// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSAFEZONECRYSTAL_HPP
#define _SLDRSAFEZONECRYSTAL_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrSafeZoneCrystal {
  SLdrSafeZoneCrystal();
  ~SLdrSafeZoneCrystal();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrActorParameters actorParameters; // 0xd29c031d
  CAssetId scannableInfoCollapsed; // 0x9b8b3323
  CAssetId scannableInfoEntangled; // 0xe36e20a7
  CAssetId scannableInfoLight; // 0xac794da8
  CAssetId scannableInfoAnnihilator; // 0xc21f264f
  int safezoneType; // 0x1115fb68
  bool initiallyEntangled; // 0xa0d9e87f
  CAssetId collapsedEffect; // 0x42a046c2
  CAssetId expandedEffect; // 0x5b91ff38
  CAssetId entangledEffect; // 0x5b8275bc
  CAssetId hurtfulEffect; // 0xadacec90
  CAssetId echoEffect; // 0x0d2e4ad3
  CAssetId normalCrystal; // 0x71efffc4
  CAssetId entangledCrystal; // 0xc3dd9b75
  CAssetId hurtfulCrystal; // 0xf1f3d90f
  CAssetId echoCrystal; // 0x1e864b83
  float maxTimeExpanded; // 0xbd30f7a3
  float maxTimeEntangled; // 0xa7bdc4f8
  float unknown_0xf0a45c32; // 0xf0a45c32
  float unknown_0xd8116003; // 0xd8116003
  float unknown_0x415046ed; // 0x415046ed
  float unknown_0xec9c01b2; // 0xec9c01b2
  float powerBeamHP; // 0x545540e5
  CAssetId powerBeamRefreshEffect; // 0x5490e214
  CVector3f hitRadius; // 0x887e8a8b
  CVector3f hitOffset; // 0xb7f5646d
  CVector3f effectOffset; // 0x41b72b2c
  SLdrSpline unknown_0xbbbee60b; // 0xbbbee60b
};

void LoadTypedefSLdrSafeZoneCrystal(SLdrSafeZoneCrystal& data, CInputStream& input);

#endif
