// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRAIWAYPOINT_HPP
#define _SLDRAIWAYPOINT_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrAIWaypoint {
  SLdrAIWaypoint();
  ~SLdrAIWaypoint();

  SLdrEditorProperties editorProperties; // 0x255a4580
  float speed; // 0x6392404e
  float pause; // 0x80f7e605
  int unknown_0xc6705a00; // 0xc6705a00
  int locatorIndex; // 0xa790c6a9
  int unknown_0x166979d4; // 0x166979d4
};

void LoadTypedefSLdrAIWaypoint(SLdrAIWaypoint& data, CInputStream& input);

#endif
