// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRGUIWIDGET_HPP
#define _SLDRGUIWIDGET_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrGuiWidgetProperties.hpp"

struct SLdrGuiWidget {
  SLdrGuiWidget();
  ~SLdrGuiWidget();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrGuiWidgetProperties widgetProperties; // 0x91cefa1e
  int controllerNumber; // 0xdb7f4aa2
};

void LoadTypedefSLdrGuiWidget(SLdrGuiWidget& data, CInputStream& input);

#endif
