// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRGUNTURRETTOP_HPP
#define _SLDRGUNTURRETTOP_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrGunTurretTop {
  SLdrGunTurretTop();
  ~SLdrGunTurretTop();

  SLdrEditorProperties editorProperties; // 0x255a4580
  float powerUpTime; // 0x3bc1d043
  float powerDownTime; // 0x838a75a4
  CAssetId pART; // 0xbf87e353
  CAssetId pART_0xaf6e671a; // 0xaf6e671a
  int alwaysFF; // 0x67c8a8f4
  int alwaysFF_0x68d8b844; // 0x68d8b844
  CColor lightColor; // 0xbd3efe7d
  int sound; // 0xe4aeeba4
  int sound_0x5d9ed447; // 0x5d9ed447
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
};

void LoadTypedefSLdrGunTurretTop(SLdrGunTurretTop& data, CInputStream& input);

#endif
