// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSUBTITLE_HPP
#define _SLDRSUBTITLE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrTextProperties.hpp"

struct SLdrSubtitle {
  SLdrSubtitle();
  ~SLdrSubtitle();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrTextProperties textProperties; // 0xe0543e66
  int textPositionX; // 0xc33a87c7
  int textPositionY; // 0x7b86e0a2
  SLdrTextProperties japanTextProperties; // 0xc8e441fa
  int japanTextPositionX; // 0x53a7f7a7
  int japanTextPositionY; // 0xeb1b90c2
  CAssetId stringTable; // 0xfd95ed2a
  int initialStringIndex; // 0x6ce46689
  float fadeInTime; // 0x90aa341f
  float fadeOutTime; // 0x7c269ebc
};

inline SLdrSubtitle::SLdrSubtitle() : editorProperties(), textProperties(), japanTextProperties(), stringTable(kInvalidAssetId) {
  textProperties.lineSpacing = 100.0f;
  textProperties.lineExtraSpace = 0;
  textProperties.characterExtraSpace = 0;
  textPositionX = 0;
  textPositionY = 0;
  japanTextProperties.textBoundingWidth = 640;
  japanTextProperties.textBoundingHeight = 448;
  japanTextProperties.unknown_0x18dd95cd = 1;
  japanTextPositionX = 0;
  japanTextPositionY = 100;
  initialStringIndex = 0;
  fadeInTime = 0.0f;
  fadeOutTime = 0.0f;
}

inline SLdrSubtitle::~SLdrSubtitle() {}

#endif
