// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTEXTPANE_HPP
#define _SLDRTEXTPANE_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrTextProperties.hpp"
#include "rstl/string.hpp"

struct SLdrTextPane {
  SLdrTextPane();
  ~SLdrTextPane();

  SLdrEditorProperties editorProperties; // 0x255a4580
  rstl::string guiLabel; // 0x73939407
  SLdrTextProperties textProperties; // 0xe0543e66
  SLdrTextProperties japanTextProperties; // 0xc8e441fa
  CVector3f pivotOffset; // 0xdef21bf5
  CAssetId defaultString; // 0xe7ac3927
  rstl::string defaultStringName; // 0xd501c87e
  int blend_Mode; // 0x94f0365c
  float fadeInTime; // 0x90aa341f
  float fadeOutTime; // 0x7c269ebc
  bool depth_Compare; // 0x94c01b0c
  bool depth_Update; // 0xaed25a51
  bool depth_Backwards; // 0x35dc43d0
};

void LoadTypedefSLdrTextPane(SLdrTextPane& data, CInputStream& input);

#endif
