// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRVISORFLARE_HPP
#define _SLDRVISORFLARE_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrFlareDef {
  SLdrFlareDef();
  ~SLdrFlareDef();

  CAssetId texture; // 0xd1f65872
  float position; // 0xcb99b4da
  float scale; // 0x2c51a676
  CColor color; // 0x37c7d09d
};

inline SLdrFlareDef::SLdrFlareDef() : texture(kInvalidAssetId), color(CColor::Green()) {
  position = 0.0f;
  scale = 0.0f;
  color = CColor(1.0f, 1.0f, 1.0f, 1.0f);
}

inline SLdrFlareDef::~SLdrFlareDef() {}

inline void LoadTypedefFlareDef(SLdrFlareDef& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0xd1f65872: {
      sldrThis.texture = CAssetId(input.ReadInt32());
      break;
    }
    case 0xcb99b4da: {
      sldrThis.position = input.ReadFloat();
      break;
    }
    case 0x2c51a676: {
      sldrThis.scale = input.ReadFloat();
      break;
    }
    case 0x37c7d09d: {
      sldrThis.color = CColor(input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrVisorFlare {
  SLdrVisorFlare();
  ~SLdrVisorFlare();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int blendMode; // 0xcb13ef46
  bool constantScale; // 0xe0c5fc06
  float fadeTime; // 0xd4124c4c
  float fadeFactor; // 0xd6fb31bf
  float rotateFactor; // 0x3161f38c
  int combatVisorMode; // 0x43b503a6
  bool unknown_0xa51f243e; // 0xa51f243e
  bool noOcclusionTest; // 0x050881a9
  SLdrFlareDef flare1; // 0x3c257223
  SLdrFlareDef flare2; // 0x05a84ee6
  SLdrFlareDef flare3; // 0x12d35aa5
  SLdrFlareDef flare4; // 0x76b2376c
  SLdrFlareDef flare5; // 0x61c9232f
};

inline SLdrVisorFlare::SLdrVisorFlare() : editorProperties(), flare1(), flare2(), flare3(), flare4(), flare5() {
  blendMode = 0;
  constantScale = true;
  fadeTime = 0.1f;
  fadeFactor = 1.0f;
  rotateFactor = 2.0f;
  combatVisorMode = 0;
  unknown_0xa51f243e = true;
  noOcclusionTest = false;
  flare1.scale = 1.0f;
  flare2.position = 0.25f;
  flare2.scale = 1.0f;
  flare3.position = 0.5f;
  flare3.scale = 1.0f;
  flare4.position = 0.75f;
  flare4.scale = 1.0f;
  flare5.position = 1.0f;
  flare5.scale = 1.0f;
}

inline SLdrVisorFlare::~SLdrVisorFlare() {}

#endif
