// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSTREAMEDMOVIE_HPP
#define _SLDRSTREAMEDMOVIE_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "rstl/string.hpp"

struct SLdrStreamedMovie {
  SLdrStreamedMovie();
  ~SLdrStreamedMovie();

  SLdrEditorProperties editorProperties; // 0x255a4580
  rstl::string movieFile; // 0x582b84a8
  bool loop; // 0xeda47ff6
  bool videoFilterEnabled; // 0x36963bcc
  int whenToDraw; // 0xa78ac0c0
  int volume; // 0x80c66c37
  int volumeType; // 0xe1ff4f04
  float cacheLength; // 0xad9eb77f
  float fadeOutTime; // 0x7c269ebc
};

void LoadTypedefSLdrStreamedMovie(SLdrStreamedMovie& data, CInputStream& input);

#endif
