// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRFISHCLOUDMODIFIER_HPP
#define _SLDRFISHCLOUDMODIFIER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrFishCloudModifier {
  SLdrFishCloudModifier();
  ~SLdrFishCloudModifier();

  SLdrEditorProperties editorProperties; // 0x255a4580
  bool active; // 0xc6bb2f45
  bool unknown_0xea2d4ca8; // 0xea2d4ca8
  bool rotate; // 0x923109d6
  float influenceDistance; // 0x7864ad0e
  float influencePriority; // 0xaba2d9ed
};

void LoadTypedefSLdrFishCloudModifier(SLdrFishCloudModifier& data, CInputStream& input);

#endif
