// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTARGETINGPOINT_HPP
#define _SLDRTARGETINGPOINT_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrTargetingPoint {
  SLdrTargetingPoint();
  ~SLdrTargetingPoint();

  SLdrEditorProperties editorProperties; // 0x255a4580
};

void LoadTypedefSLdrTargetingPoint(SLdrTargetingPoint& data, CInputStream& input);

#endif
