// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSPIDERBALLWAYPOINT_HPP
#define _SLDRSPIDERBALLWAYPOINT_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrSpiderBallWaypoint {
  SLdrSpiderBallWaypoint();
  ~SLdrSpiderBallWaypoint();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int flags; // 0x5d817483
};

void LoadTypedefSLdrSpiderBallWaypoint(SLdrSpiderBallWaypoint& data, CInputStream& input);

#endif
