// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSEQUENCETIMER_HPP
#define _SLDRSEQUENCETIMER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrSequenceConnections.hpp"

struct SLdrSequenceTimer {
  SLdrSequenceTimer();
  ~SLdrSequenceTimer();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrSequenceConnections sequenceConnections; // non-matching name, 0xef5c94e9
  float startTime; // 0xb8bd2175
  float maxTime; // 0x03e7b2b4
  float loopStartTime; // 0xacf9ca5f
  bool isAutostart; // 0x42c6e2b2
  bool isLoop; // 0xc08d1b93
  bool takeExternalTime; // 0x27b3b082
};

inline SLdrSequenceTimer::SLdrSequenceTimer() : editorProperties(), sequenceConnections() {
  editorProperties.unknown_0x5d298a43 = 3;
  startTime = 0.0f;
  maxTime = 0.0f;
  loopStartTime = 0.0f;
  isAutostart = false;
  isLoop = false;
  takeExternalTime = false;
}

inline SLdrSequenceTimer::~SLdrSequenceTimer() {}

#endif
