// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSCANTREESLIDER_HPP
#define _SLDRSCANTREESLIDER_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "rstl/string.hpp"

struct SLdrScanTreeSlider {
  SLdrScanTreeSlider();
  ~SLdrScanTreeSlider();

  SLdrEditorProperties editorProperties; // 0x255a4580
  CAssetId nodeName; // 0x46219bac
  rstl::string stringName; // 0x32698bd6
  int unknown_0x0261a4e0; // 0x0261a4e0
};

void LoadTypedefSLdrScanTreeSlider(SLdrScanTreeSlider& data, CInputStream& input);

#endif
