// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSOUND_HPP
#define _SLDRSOUND_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrSurroundPan {
  SLdrSurroundPan();
  ~SLdrSurroundPan();

  float pan; // 0xdf4353a3
  float surroundPan; // 0x482b88aa
};

void LoadTypedefSLdrSurroundPan(SLdrSurroundPan& data, CInputStream& input);

struct SLdrSound {
  SLdrSound();
  ~SLdrSound();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int sound; // 0x5f7c352e
  float maxAudibleDistance; // 0x214e48a0
  float dropOff; // 0x08bf2e54
  float delayTime; // 0x8e16e012
  int minVolume; // 0x57619496
  int maxVolume; // 0xc712847c
  int priority; // 0x42087650
  SLdrSurroundPan surroundPan; // 0x0bb62639
  bool loop; // 0xeda47ff6
  bool ambient; // 0x8971b7a7
  bool viewportDependent; // 0x84f3ac3d
  bool autoStart; // 0x3217dff8
  bool canOcclude; // 0x94721163
  bool useRoomAcoustics; // 0x85707354
  bool persistent; // 0xea03e258
  bool playAlways; // 0x0d7f8c7f
  bool allArea; // 0xe45c3499
  bool soundIsMusic; // 0x76d40091
  int pitch; // 0x8a764463
  int echoVisorMaxVolume; // 0x69ec9107
};

void LoadTypedefSLdrSound(SLdrSound& data, CInputStream& input);

#endif
