// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRDAMAGEABLETRIGGERORIENTATED_HPP
#define _SLDRDAMAGEABLETRIGGERORIENTATED_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrHealthInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrVisorParameters.hpp"

struct SLdrDamageableTriggerOrientated {
  SLdrDamageableTriggerOrientated();
  ~SLdrDamageableTriggerOrientated();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrHealthInfo health; // 0xcf90d15e
  SLdrDamageVulnerability vulnerability; // 0x7b71ae90
  bool orbitable; // 0x704b5369
  bool enableSeekerLockOn; // non-matching name, 0x5dfd7820
  bool invulnerable; // 0x6652bdd7
  SLdrVisorParameters visor; // 0x05ad250e
};

inline SLdrDamageableTriggerOrientated::SLdrDamageableTriggerOrientated() : editorProperties(), health(), vulnerability(), visor() {
  orbitable = false;
  enableSeekerLockOn = false;
  invulnerable = false;
}

inline SLdrDamageableTriggerOrientated::~SLdrDamageableTriggerOrientated() {}

#endif
