// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDREMPERORINGSTAGE1_HPP
#define _SLDREMPERORINGSTAGE1_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAnimationSet.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAudioPlaybackParms.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrHealthInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPlasmaBeamInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrShockWaveInfo.hpp"

struct SLdrEmperorIngStage1TentacleData {
  SLdrEmperorIngStage1TentacleData();
  ~SLdrEmperorIngStage1TentacleData();

  SLdrHealthInfo health; // 0xcf90d15e
  SLdrDamageVulnerability normalVulnerability; // 0x29df61e1
  SLdrDamageVulnerability warpAttackVulnerability; // 0x8d7378a4
  SLdrDamageVulnerability meleeAttackVulnerability; // 0x6c79054f
  SLdrDamageVulnerability projectileAttackVulnerability; // 0x3c2d2492
  float stayRetractedTime; // 0x491c2657
  int tentacleDamagedSound; // 0xe19f4608
};

inline SLdrEmperorIngStage1TentacleData::SLdrEmperorIngStage1TentacleData() : health(), normalVulnerability(), warpAttackVulnerability(), meleeAttackVulnerability(), projectileAttackVulnerability() {
  stayRetractedTime = 0.0f;
  tentacleDamagedSound = 0;
}

inline SLdrEmperorIngStage1TentacleData::~SLdrEmperorIngStage1TentacleData() {}

inline void LoadTypedefEmperorIngStage1TentacleData(SLdrEmperorIngStage1TentacleData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0xcf90d15e: {
      LoadTypedefHealthInfo(sldrThis.health, input);
      break;
    }
    case 0x29df61e1: {
      LoadTypedefDamageVulnerability(sldrThis.normalVulnerability, input);
      break;
    }
    case 0x8d7378a4: {
      LoadTypedefDamageVulnerability(sldrThis.warpAttackVulnerability, input);
      break;
    }
    case 0x6c79054f: {
      LoadTypedefDamageVulnerability(sldrThis.meleeAttackVulnerability, input);
      break;
    }
    case 0x3c2d2492: {
      LoadTypedefDamageVulnerability(sldrThis.projectileAttackVulnerability, input);
      break;
    }
    case 0x491c2657: {
      sldrThis.stayRetractedTime = input.ReadFloat();
      break;
    }
    case 0xe19f4608: {
      sldrThis.tentacleDamagedSound = input.ReadInt32();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrEmperorIngStage1MeleeData {
  SLdrEmperorIngStage1MeleeData();
  ~SLdrEmperorIngStage1MeleeData();

  SLdrDamageInfo damage; // 0x337f9524
};

inline SLdrEmperorIngStage1MeleeData::SLdrEmperorIngStage1MeleeData() : damage() {
}

inline SLdrEmperorIngStage1MeleeData::~SLdrEmperorIngStage1MeleeData() {}

inline void LoadTypedefEmperorIngStage1MeleeData(SLdrEmperorIngStage1MeleeData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x337f9524: {
      LoadTypedefDamageInfo(sldrThis.damage, input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrEmperorIngStage1ProjectileAttackData {
  SLdrEmperorIngStage1ProjectileAttackData();
  ~SLdrEmperorIngStage1ProjectileAttackData();

  CAssetId projectile; // 0xef485db9
  SLdrDamageInfo projectileDamage; // 0x553b1339
  CAssetId projectileVisorEffect; // 0x8f8c64a0
};

inline SLdrEmperorIngStage1ProjectileAttackData::SLdrEmperorIngStage1ProjectileAttackData() : projectile(kInvalidAssetId), projectileDamage(), projectileVisorEffect(kInvalidAssetId) {
}

inline SLdrEmperorIngStage1ProjectileAttackData::~SLdrEmperorIngStage1ProjectileAttackData() {}

inline void LoadTypedefEmperorIngStage1ProjectileAttackData(SLdrEmperorIngStage1ProjectileAttackData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0xef485db9: {
      sldrThis.projectile = CAssetId(input.ReadInt32());
      break;
    }
    case 0x553b1339: {
      LoadTypedefDamageInfo(sldrThis.projectileDamage, input);
      break;
    }
    case 0x8f8c64a0: {
      sldrThis.projectileVisorEffect = CAssetId(input.ReadInt32());
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrEmperorIngStage1WarpAttackData {
  SLdrEmperorIngStage1WarpAttackData();
  ~SLdrEmperorIngStage1WarpAttackData();

  CAssetId portalEffect; // 0x4a7c4ec2
  SLdrAnimationSet attackTip; // 0xf10b6ef6
  SLdrDamageInfo stabDamage; // 0x946016a9
  int unknown_0xecfab026; // 0xecfab026
  int unknown_0x94880277; // 0x94880277
  int sound; // non-matching name, 0x1c3e84b6
  int sound_0xa93f0198; // non-matching name, 0xa93f0198
};

inline SLdrEmperorIngStage1WarpAttackData::SLdrEmperorIngStage1WarpAttackData() : portalEffect(kInvalidAssetId), attackTip(), stabDamage() {
  unknown_0xecfab026 = -1;
  unknown_0x94880277 = -1;
  sound = 0;
  sound_0xa93f0198 = 0;
}

inline SLdrEmperorIngStage1WarpAttackData::~SLdrEmperorIngStage1WarpAttackData() {}

inline void LoadTypedefEmperorIngStage1WarpAttackData(SLdrEmperorIngStage1WarpAttackData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x4a7c4ec2: {
      sldrThis.portalEffect = CAssetId(input.ReadInt32());
      break;
    }
    case 0xf10b6ef6: {
      LoadTypedefAnimationSet(sldrThis.attackTip, input);
      break;
    }
    case 0x946016a9: {
      LoadTypedefDamageInfo(sldrThis.stabDamage, input);
      break;
    }
    case 0xecfab026: {
      sldrThis.unknown_0xecfab026 = input.ReadInt32();
      break;
    }
    case 0x94880277: {
      sldrThis.unknown_0x94880277 = input.ReadInt32();
      break;
    }
    case 0x1c3e84b6: {
      sldrThis.sound = input.ReadInt32();
      break;
    }
    case 0xa93f0198: {
      sldrThis.sound_0xa93f0198 = input.ReadInt32();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrEmperorIngStage1TauntAttackData {
  SLdrEmperorIngStage1TauntAttackData();
  ~SLdrEmperorIngStage1TauntAttackData();

  float loopDuration; // 0xcee68723
  int destroyPercentage; // 0x01274d6e
  SLdrShockWaveInfo shockWaveInfo; // 0x8f4787cb
  int shockWaveTravelSound; // 0x25af490e
};

inline SLdrEmperorIngStage1TauntAttackData::SLdrEmperorIngStage1TauntAttackData() : shockWaveInfo() {
  loopDuration = 0.0f;
  destroyPercentage = 0;
  shockWaveTravelSound = 0;
}

inline SLdrEmperorIngStage1TauntAttackData::~SLdrEmperorIngStage1TauntAttackData() {}

inline void LoadTypedefEmperorIngStage1TauntAttackData(SLdrEmperorIngStage1TauntAttackData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0xcee68723: {
      sldrThis.loopDuration = input.ReadFloat();
      break;
    }
    case 0x01274d6e: {
      sldrThis.destroyPercentage = input.ReadInt32();
      break;
    }
    case 0x8f4787cb: {
      LoadTypedefShockWaveInfo(sldrThis.shockWaveInfo, input);
      break;
    }
    case 0x25af490e: {
      sldrThis.shockWaveTravelSound = input.ReadInt32();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrEmperorIngStage1BeamAttackData {
  SLdrEmperorIngStage1BeamAttackData();
  ~SLdrEmperorIngStage1BeamAttackData();

  SLdrPlasmaBeamInfo beamInfo; // 0x1598012a
  SLdrDamageInfo damage; // 0x337f9524
  int sound; // 0x5f7c352e
};

inline SLdrEmperorIngStage1BeamAttackData::SLdrEmperorIngStage1BeamAttackData() : beamInfo(), damage() {
  beamInfo.length = 500.0f;
  beamInfo.expansionSpeed = 4.0f;
  beamInfo.lifeTime = 1.0f;
  beamInfo.pulseSpeed = 20.0f;
  beamInfo.shutdownTime = 0.25f;
  beamInfo.pulseEffectScale = 2.0f;
  beamInfo.innerColor = CColor(0.49803901f, 0.49803901f, 0.49803901f, 0.49803901f);
  beamInfo.outerColor = CColor(0.60000002f, 0.60000002f, 0.0f, 0.49803901f);
  sound = 0;
}

inline SLdrEmperorIngStage1BeamAttackData::~SLdrEmperorIngStage1BeamAttackData() {}

inline void LoadTypedefEmperorIngStage1BeamAttackData(SLdrEmperorIngStage1BeamAttackData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x1598012a: {
      LoadTypedefPlasmaBeamInfo(sldrThis.beamInfo, input);
      break;
    }
    case 0x337f9524: {
      LoadTypedefDamageInfo(sldrThis.damage, input);
      break;
    }
    case 0x5f7c352e: {
      sldrThis.sound = input.ReadInt32();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrEmperorIngStage1Data {
  SLdrEmperorIngStage1Data();
  ~SLdrEmperorIngStage1Data();

  SLdrEmperorIngStage1TentacleData tentacle; // 0xb3c6398f
  SLdrEmperorIngStage1MeleeData melee; // 0xf59f9a60
  SLdrEmperorIngStage1ProjectileAttackData projectile; // 0xa1cda0b6
  SLdrEmperorIngStage1WarpAttackData warp; // 0x85f36473
  SLdrEmperorIngStage1TauntAttackData tauntAttack; // 0xb4bc04c4
  SLdrEmperorIngStage1BeamAttackData beamAttack; // 0x8e6d20ec
  float heartExposedTime; // 0xa588afd1
  float unknown_0x905938b8; // 0x905938b8
  float unknown_0xb826317a; // 0xb826317a
  SLdrAudioPlaybackParms heartDamageSound; // 0x88232388
  float turnSpeedAccel; // 0xc36ae5ca
  float maxTurnSpeedNormal; // 0xd30d9bb9
  float maxTurnSpeedMelee; // 0xb02cd31f
  float unknown_0xe5a7c358; // 0xe5a7c358
  int vulnerabilityChangeSound; // 0x93357240
  float tauntFrequency; // 0x293a0c19
  float attackIntervalMin; // 0x31ebf869
  float attackIntervalMax; // 0xd78b5788
};

inline SLdrEmperorIngStage1Data::SLdrEmperorIngStage1Data() : tentacle(), melee(), projectile(), warp(), tauntAttack(), beamAttack(), heartDamageSound(), vulnerabilityChangeSound(-1) {
  heartExposedTime = 0.0f;
  unknown_0x905938b8 = 0.0f;
  unknown_0xb826317a = 0.0f;
  turnSpeedAccel = 0.0f;
  maxTurnSpeedNormal = 0.0f;
  maxTurnSpeedMelee = 0.0f;
  unknown_0xe5a7c358 = 0.0f;
  tauntFrequency = 0.0f;
  attackIntervalMin = 0.0f;
  attackIntervalMax = 0.0f;
}

inline SLdrEmperorIngStage1Data::~SLdrEmperorIngStage1Data() {}

inline void LoadTypedefEmperorIngStage1Data(SLdrEmperorIngStage1Data& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0xb3c6398f: {
      LoadTypedefEmperorIngStage1TentacleData(sldrThis.tentacle, input);
      break;
    }
    case 0xf59f9a60: {
      LoadTypedefEmperorIngStage1MeleeData(sldrThis.melee, input);
      break;
    }
    case 0xa1cda0b6: {
      LoadTypedefEmperorIngStage1ProjectileAttackData(sldrThis.projectile, input);
      break;
    }
    case 0x85f36473: {
      LoadTypedefEmperorIngStage1WarpAttackData(sldrThis.warp, input);
      break;
    }
    case 0xb4bc04c4: {
      LoadTypedefEmperorIngStage1TauntAttackData(sldrThis.tauntAttack, input);
      break;
    }
    case 0x8e6d20ec: {
      LoadTypedefEmperorIngStage1BeamAttackData(sldrThis.beamAttack, input);
      break;
    }
    case 0xa588afd1: {
      sldrThis.heartExposedTime = input.ReadFloat();
      break;
    }
    case 0x905938b8: {
      sldrThis.unknown_0x905938b8 = input.ReadFloat();
      break;
    }
    case 0xb826317a: {
      sldrThis.unknown_0xb826317a = input.ReadFloat();
      break;
    }
    case 0x88232388: {
      LoadTypedefAudioPlaybackParms(sldrThis.heartDamageSound, input);
      break;
    }
    case 0xc36ae5ca: {
      sldrThis.turnSpeedAccel = input.ReadFloat();
      break;
    }
    case 0xd30d9bb9: {
      sldrThis.maxTurnSpeedNormal = input.ReadFloat();
      break;
    }
    case 0xb02cd31f: {
      sldrThis.maxTurnSpeedMelee = input.ReadFloat();
      break;
    }
    case 0xe5a7c358: {
      sldrThis.unknown_0xe5a7c358 = input.ReadFloat();
      break;
    }
    case 0x93357240: {
      sldrThis.vulnerabilityChangeSound = input.ReadInt32();
      break;
    }
    case 0x293a0c19: {
      sldrThis.tauntFrequency = input.ReadFloat();
      break;
    }
    case 0x31ebf869: {
      sldrThis.attackIntervalMin = input.ReadFloat();
      break;
    }
    case 0xd78b5788: {
      sldrThis.attackIntervalMax = input.ReadFloat();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrEmperorIngStage1 {
  SLdrEmperorIngStage1();
  ~SLdrEmperorIngStage1();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrEmperorIngStage1Data data; // 0x4a1e493b
};

inline SLdrEmperorIngStage1::SLdrEmperorIngStage1() : editorProperties(), patterned(), actorInformation(), data() {
  patterned.creatureSize = 2;
}

inline SLdrEmperorIngStage1::~SLdrEmperorIngStage1() {}

#endif
