// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRHUDMEMO_HPP
#define _SLDRHUDMEMO_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrHUDMemo {
  SLdrHUDMemo();
  ~SLdrHUDMemo();

  SLdrEditorProperties editorProperties; // 0x255a4580
  float displayTime; // 0x1a26c1cc
  bool clearWindow; // 0x84e2496f
  bool player1; // 0xa8fadfa5
  bool player2; // 0xef5aa575
  bool player3; // 0xd23a8cc5
  bool player4; // 0x601a50d5
  bool typeOut; // 0xafd0158e
  bool useOriginator; // 0xbd6f7b11
  int displayType; // 0x4ab3b95b
  CAssetId string; // 0x9182250c
};

inline SLdrHUDMemo::SLdrHUDMemo() : editorProperties(), string(kInvalidAssetId) {
  displayTime = 3.0f;
  clearWindow = true;
  player1 = true;
  player2 = true;
  player3 = true;
  player4 = true;
  typeOut = true;
  useOriginator = false;
  displayType = 0;
}

inline SLdrHUDMemo::~SLdrHUDMemo() {}

#endif
