// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRACTORROTATE_HPP
#define _SLDRACTORROTATE_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrRotationSplines {
  SLdrRotationSplines();
  ~SLdrRotationSplines();

  SLdrSpline xRotation; // 0x69d8447d
  SLdrSpline yRotation; // 0xd0239f95
  SLdrSpline zRotation; // 0xc15ef5ec
};

void LoadTypedefSLdrRotationSplines(SLdrRotationSplines& data, CInputStream& input);

struct SLdrScaleSplines {
  SLdrScaleSplines();
  ~SLdrScaleSplines();

  SLdrSpline xScale; // 0xf437a62f
  SLdrSpline yScale; // 0x6f92ea40
  SLdrSpline zScale; // 0x180c38b0
};

void LoadTypedefSLdrScaleSplines(SLdrScaleSplines& data, CInputStream& input);

struct SLdrActorRotate {
  SLdrActorRotate();
  ~SLdrActorRotate();

  SLdrEditorProperties editorProperties; // 0x255a4580
  uint flagsActorRotate; // 0xf11c6c2b
  float duration; // 0x8b51e23f
  SLdrRotationSplines rotationControls; // 0xefe4ea57
  SLdrScaleSplines scaleControls; // 0x2f7ec0a2
};

void LoadTypedefSLdrActorRotate(SLdrActorRotate& data, CInputStream& input);

#endif
