// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCRYSTALLITE_HPP
#define _SLDRCRYSTALLITE_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrCrystallite {
  SLdrCrystallite();
  ~SLdrCrystallite();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  float waypointApproachDistance; // 0x733bd27c
  float wallTurnSpeed; // 0xac47c628
  float floorTurnSpeed; // 0x8e4f7b29
  float downTurnSpeed; // 0x3d3c1b76
  float visibleDistance; // 0xa72530e8
  float forwardMovingPriority; // 0x5e6a54b8
  float stunTime; // 0x7e192395
};

void LoadTypedefSLdrCrystallite(SLdrCrystallite& data, CInputStream& input);

#endif
