// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRDAMAGEABLETRIGGER_HPP
#define _SLDRDAMAGEABLETRIGGER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrHealthInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrVisorParameters.hpp"

struct SLdrDamageableTrigger {
  SLdrDamageableTrigger();
  ~SLdrDamageableTrigger();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrHealthInfo health; // 0xcf90d15e
  SLdrDamageVulnerability vulnerability; // 0x7b71ae90
  bool orbitable; // 0x704b5369
  bool enableSeekerLockOn; // 0x5dfd7820
  bool invulnerable; // 0x6652bdd7
  SLdrVisorParameters visor; // 0x05ad250e
};

void LoadTypedefSLdrDamageableTrigger(SLdrDamageableTrigger& data, CInputStream& input);

#endif
