// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTWEAKPLAYER_HPP
#define _SLDRTWEAKPLAYER_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "rstl/string.hpp"

struct SLdrTweakPlayer_DarkWorld {
  SLdrTweakPlayer_DarkWorld();
  ~SLdrTweakPlayer_DarkWorld();

  float damageGracePeriod; // 0x4985bc73
  float unknown_0xa4e33ef0; // 0xa4e33ef0
  SLdrDamageInfo damagePerSecond; // 0xf9bf59a2
  float darkSuitDamageReduction; // 0x333b7549
  float darkSuitEffectGenerationScale; // 0xee452490
  float darkSuitEffectColorScale; // 0x19275a97
};

void LoadTypedefSLdrTweakPlayer_DarkWorld(SLdrTweakPlayer_DarkWorld& data, CInputStream& input);

struct SLdrTweakPlayer_GrappleBeam {
  SLdrTweakPlayer_GrappleBeam();
  ~SLdrTweakPlayer_GrappleBeam();

  float travel_Speed; // 0x14849367
  float x_Wave_Amplitude; // 0x6c6e6f3c
  float z_Wave_Amplitude; // 0x88aa6e41
  float angle_Phase_Delta; // 0x2aab8dda
};

void LoadTypedefSLdrTweakPlayer_GrappleBeam(SLdrTweakPlayer_GrappleBeam& data, CInputStream& input);

struct SLdrTweakPlayer_Motion {
  SLdrTweakPlayer_Motion();
  ~SLdrTweakPlayer_Motion();

  float forwardAccelNormal; // 0x18d0b2da
  float forwardAccelAir; // 0x84f61ac5
  float forwardAccelIce; // 0xedb06c1d
  float forwardAccelOrganic; // 0x56f9f2af
  float forwardAccelWater; // 0xd05b643f
  float forwardAccelLava; // 0x122ce118
  float forwardAccelPhazon; // 0xf848dabe
  float forwardAccelShrubbery; // 0x68ac6028
  float rotationalAccelNormal; // 0xcd4ee9fc
  float rotationalAccelAir; // 0x3c461db2
  float rotationalAccelIce; // 0x55006b6a
  float rotationalAccelOrganic; // 0x8421e909
  float rotationalAccelWater; // 0x2e41a61d
  float rotationalAccelLava; // 0xdcf5b580
  float rotationalAccelPhazon; // 0x2dd68198
  float rotationalAccelShrubbery; // 0x1a946073
  float movementFrictionNormal; // 0xd4a25028
  float movementFrictionAir; // 0x2b5cb136
  float movementFrictionIce; // 0x421ac7ee
  float movementFrictionOrganic; // 0x0586137d
  float movementFrictionWater; // 0xaece038b
  float movementFrictionLava; // 0x3637e815
  float movementFrictionPhazon; // 0x343a384c
  float movementFrictionShrubbery; // 0x0caf4624
  float rotationFrictionNormal; // 0x34b2c148
  float rotationFrictionAir; // 0xb917ae8a
  float rotationFrictionIce; // 0xd051d852
  float rotationFrictionOrganic; // 0x48d462b4
  float rotationFrictionWater; // 0x6bb67d81
  float rotationFrictionLava; // 0xf4725cad
  float rotationFrictionPhazon; // 0xd42aa92c
  float rotationFrictionShrubbery; // 0x319526db
  float rotationMaxSpeedNormal; // 0x4b6eb6ca
  float rotationMaxSpeedAir; // 0xc107f3db
  float rotationMaxSpeedIce; // 0xa8418503
  float rotationMaxSpeedOrganic; // 0x4b1d5ccf
  float rotationMaxSpeedWater; // 0xddcc44cd
  float rotationMaxSpeedLava; // 0xe8662d92
  float rotationMaxSpeedPhazon; // 0xabf6deae
  float rotationMaxSpeedShrubbery; // 0x3c3f9884
  float forwardMaxSpeedNormal; // 0xffd4a030
  float forwardMaxSpeedAir; // 0x59dfbcb9
  float forwardMaxSpeedIce; // 0x3099ca61
  float forwardMaxSpeedOrganic; // 0x16c1fddb
  float forwardMaxSpeedWater; // 0x6c648931
  float forwardMaxSpeedLava; // 0x4b42f5a9
  float forwardMaxSpeedPhazon; // 0x1f4cc854
  float forwardMaxSpeedShrubbery; // 0xb3408173
  float gravitationalAccel; // 0x14b78aaf
  float fluidGravitationalAccel; // 0x2c7620d3
  float verticalJumpAccel; // 0x0c2c91f7
  float horizontalJumpAccel; // 0x938c77d4
  float verticalDoubleJumpAccel; // 0x13c95dfd
  float horizontalDoubleJumpAccel; // 0x8e41fed2
  float waterJumpFactor; // 0xb261fa30
  float waterBallJumpFactor; // 0x6ae560e9
  float lavaJumpFactor; // 0x03149633
  float lavaBallJumpFactor; // 0xd7b3f3ea
  float phazonJumpFactor; // 0xaf1450a2
  float phazonBallJumpFactor; // 0x980d701a
  float allowedJumpTime; // 0xa805feae
  float allowedDoubleJumpTime; // 0x233e3199
  float minDoubleJumpWindow; // 0x97f30b95
  float maxDoubleJumpWindow; // 0x4c4c5872
  float allowedJumpBootTime; // 0x9bb73a0b
  float minJumpTime; // 0x4c8d664c
  float minDoubleJumpTime; // 0x1fc20169
  float ledgeFallTime; // 0xe7a5d759
  float doubleJumpImpulse; // 0x7044b295
  float backwardsForceMultiplier; // 0xd82380a6
  float bombJumpHeight; // 0x2a2e4100
  float bombJumpRadius; // 0x905545e6
  float gravityBoostTime; // 0x229460be
  float gravityBoostForce; // 0x0e238fd3
  float gravityBoostCancelDampening; // 0xdc92a0ac
  bool gravityBoostMultipleAllowed; // 0xe1fefd3c
};

void LoadTypedefSLdrTweakPlayer_Motion(SLdrTweakPlayer_Motion& data, CInputStream& input);

struct SLdrTweakPlayer_Misc {
  SLdrTweakPlayer_Misc();
  ~SLdrTweakPlayer_Misc();

  float eyeOffset; // 0xb49b008e
  float normalTurnFactor; // 0xb0291470
  float freeLookTurnFactor; // 0x287892ab
  float freeLookMaxX; // 0x79f8ef93
  float freeLookMaxZ; // 0x34304e98
  float freeLookSpeed; // 0xba27556f
  float freeLookSnapSpeed; // 0xd7d7828e
  float freeLookFadeAngle; // 0x0e0c431e
  float freeLookMinAngle; // 0x2c1da0ec
  float freeLookCenteredTime; // 0xe11788e4
  float freeLookDampenFactor; // 0xc982754e
  bool nullAnalogScales; // 0xfb5c81a9
  float unknown_0xfb909bc3; // 0xfb909bc3
  float leftAnalogMax; // 0xf1f038de
  float rightAnalogMax; // 0x2b1f5094
};

void LoadTypedefSLdrTweakPlayer_Misc(SLdrTweakPlayer_Misc& data, CInputStream& input);

struct SLdrTweakPlayer_AimStuff {
  SLdrTweakPlayer_AimStuff();
  ~SLdrTweakPlayer_AimStuff();

  float aimMinTime; // 0x27c60d0a
  float aimMaxTime; // 0xb7b51de0
  float aimMaxDistance; // 0xf77d0359
  float aimMaxAngleLeft; // 0xde887cca
  float aimMaxAngleRight; // 0xb4b07d5d
  float aimMaxAngleUp; // 0xe5f8c567
  float aimMaxAngleDown; // 0x9774749d
  float aimAnglePerSecond; // 0x133f3002
  float aimThresholdDistance; // 0x96fab602
  float aimTurnAnglePerSecond; // 0x94164a2f
  float aimNewTargetRadius; // 0x54354c80
  float aimBoxWidth; // 0x5361ce18
  float aimBoxHeight; // 0x4b2e9260
  float aimTargetTimer; // 0x3b9a3789
  float aimAssistHorizontalAngle; // 0x38dd0b85
  float aimAssistVerticalAngle; // 0x1157883e
};

void LoadTypedefSLdrTweakPlayer_AimStuff(SLdrTweakPlayer_AimStuff& data, CInputStream& input);

struct SLdrTweakPlayer_Orbit {
  SLdrTweakPlayer_Orbit();
  ~SLdrTweakPlayer_Orbit();

  float orbitCloseMinDistance; // 0x68738246
  float orbitCloseNormalDistance; // 0x991180ef
  float orbitCloseMaxDistance; // 0x398a391b
  float orbitFarMinDistance; // 0x495caff1
  float orbitFarNormalDistance; // 0xd2fb0fed
  float orbitFarMaxDistance; // 0x18a514ac
  float orbitCarcassMinDistance; // 0x31072813
  float orbitCarcassNormalDistance; // 0xf0e68dab
  float orbitCarcassMaxDistance; // 0x60fe934e
  float orbitMaxAngularChange; // 0xa6332f81
  float orbitModeTimer; // 0x663a6f89
  float orbitCameraSpeed; // 0xe60bbbbb
  float orbitUpperAngle; // 0x914977b4
  float orbitLowerAngle; // 0xee0c7156
  float orbitHorizAngle; // 0xc6960be2
  float orbitUpperCameraAngle; // 0x6f6dffdd
  float orbitLowerCameraAngle; // 0x48c63796
  float orbitMaxTargetDistance; // 0x598beb71
  float orbitMaxLockDistance; // 0x30b2f98e
  float unknown_0x55f7d145; // 0x55f7d145
  float orbitDistanceThreshold; // 0xf034335c
  int orbitZoneWidth; // 0x40ae584e
  int orbitZoneHeight; // 0x111e9dec
  int orbitZoneCentreX; // 0x58ee9d03
  int orbitZoneCentreY; // 0xe052fa66
  int orbitZoneIdealX; // 0xc452b61e
  int orbitZoneIdealY; // 0x7ceed17b
  int orbitScanZoneWidth; // 0x44989f30
  int orbitScanZoneHeight; // 0xa6a7f710
  int orbitScanZoneCentreX; // 0xec529a5e
  int orbitScanZoneCentreY; // 0x54eefd3b
  int orbitScanZoneIdealX; // 0x73ebdce2
  int orbitScanZoneIdealY; // 0xcb57bb87
  float orbitBoxWidth; // 0xd2a8cc1f
  float orbitBoxHeight; // 0xd5cbcec1
  float orbitMinCameraPitchDistance; // 0x141ed3b9
  float orbitMaxCameraPitchDistance; // 0x72fbb5cd
  float unknown_0x478c15f9; // 0x478c15f9
  float orbitZRange; // 0x93b712ba
  float orbitSelectionCloseAngle; // 0x7b4688ce
  float orbitSelectionMaxAngle; // 0x2e0cf3cd
  float unknown_0x90b71b2e; // 0x90b71b2e
  float orbitPreventionTime; // 0x775761c5
  bool orbitDash; // 0xfa255139
  bool orbitDashUsesTap; // 0x8f80e39e
  float orbitDashTapTime; // 0xd290d7b5
  float orbitDashStickThreshold; // 0x2421b618
  float orbitDashDoubleJumpImpulse; // 0xb814530b
  float orbitDashVerticalDoubleJumpAccel; // 0x75a00cfb
  float orbitDashHorizontalDoubleJumpAccel; // 0xc4775e5f
};

void LoadTypedefSLdrTweakPlayer_Orbit(SLdrTweakPlayer_Orbit& data, CInputStream& input);

struct SLdrTweakPlayer_ScanVisor {
  SLdrTweakPlayer_ScanVisor();
  ~SLdrTweakPlayer_ScanVisor();

  float scanDistance; // 0xb0a32e5b
  bool scanRetention; // 0x2a75f2b8
  bool scanFreezesGame; // 0x058284bb
  bool scanLineOfSight; // 0x1e54f5ae
  float scanMaxTargetDistance; // 0xadfa90fc
  float scanMaxLockDistance; // 0xf4db84a9
  float scanCameraSpeed; // 0x8a7b245f
};

void LoadTypedefSLdrTweakPlayer_ScanVisor(SLdrTweakPlayer_ScanVisor& data, CInputStream& input);

struct SLdrTweakPlayer_Grapple {
  SLdrTweakPlayer_Grapple();
  ~SLdrTweakPlayer_Grapple();

  float grappleDistance; // 0xa726316b
  float grappleBeamLength; // 0x33e79b51
  float grappleSwingTime; // 0x9dd3e88b
  float grappleMaxVelocity; // 0xfb605ba4
  float grappleCameraSpeed; // 0xfe98b8e9
  float grapplePullCloseDistance; // 0x9210a25e
  float grapplePullDampenDistance; // 0xbe0c8b5e
  float grapplePullVelocity; // 0x2603a0be
  float grapplePullCameraSpeed; // 0x5b98a3bd
  float grappleTurnRate; // 0x87d4b5d6
  float grappleJumpForce; // 0xb7f82a9f
  float grappleReleaseTime; // 0x395478a8
  int grappleControlScheme; // 0x93c013c9
  bool grappleHoldOrbitButton; // 0x8eeed636
  bool grappleTurnControlsReversed; // 0xe1eb12e2
  SLdrTweakPlayer_GrappleBeam beam; // 0xae1fc47c
};

void LoadTypedefSLdrTweakPlayer_Grapple(SLdrTweakPlayer_Grapple& data, CInputStream& input);

struct SLdrTweakPlayer_Collision {
  SLdrTweakPlayer_Collision();
  ~SLdrTweakPlayer_Collision();

  float playerHeight; // 0xd0f345b2
  float playerRadius; // 0x6a884154
  float stepUpHeight; // 0xd9355674
  float stepDownHeight; // 0x88ea81db
  float ballRadius; // 0x0e2f537f
};

void LoadTypedefSLdrTweakPlayer_Collision(SLdrTweakPlayer_Collision& data, CInputStream& input);

struct SLdrTweakPlayer_FirstPersonCamera {
  SLdrTweakPlayer_FirstPersonCamera();
  ~SLdrTweakPlayer_FirstPersonCamera();

  float firstPersonCameraSpeed; // 0xba5eb7f5
  float cameraElevation; // 0x0d41e3ba
  float unknown_0xb400ebd6; // 0xb400ebd6
  float unknown_0xfd26b7b9; // 0xfd26b7b9
  float unknown_0x97b14dc6; // 0x97b14dc6
  float unknown_0xeb59925a; // 0xeb59925a
  float unknown_0xa1d73380; // 0xa1d73380
  float unknown_0xc8e8344a; // 0xc8e8344a
  float darkLightPitch; // 0xd40c480e
  CVector3f darkLightScale; // 0x7960c3a0
};

void LoadTypedefSLdrTweakPlayer_FirstPersonCamera(SLdrTweakPlayer_FirstPersonCamera& data, CInputStream& input);

struct SLdrTweakPlayer_Shield {
  SLdrTweakPlayer_Shield();
  ~SLdrTweakPlayer_Shield();

  float maxEnergy; // 0xd42fa1c1
  float usageRate; // 0x787855e6
  float rechargeRate; // 0x5dadd6ab
  bool allowsMotion; // 0x59efbb34
};

void LoadTypedefSLdrTweakPlayer_Shield(SLdrTweakPlayer_Shield& data, CInputStream& input);

struct SLdrTweakPlayer_Frozen {
  SLdrTweakPlayer_Frozen();
  ~SLdrTweakPlayer_Frozen();

  float frozenTimer; // 0xb3f20575
  int frozenJumpCounter; // 0xb851d54f
  float frozenDamageThreshold; // 0x33b040bf
};

void LoadTypedefSLdrTweakPlayer_Frozen(SLdrTweakPlayer_Frozen& data, CInputStream& input);

struct SLdrTweakPlayer_SuitDamageReduction {
  SLdrTweakPlayer_SuitDamageReduction();
  ~SLdrTweakPlayer_SuitDamageReduction();

  float varia; // 0xdf131ecd
  float dark; // 0x908a8e6c
  float light; // 0x95700a27
};

void LoadTypedefSLdrTweakPlayer_SuitDamageReduction(SLdrTweakPlayer_SuitDamageReduction& data, CInputStream& input);

struct SLdrTweakPlayer {
  SLdrTweakPlayer();
  ~SLdrTweakPlayer();

  rstl::string instanceName; // 0x7fda1466
  SLdrTweakPlayer_DarkWorld darkWorld; // 0xdfd08eba
  SLdrTweakPlayer_GrappleBeam grappleBeam; // 0x45171a96
  SLdrTweakPlayer_Motion motion; // 0x82cf4cf1
  SLdrTweakPlayer_Misc misc; // 0x56a720c8
  SLdrTweakPlayer_AimStuff aimStuff; // 0x42a17438
  SLdrTweakPlayer_Orbit orbit; // 0x243ae038
  SLdrTweakPlayer_ScanVisor scanVisor; // 0x20124c3d
  SLdrTweakPlayer_Grapple grapple; // 0x30412440
  SLdrTweakPlayer_Collision collision; // 0xc4d32ae5
  SLdrTweakPlayer_FirstPersonCamera firstPersonCamera; // 0xd6155d4b
  SLdrTweakPlayer_Shield shield; // 0xbcca767e
  SLdrTweakPlayer_Frozen frozen; // 0x4d3b20b7
  SLdrTweakPlayer_SuitDamageReduction suitDamageReduction; // 0xaeaff210
};

void LoadTypedefSLdrTweakPlayer(SLdrTweakPlayer& data, CInputStream& input);

#endif
