// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSURFACECAMERA_HPP
#define _SLDRSURFACECAMERA_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrSplineType.hpp"

struct SLdrSurfaceCamera {
  SLdrSurfaceCamera();
  ~SLdrSurfaceCamera();

  SLdrEditorProperties editorProperties; // 0x255a4580
  uint flagsSurfaceCamera; // 0x1ffc65d8
  int surfaceType; // 0x1405b5e4
  SLdrSpline spline; // 0x922d151f
  CVector3f playerOffset; // 0x1d8b933f
  SLdrSplineType playerSplineType; // 0x33e4685b
  bool playerSplineLoops; // 0x431769c6
  SLdrSplineType targetSplineType; // 0x5604d304
  bool targetSplineLoops; // 0x33b4f106
  SLdrSpline targetControlSpline; // 0xc4dfbfa7
  SLdrSpline fOVSpline; // 0x6868d4b3
};

void LoadTypedefSLdrSurfaceCamera(SLdrSurfaceCamera& data, CInputStream& input);

#endif
