// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTWEAKGAME_HPP
#define _SLDRTWEAKGAME_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "rstl/string.hpp"

struct SLdrTweakGame_FragLimitChoices {
  SLdrTweakGame_FragLimitChoices();
  ~SLdrTweakGame_FragLimitChoices();

  int fragLimit0; // 0xa2023ba8
  int fragLimit1; // 0x1abe5ccd
  int fragLimit2; // 0x080bf323
  int fragLimit3; // 0xb0b79446
  int fragLimit4; // 0x2d60acff
};

void LoadTypedefSLdrTweakGame_FragLimitChoices(SLdrTweakGame_FragLimitChoices& data, CInputStream& input);

struct SLdrTweakGame_TimeLimitChoices {
  SLdrTweakGame_TimeLimitChoices();
  ~SLdrTweakGame_TimeLimitChoices();

  float timeLimit0; // 0x779e8ff4
  float timeLimit1; // 0xbcc25c51
  float timeLimit2; // 0x3a562eff
  float timeLimit3; // 0xf10afd5a
  float timeLimit4; // 0xec0fcde2
};

void LoadTypedefSLdrTweakGame_TimeLimitChoices(SLdrTweakGame_TimeLimitChoices& data, CInputStream& input);

struct SLdrTweakGame_CoinLimitChoices {
  SLdrTweakGame_CoinLimitChoices();
  ~SLdrTweakGame_CoinLimitChoices();

  int coinLimit0; // 0x6b4cae26
  int coinLimit1; // 0xd3f0c943
  int coinLimit2; // 0xc14566ad
  int coinLimit3; // 0x79f901c8
  int coinLimit4; // 0xe42e3971
};

void LoadTypedefSLdrTweakGame_CoinLimitChoices(SLdrTweakGame_CoinLimitChoices& data, CInputStream& input);

struct SLdrTweakGame {
  SLdrTweakGame();
  ~SLdrTweakGame();

  rstl::string instanceName; // 0x7fda1466
  rstl::string pakFile; // 0x2bd13ab3
  rstl::string asset; // 0xf8be005a
  float fieldofView; // 0xfc93ceb8
  float fieldofView2Player; // 0x9fb2faa6
  bool disableDebugMenu; // 0xa9096914
  bool musicOnByDefault; // 0x7262d27b
  bool developmentMode; // 0xe943ba12
  float frontEndAudioVolume; // 0xa3dcf42a
  float unknown_0xb35c72be; // 0xb35c72be
  float unknown_0x4a02103c; // 0x4a02103c
  float unknown_0xe1fca71b; // 0xe1fca71b
  float unknown_0xfbce966a; // 0xfbce966a
  float unknown_0x09c6ca10; // 0x09c6ca10
  float hardModeDamageMultiplier; // 0x4dfcd432
  float hardModeWeaponMultiplier; // 0xae1831d9
  float safeZoneActivationTime; // 0x5ab5812c
  float safeZoneDeactivationTime; // 0x53401390
  int maxPercentageInventoryItems; // 0xd09f373b
  SLdrTweakGame_FragLimitChoices unknown_0x1d627808; // 0x1d627808
  SLdrTweakGame_TimeLimitChoices unknown_0xb2e8828d; // 0xb2e8828d
  SLdrTweakGame_CoinLimitChoices unknown_0x06af87bd; // 0x06af87bd
  SLdrTweakGame_TimeLimitChoices unknown_0x1533ea4e; // 0x1533ea4e
  SLdrSpline unknown_0x40818220; // 0x40818220
};

void LoadTypedefSLdrTweakGame(SLdrTweakGame& data, CInputStream& input);

#endif
