// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRKROCUSS_HPP
#define _SLDRKROCUSS_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrKrocuss {
  SLdrKrocuss();
  ~SLdrKrocuss();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int flavor; // 0xbe73724a
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  float waypointApproachDistance; // 0x733bd27c
  float visibleDistance; // 0xa72530e8
  float wallTurnSpeed; // 0xac47c628
  float floorTurnSpeed; // 0x8e4f7b29
  float downTurnSpeed; // 0x3d3c1b76
  float stickyReach; // 0xd5c25506
  float projectileBoundsMultiplier; // 0x742eab20
  float collisionLookAhead; // 0x80a81909
  float animSpeedScalar; // 0x8590483b
  bool initiallyPaused; // 0xc3cc437f
  float timeShellClosed; // 0xf04cadca
  float timeToOpenShell; // 0x497d54e8
  float timeShellOpen; // 0x3371c963
  float timeToCloseShell; // 0x22d37771
  float unknown_0xbbebed9e; // 0xbbebed9e
  SLdrDamageVulnerability shellClosedVulnerability; // 0x6bd144c8
  CColor wingLightColor; // 0x4d20624b
  CAssetId dPSC; // non-matching name, 0xc3566114
  int shellOpenSound; // 0x6a11338f
  int shellCloseSound; // 0xf64ca627
  float maxAudibleDistance; // 0x214e48a0
};

inline SLdrKrocuss::SLdrKrocuss() : editorProperties(), patterned(), actorInformation(), shellClosedVulnerability(), wingLightColor(CColor::Green()), dPSC(kInvalidAssetId) {
  flavor = 0;
  patterned.mass = 25.0f;
  patterned.speed = 3.0f;
  patterned.turnSpeed = 720.0f;
  patterned.detectionRange = 5.0f;
  patterned.detectionHeightRange = 5.0f;
  patterned.detectionAngle = 90.0f;
  patterned.minAttackRange = 4.0f;
  patterned.maxAttackRange = 20.0f;
  patterned.contactDamage.dI_WeaponType = 9;
  patterned.contactDamage.dI_Damage = 10.0f;
  patterned.contactDamage.dI_KnockBackPower = 5.0f;
  patterned.damageWaitTime = 3.0f;
  patterned.collisionRadius = 0.2f;
  patterned.collisionHeight = 5.0f;
  patterned.unknown_0xe287d8dd = 0.0f;
  waypointApproachDistance = 2.5f;
  visibleDistance = 2.5f;
  wallTurnSpeed = 360.0f;
  floorTurnSpeed = 180.0f;
  downTurnSpeed = 120.0f;
  stickyReach = 0.40000001f;
  projectileBoundsMultiplier = 1.0f;
  collisionLookAhead = 0.02f;
  animSpeedScalar = 1.0f;
  initiallyPaused = false;
  timeShellClosed = 1.0f;
  timeToOpenShell = 1.0f;
  timeShellOpen = 1.0f;
  timeToCloseShell = 1.0f;
  unknown_0xbbebed9e = 1.0f;
  wingLightColor = CColor(1.0f, 0.0f, 0.0f, 1.0f);
  shellOpenSound = 0;
  shellCloseSound = 0;
  maxAudibleDistance = 50.0f;
}

inline SLdrKrocuss::~SLdrKrocuss() {}

#endif
