// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRBALLTRIGGER_HPP
#define _SLDRBALLTRIGGER_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrTriggerInfo.hpp"

struct SLdrBallTrigger {
  SLdrBallTrigger();
  ~SLdrBallTrigger();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrTriggerInfo trigger; // 0x77a27411
  float attractionForce; // 0xb61b1149
  float attractionAngle; // 0x81af51d5
  float attractionDistance; // 0xbb38d077
  CVector3f attractionDirection; // 0xea511d83
  bool noBallMovement; // 0xb613f4e4
  float boundsSizeMultiplier; // 0x2766636a
};

inline SLdrBallTrigger::SLdrBallTrigger() : editorProperties(), trigger(), attractionDirection(CVector3f::Zero()) {
  editorProperties.transform.scale = CVector3f(2.0f, 2.0f, 2.0f);
  attractionForce = 20.0f;
  attractionAngle = 60.0f;
  attractionDistance = 20.0f;
  attractionDirection = CVector3f(1.0f, 0.0f, 0.0f);
  noBallMovement = false;
  boundsSizeMultiplier = 1.0f;
}

inline SLdrBallTrigger::~SLdrBallTrigger() {}

#endif
