// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTIMEKEYFRAME_HPP
#define _SLDRTIMEKEYFRAME_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrTimeKeyframe {
  SLdrTimeKeyframe();
  ~SLdrTimeKeyframe();

  SLdrEditorProperties editorProperties; // 0x255a4580
  float time; // 0x44335aff
};

void LoadTypedefSLdrTimeKeyframe(SLdrTimeKeyframe& data, CInputStream& input);

#endif
