// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSWAMPBOSSSTAGE1_HPP
#define _SLDRSWAMPBOSSSTAGE1_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAudioPlaybackParms.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrShockWaveInfo.hpp"

struct SLdrSwampBossStage1Sounds {
  SLdrSwampBossStage1Sounds();
  ~SLdrSwampBossStage1Sounds();

  SLdrAudioPlaybackParms tongueOut_OneShot; // 0x4f904909
  SLdrAudioPlaybackParms tongueRetract_Loop; // 0x82e108de
  SLdrAudioPlaybackParms tongueHitPlayer_OneShot; // 0xdf090545
  SLdrAudioPlaybackParms tonguePullPlayer_Loop; // 0x3dd5b3cf
  SLdrAudioPlaybackParms weakSpotHitSmall_OneShot; // 0xf82231bb
  SLdrAudioPlaybackParms weakSpotHitLarge_OneShot; // 0x009e3658
  SLdrAudioPlaybackParms painSound_OneShot; // 0x62bd75b1
  float painSoundDamageThreshold; // 0x7714baec
  SLdrAudioPlaybackParms telegraph_Loop; // 0x32969cba
  SLdrAudioPlaybackParms shockWaveVolumetric_Loop; // 0x597d2ac9
};

void LoadTypedefSLdrSwampBossStage1Sounds(SLdrSwampBossStage1Sounds& data, CInputStream& input);

struct SLdrSwampBossStage1Struct {
  SLdrSwampBossStage1Struct();
  ~SLdrSwampBossStage1Struct();

  float unknown_0x98106ee2; // 0x98106ee2
  float minTimeBetweenAttacks; // 0x95e7a2c2
  float maxTimeBetweenAttacks; // 0x76ba1c18
  int unknown_0xbb0ffdd6; // 0xbb0ffdd6
  int unknown_0x60b0ae31; // 0x60b0ae31
  int firstAttack; // 0x9cfa9acb
  int secondAttack; // 0x180f81dd
  int thirdAttack; // 0x42617cfd
  int fourthAttack; // 0xc39f864e
};

void LoadTypedefSLdrSwampBossStage1Struct(SLdrSwampBossStage1Struct& data, CInputStream& input);

struct SLdrSwampBossStage1Data {
  SLdrSwampBossStage1Data();
  ~SLdrSwampBossStage1Data();

  CAssetId darkWaterRingEffect; // 0x6cedf364
  float unknown_0x27a06f6a; // 0x27a06f6a
  float unknown_0x233a5e40; // 0x233a5e40
  CAssetId preJumpTelegraphEffect; // 0xef7c65ac
  SLdrShockWaveInfo splashShockWave; // 0x6c0f7aa3
  CAssetId tongueParticleEffect; // 0x762cd5b7
  CAssetId tongueParticleModel; // 0xd8ab76f0
  CAssetId tongueTipModel; // 0x145debea
  SLdrDamageInfo damageInfo; // 0xd0b0f21f
  CAssetId pART; // 0x0a078586
  float unknown_0x78755da3; // 0x78755da3
  float unknown_0x74e1a041; // 0x74e1a041
  float unknown_0x1f4e7c2c; // 0x1f4e7c2c
  float unknown_0xee6b6f47; // 0xee6b6f47
  float unknown_0x3ce96c9d; // 0x3ce96c9d
  SLdrDamageVulnerability weakSpotVulnerability; // 0x950318f0
  float weakSpotDamageMultiplier; // 0xba694941
  CAssetId spitProjectile; // 0xcfe37ebf
  SLdrDamageInfo spitDamage; // 0xda3c9b32
  CAssetId spitVisorEffect; // 0x008becab
  int sound_SpitVisor; // 0xf3af8417
  float spitProjectileRadius; // 0xdadc5bc9
  SLdrSwampBossStage1Sounds sounds; // 0xd402095f
  SLdrSwampBossStage1Struct swampBossStage1Struct; // 0x4500f774
  SLdrSwampBossStage1Struct swampBossStage1Struct_0x3e1e7597; // 0x3e1e7597
  SLdrSwampBossStage1Struct swampBossStage1Struct_0xa1c4f609; // 0xa1c4f609
};

void LoadTypedefSLdrSwampBossStage1Data(SLdrSwampBossStage1Data& data, CInputStream& input);

struct SLdrSwampBossStage1 {
  SLdrSwampBossStage1();
  ~SLdrSwampBossStage1();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrSwampBossStage1Data swampBossStage1Properties; // 0xb01a28d5
};

void LoadTypedefSLdrSwampBossStage1(SLdrSwampBossStage1& data, CInputStream& input);

#endif
