// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDREMPERORINGSTAGE3_HPP
#define _SLDREMPERORINGSTAGE3_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAudioPlaybackParms.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrBasicSwarmProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrHealthInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPlasmaBeamInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrShockWaveInfo.hpp"

struct SLdrEmperorIngStage3DarkBeamAttackData {
  SLdrEmperorIngStage3DarkBeamAttackData();
  ~SLdrEmperorIngStage3DarkBeamAttackData();

  SLdrPlasmaBeamInfo beamInfo; // 0x1598012a
  SLdrDamageInfo damage; // 0x337f9524
  int beamSound; // 0xf6f185d6
};

void LoadTypedefSLdrEmperorIngStage3DarkBeamAttackData(SLdrEmperorIngStage3DarkBeamAttackData& data, CInputStream& input);

struct SLdrEmperorIngStage3PortalAttackData {
  SLdrEmperorIngStage3PortalAttackData();
  ~SLdrEmperorIngStage3PortalAttackData();

  CAssetId effect; // 0xb68c6d96
  int portalOpenSound; // 0x1a66bed7
  SLdrDamageInfo projectileDamage; // 0x553b1339
  SLdrPlasmaBeamInfo beamInfo; // 0x1598012a
};

void LoadTypedefSLdrEmperorIngStage3PortalAttackData(SLdrEmperorIngStage3PortalAttackData& data, CInputStream& input);

struct SLdrEmperorIngStage3Action {
  SLdrEmperorIngStage3Action();
  ~SLdrEmperorIngStage3Action();

  bool enabled; // 0x29c77d27
  float chance; // 0x7a7b330e
  float modifier; // 0xed2d546f
};

void LoadTypedefSLdrEmperorIngStage3Action(SLdrEmperorIngStage3Action& data, CInputStream& input);

struct SLdrEmperorIngStage3Stage {
  SLdrEmperorIngStage3Stage();
  ~SLdrEmperorIngStage3Stage();

  float minHealthPercentage; // 0xdfea46b3
  float minTimeBetweenAttacks; // 0x95e7a2c2
  float maxTimeBetweenAttacks; // 0x76ba1c18
  SLdrEmperorIngStage3Action stampede; // 0x3826ec75
  SLdrEmperorIngStage3Action jumpSlide; // 0x93bf1106
  SLdrEmperorIngStage3Action lightSwarm; // 0xc4b88b80
  SLdrEmperorIngStage3Action darkBeam; // 0x32c6dc77
  SLdrEmperorIngStage3Action lightBeam; // 0xc6e7b293
  SLdrEmperorIngStage3Action portalAttack; // 0x20746b56
  SLdrEmperorIngStage3Action darkFlier; // 0x2ab44adb
  SLdrEmperorIngStage3Action jumpAttack; // 0xe2e78a78
};

void LoadTypedefSLdrEmperorIngStage3Stage(SLdrEmperorIngStage3Stage& data, CInputStream& input);

struct SLdrEmperorIngStage3Data {
  SLdrEmperorIngStage3Data();
  ~SLdrEmperorIngStage3Data();

  float tauntFrequency; // 0x293a0c19
  SLdrHealthInfo yellowHealth; // 0x8a3f760c
  SLdrHealthInfo health; // 0xcf90d15e
  float vulnerableTime; // 0x69bc5cd4
  float vulnerableDamageThreshold; // 0xb110e539
  SLdrDamageVulnerability redVulnerability; // 0x8d70d67a
  SLdrDamageVulnerability lightVulnerability; // 0x89c142f7
  SLdrDamageVulnerability darkVulnerability; // 0x8855c118
  SLdrDamageInfo meleeDamage; // 0xc9416034
  SLdrDamageInfo stampedeDamage; // 0x1440d152
  SLdrDamageInfo jumpSlideDamage; // 0xef582bd6
  SLdrDamageInfo groundPoundDamage; // 0x4738c321
  SLdrEmperorIngStage3DarkBeamAttackData darkBeamAttack; // 0x98e311c1
  SLdrEmperorIngStage3DarkBeamAttackData lightBeamAttack; // 0x93dae216
  CAssetId lightSwarmEffect; // 0x4f82b9e5
  SLdrBasicSwarmProperties lightSwarmProperties; // 0x043e9c2e
  SLdrAudioPlaybackParms lightSwarmDeathSound; // 0x91001508
  SLdrAudioPlaybackParms audioPlaybackParms; // 0x03552953
  SLdrEmperorIngStage3PortalAttackData portalAttack; // 0xaf7e3033
  SLdrShockWaveInfo jumpAttackShockWaveInfo; // 0xab4ed456
  int sound; // 0x985f72fd
  SLdrEmperorIngStage3Stage stage1; // 0xe843417f
  SLdrEmperorIngStage3Stage stage2; // 0xd13bec3f
  SLdrEmperorIngStage3Stage stage3; // 0xc61388ff
  SLdrEmperorIngStage3Stage stage4; // 0xa3cab6bf
};

void LoadTypedefSLdrEmperorIngStage3Data(SLdrEmperorIngStage3Data& data, CInputStream& input);

struct SLdrEmperorIngStage3 {
  SLdrEmperorIngStage3();
  ~SLdrEmperorIngStage3();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrEmperorIngStage3Data data; // 0x30de1a5b
};

void LoadTypedefSLdrEmperorIngStage3(SLdrEmperorIngStage3& data, CInputStream& input);

#endif
