// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCAMERAWAYPOINT_HPP
#define _SLDRCAMERAWAYPOINT_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrCameraWaypoint {
  SLdrCameraWaypoint();
  ~SLdrCameraWaypoint();

  SLdrEditorProperties editorProperties; // 0x255a4580
};

void LoadTypedefSLdrCameraWaypoint(SLdrCameraWaypoint& data, CInputStream& input);

#endif
