// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSTREAMEDAUDIO_HPP
#define _SLDRSTREAMEDAUDIO_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "rstl/string.hpp"

struct SLdrStreamedAudio {
  SLdrStreamedAudio();
  ~SLdrStreamedAudio();

  SLdrEditorProperties editorProperties; // 0x255a4580
  rstl::string songFile; // 0xf6f3de1c
  bool defaultAudio; // 0x34b152c4
  float fadeInTime; // 0x90aa341f
  float fadeOutTime; // 0x7c269ebc
  int volume; // 0x80c66c37
  int softwareChannel; // 0x28f82261
  bool softwareIsMusic; // 0xd3356fe7
};

void LoadTypedefSLdrStreamedAudio(SLdrStreamedAudio& data, CInputStream& input);

#endif
