// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTWEAKCAMERABOB_HPP
#define _SLDRTWEAKCAMERABOB_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "rstl/string.hpp"

struct SLdrTweakCameraBob {
  SLdrTweakCameraBob();
  ~SLdrTweakCameraBob();

  rstl::string instanceName; // 0x7fda1466
  float cameraBobExtentX; // 0xe2a0b6f1
  float cameraBobExtentY; // 0x29fc6554
  float cameraBobPeriod; // 0x149d7339
  float orbitBobScale; // 0xa27bb5a7
  float maxOrbitBobScale; // 0xe3580b2b
  float slowSpeedPeriodScale; // 0xb05dade7
  float targetMagnitudeTrackingRate; // 0x6dc5d440
  float landingBobSpringConstant; // 0xd16539a7
  float viewWanderRadius; // 0xadbb0a42
  float viewWanderSpeedMin; // 0xe7f8f11b
  float viewWanderSpeedMax; // 0x01985efa
  float viewWanderRollVariation; // 0xef19ba33
  float gunBobMagnitude; // 0x7f59be96
  float helmetBobMagnitude; // 0x38a82ac1
};

void LoadTypedefSLdrTweakCameraBob(SLdrTweakCameraBob& data, CInputStream& input);

#endif
