// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCAMERASHAKER_HPP
#define _SLDRCAMERASHAKER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrCameraShakerData.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrCameraShaker {
  SLdrCameraShaker();
  ~SLdrCameraShaker();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrCameraShakerData shakerData; // 0xad547f96
};

void LoadTypedefSLdrCameraShaker(SLdrCameraShaker& data, CInputStream& input);

#endif
