// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRAREADAMAGE_HPP
#define _SLDRAREADAMAGE_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrAreaDamage {
  SLdrAreaDamage();
  ~SLdrAreaDamage();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrDamageInfo damage; // 0x337f9524
  float pulseTime; // 0x8e07e9d3
  float graceTime; // 0xc052bc02
};

void LoadTypedefSLdrAreaDamage(SLdrAreaDamage& data, CInputStream& input);

#endif
