// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSNAKEWEEDSWARM_HPP
#define _SLDRSNAKEWEEDSWARM_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAnimationParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrSnakeWeedSwarm {
  SLdrSnakeWeedSwarm();
  ~SLdrSnakeWeedSwarm();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrAnimationParameters animationInformation; // 0xe25fb08c
  SLdrActorParameters actorInformation; // 0x7e397fed
  float density; // 0x64e5fe9f
  float maxDepth; // 0x23cef95f
  float locationVariance; // 0xbe02e456
  float detectionRadius; // 0x21cdcf21
  float grabRadius; // 0x89664723
  float waitTimeOut; // 0x723737bc
  float waitTimeOutVariance; // 0x57452dd9
  float retreatDepth; // 0x5c20b0c7
  float moveSpeed; // 0x6497c750
  float moveSpeedVariance; // 0x11f854e2
  float maxSlope; // 0xa755c1df
  float minSize; // 0x558c6dd7
  float maxSize; // 0xc5ff7d3d
  float heightOffset; // 0xb2ebc23a
  SLdrDamageInfo contactDamage; // 0xd756416e
  float damageWaitTime; // 0xe0cdc7e3
  int sound_Looped; // 0xcd7d996e
  int sound_IntoGround; // 0x1026db89
  int sound_OutofGround; // 0xcde17346
};

void LoadTypedefSLdrSnakeWeedSwarm(SLdrSnakeWeedSwarm& data, CInputStream& input);

#endif
