// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSCANNABLEOBJECTINFO_HPP
#define _SLDRSCANNABLEOBJECTINFO_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAnimationParameters.hpp"
#include "rstl/string.hpp"

struct SLdrScanSpeed {
  SLdrScanSpeed();
  ~SLdrScanSpeed();

  int value;
};

void LoadTypedefSLdrScanSpeed(SLdrScanSpeed& data, CInputStream& input);

struct SLdrScanInfoSecondaryModel {
  SLdrScanInfoSecondaryModel();
  ~SLdrScanInfoSecondaryModel();

  CAssetId secondaryStaticModel; // 0x1f7921bc
  SLdrAnimationParameters secondaryAnimatedModel; // 0xcdd202d1
  rstl::string secondaryModelLocator; // 0x3ea2bed8
};

void LoadTypedefSLdrScanInfoSecondaryModel(SLdrScanInfoSecondaryModel& data, CInputStream& input);

struct SLdrScannableObjectInfo {
  SLdrScannableObjectInfo();
  ~SLdrScannableObjectInfo();

  CAssetId scanInfoTextStringTable; // 0x2f5b6423
  SLdrScanSpeed unknown_0xc308a322; // 0xc308a322
  bool critical; // 0x7b714814
  bool unknown_0x1733b1ec; // 0x1733b1ec
  CAssetId scanTextureInHud; // 0x53336141
  float modelInitialPitch; // 0x3de0ba64
  float modelInitialYaw; // 0x2add6628
  float modelScale; // 0xd0c15066
  CAssetId staticModel; // 0xb7adc418
  SLdrAnimationParameters animatedModel; // 0x15694ee1
  SLdrAnimationParameters primarySecondAnimatedModel; // 0x58f9fe99
  SLdrScanInfoSecondaryModel secondaryModel0; // 0x1c5b4a3a
  SLdrScanInfoSecondaryModel secondaryModel1; // 0x8728a0ee
  SLdrScanInfoSecondaryModel secondaryModel2; // 0xf1cd99d3
  SLdrScanInfoSecondaryModel secondaryModel3; // 0x6abe7307
  SLdrScanInfoSecondaryModel secondaryModel4; // 0x1c07eba9
  SLdrScanInfoSecondaryModel secondaryModel5; // 0x8774017d
  SLdrScanInfoSecondaryModel secondaryModel6; // 0xf1913840
  SLdrScanInfoSecondaryModel secondaryModel7; // 0x6ae2d294
  SLdrScanInfoSecondaryModel secondaryModel8; // 0x1ce2091c
};

void LoadTypedefSLdrScannableObjectInfo(SLdrScannableObjectInfo& data, CInputStream& input);

#endif
