// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTIMER_HPP
#define _SLDRTIMER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrTimer {
  SLdrTimer();
  ~SLdrTimer();

  SLdrEditorProperties editorProperties; // 0x255a4580
  float time; // 0x44335aff
  float randomAdjust; // 0x3ad39b31
  bool autoReset; // 0x7bef45ca
  bool autoStart; // 0x3217dff8
};

void LoadTypedefSLdrTimer(SLdrTimer& data, CInputStream& input);

#endif
