// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRMETAREE_HPP
#define _SLDRMETAREE_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAudioPlaybackParms.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrMetaree {
  SLdrMetaree();
  ~SLdrMetaree();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrDamageInfo radiusDamage; // 0x086d58dd
  float dropHeight; // 0x38a5566f
  CVector3f collisionOffset0; // 0xa287077d
  float attackSpeed; // 0x6c0a2bc8
  float dropDelay; // 0x0097f282
  float haltDelay; // 0xe4e808c9
  float launchSpeed; // 0x31381a17
  SLdrAudioPlaybackParms turnSound; // 0xea11d1fa
};

inline SLdrMetaree::SLdrMetaree() : editorProperties(), patterned(), actorInformation(), radiusDamage(), collisionOffset0(CVector3f::Zero()), turnSound() {
  editorProperties.unknown_0x5d298a43 = 3;
  patterned.detectionRange = 10.0f;
  patterned.maxAttackRange = 30.0f;
  patterned.contactDamage.dI_WeaponType = 11;
  patterned.contactDamage.dI_Damage = 2.5f;
  patterned.contactDamage.dI_KnockBackPower = 4.0f;
  patterned.health.health = 2.0f;
  patterned.health.hI_KnockBackResistance = 2.0f;
  patterned.unknown_0xe287d8dd = 0.0f;
  patterned.echoParameters.isEchoEmitter = true;
  actorInformation.lighting.ambientColor = CColor(1.0f, 1.0f, 1.0f, 1.0f);
  actorInformation.visor.visorFlags = 0x0000000fu;
  radiusDamage.dI_WeaponType = 11;
  radiusDamage.dI_Damage = 5.0f;
  radiusDamage.dI_KnockBackPower = 5.0f;
  dropHeight = 3.0f;
  attackSpeed = 5.0f;
  dropDelay = 0.0f;
  haltDelay = 0.0f;
  launchSpeed = 0.0f;
}

inline SLdrMetaree::~SLdrMetaree() {}

#endif
