// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSTONETOAD_HPP
#define _SLDRSTONETOAD_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrStoneToad {
  SLdrStoneToad();
  ~SLdrStoneToad();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
};

void LoadTypedefSLdrStoneToad(SLdrStoneToad& data, CInputStream& input);

#endif
