// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTWEAKAUTOMAPPER_HPP
#define _SLDRTWEAKAUTOMAPPER_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "rstl/string.hpp"

struct SLdrTweakAutoMapper_Base {
  SLdrTweakAutoMapper_Base();
  ~SLdrTweakAutoMapper_Base();

  bool unknown_0xcbe595d8; // 0xcbe595d8
  bool unknown_0x8ecb53a6; // 0x8ecb53a6
  bool scaleMoveSpeedWithCameraDistance; // 0x30b13740
  float mapScreenCameraDefaultDistance; // 0x6bea9324
  float mapScreenCameraMinDistance; // 0x065dd754
  float mapScreenCameraMaxDistance; // 0x57a46c09
  float mapScreenCameraMinXAngle; // 0xb54255b5
  float mapScreenCameraMaxXAngle; // 0x0c64cec4
  float mapScreenCameraFOV; // 0x335ebc7e
  float mapScreenAreaOpacity; // 0x45be3f6b
  CColor mapScreenBGColor; // 0x533c5684
  float miniMapCameraDistance; // 0xeb383668
  float miniMapCameraAngle; // 0x27151ede
  float miniMapCameraFOV; // 0x434172c3
  float miniMapAreaOpacity; // 0x68097036
  CColor miniMapBGColor; // 0x03adcf46
  CColor mapVisitedSurfaceColor; // 0xd3fae283
  CColor mapVisitedOutlineColor; // 0x65d2cf45
  CColor mapUnvisitedSurfaceColor; // 0xb5752c08
  CColor mapUnvisitedOutlineColor; // 0x035d01ce
  CColor mapVisitedFocusAreaSurfaceColor; // 0x805d5fa3
  CColor mapVisitedFocusAreaOutlineColor; // 0x36757265
  CColor darkMapVisitedSurfaceColor; // 0xe550fcbd
  CColor darkMapVisitedOutlineColor; // 0x5378d17b
  CColor darkMapUnvisitedSurfaceColor; // 0x0ebf3cbc
  CColor darkMapUnvisitedOutlineColor; // 0xb897117a
  CColor darkMapVisitedFocusAreaSurfaceColor; // 0x3e670f6a
  CColor darkMapVisitedFocusAreaOutlineColor; // 0x884f22ac
  float mapLightColorIntensity; // 0x7bdb0edf
  float mapAmbientColorIntensity; // 0x12221909
  float offToMiniMapTime; // 0x38dbbc09
  float miniMapToMapScreenTime; // 0x30610062
  float mapScreenToMiniMapTime; // 0xb6acea88
  float unknown_0x73de4110; // 0x73de4110
  float mapScreenZoomSpeed; // 0x19069725
  float mapScreenCircleSpeed; // 0x5ba0de1e
  float mapScreenMoveSpeed; // 0x310b37a1
  CColor mapUnvisitedFocusAreaSurfaceColor; // 0xab82e268
  CColor mapUnvisitedFocusAreaOutlineColor; // 0x1daacfae
  CColor darkMapUnvisitedFocusAreaSurfaceColor; // 0xdad161a1
  CColor darkMapUnvisitedFocusAreaOutlineColor; // 0x6cf94c67
  float mapVisitedSurfaceAlphaMiniMap; // 0x47967404
  float mapVisitedSurfaceAlphaMapScreen; // 0x0ece1950
  float mapVisitedOutlineAlphaMiniMap; // 0x9ac1bdde
  float mapVisitedOutlineAlphaMapScreen; // 0x97a19386
  float mapUnvisitedSurfaceAlphaMiniMap; // 0xcb9e3a54
  float mapUnvisitedSurfaceAlphaMapScreen; // 0x2511a49b
  float mapUnvisitedOutlineAlphaMiniMap; // 0x16c9f38e
  float mapUnvisitedOutlineAlphaMapScreen; // 0xbc7e2e4d
  float mapDoorHalfHeight; // 0x15564d32
  float mapDoorHalfWidth; // 0xf5479260
  float mapDoorHalfDepth; // 0x271b644e
  float miniMapViewportPositionX; // 0x52dc08c1
  float miniMapViewportPositionY; // 0x9980db64
  float miniMapViewportWidth; // 0x23f59057
  float miniMapViewportHeight; // 0xad3d5a3f
  float unknown_0x3315d22b; // 0x3315d22b
  float miniMapWidgetHalfWidth; // 0x9e4007b6
  float miniMapWidgetHalfHeight; // 0x7a8d3d46
  bool unknown_0x2b97d64c; // 0x2b97d64c
  float unknown_0xbdc57ce0; // 0xbdc57ce0
  float unknown_0x7d59c854; // 0x7d59c854
  float unknown_0x3c4ef7d2; // 0x3c4ef7d2
  float mapScreenToMapUniverseTime; // 0x2b483e9f
  float unknown_0x706f52fe; // 0x706f52fe
  float unknown_0x62f9ebf6; // 0x62f9ebf6
  float unknown_0xa9a53853; // 0xa9a53853
  float mapScreenMove2DHoverDepth; // 0x722b1bc0
  CColor playerModelColor; // 0x4c3fc933
  CColor playerFlashedColor; // 0x5a87c156
  CColor playerSurfaceColor; // 0x9c0c5318
  CColor playerOutlineColor; // 0x2a247ede
  CColor textColor; // 0x44303a9c
  CColor textOutlineColor; // 0xf2e13506
  CColor unknown_0x1a4b8068; // 0x1a4b8068
  CColor frameColor; // 0xa485372c
  CColor titleColor; // 0x536647d5
  CColor legendBackgroundColor; // 0xa6b633fa
  CColor legendGradientColor; // 0x01cea7f9
};

void LoadTypedefSLdrTweakAutoMapper_Base(SLdrTweakAutoMapper_Base& data, CInputStream& input);

struct SLdrTweakAutoMapper_DoorColors {
  SLdrTweakAutoMapper_DoorColors();
  ~SLdrTweakAutoMapper_DoorColors();

  int numDoorColors; // 0x4fceb904
  CColor blueDoorColor; // 0xb36aa9b7
  CColor missileDoorColor; // 0x9620d4a0
  CColor darkBeamDoorColor; // 0x4e1a9a8d
  CColor darkBeamDoorOutlineColor; // 0xce986453
  CColor annihilatorBeamDoorColor; // 0x070f36f9
  CColor lightBeamDoorColor; // 0xfada14b6
  CColor superMissileDoorColor; // 0x172241dc
  CColor seekerDoorColor; // 0x518bccdc
  CColor powerBombDoorColor; // 0x2853fa91
  CColor greyDoorColor; // 0xe655a18e
  CColor whiteDoorColor; // 0x0f08f35e
};

void LoadTypedefSLdrTweakAutoMapper_DoorColors(SLdrTweakAutoMapper_DoorColors& data, CInputStream& input);

struct SLdrTweakAutoMapper {
  SLdrTweakAutoMapper();
  ~SLdrTweakAutoMapper();

  rstl::string instanceName; // 0x7fda1466
  SLdrTweakAutoMapper_Base base; // 0x18b2f423
  SLdrTweakAutoMapper_DoorColors doorColors; // 0xc5368863
};

void LoadTypedefSLdrTweakAutoMapper(SLdrTweakAutoMapper& data, CInputStream& input);

#endif
