// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCONDITIONALRELAY_HPP
#define _SLDRCONDITIONALRELAY_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPlayerItem.hpp"

struct SLdrConditionalTest {
  SLdrConditionalTest();
  ~SLdrConditionalTest();

  int boolean; // 0xde3e40a3
  SLdrPlayerItem playerItem; // 0xd3af8d72
  int amountOrCapacity; // 0x03bdea98
  int condition; // 0x70729364
  int value; // 0x8db9398a
};

void LoadTypedefSLdrConditionalTest(SLdrConditionalTest& data, CInputStream& input);

struct SLdrConditionalRelay {
  SLdrConditionalRelay();
  ~SLdrConditionalRelay();

  SLdrEditorProperties editorProperties; // 0x255a4580
  bool setToZeroOnAreaLoaded; // 0x44db8af2
  int multiplayerMaskandNegate; // 0x2cc54e77
  SLdrConditionalTest conditional1; // 0xcec16932
  SLdrConditionalTest conditional2; // 0xe709ddc0
  SLdrConditionalTest conditional3; // 0x49614c51
  SLdrConditionalTest conditional4; // 0xb498b424
};

void LoadTypedefSLdrConditionalRelay(SLdrConditionalRelay& data, CInputStream& input);

#endif
