// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRMETROIDALPHA_HPP
#define _SLDRMETROIDALPHA_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrIngPossessionData.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrMetroidAlpha {
  SLdrMetroidAlpha();
  ~SLdrMetroidAlpha();

  SLdrEditorProperties editorProperties;                  // 0x255a4580
  SLdrPatternedAITypedef patterned;                       // 0xb3774750
  SLdrActorParameters actorInformation;                   // 0x7e397fed
  SLdrDamageVulnerability frozenVulnerability;            // 0x411938aa
  SLdrDamageVulnerability energyDrainVulnerability;       // 0xd86ee93f
  SLdrDamageVulnerability babyMetroidGrowthVulnerability; // 0x39d63082
  float unknown_0x72439b39;                               // 0x72439b39
  float unknown_0x3af75fcc;                               // 0x3af75fcc
  float telegraphAttackTime;                              // 0xa97edc02
  float babyMetroidScale;                                 // 0x0d7e7e2c
  float unknown_0x03362858;                               // 0x03362858
  float unknown_0x852d3bb0;                               // 0x852d3bb0
  float unknown_0x1c783744;                               // 0x1c783744
  CAssetId babyMetroidTransformationParticleEffect;       // 0x71a21b50
  float stage2GrowthScale;                                // 0x2fe164c4
  float stage2GrowthEnergy;                               // 0x4c1f78f3
  float unknown_0x5f3f294c;                               // 0x5f3f294c
  float dodgeCheckTimeInterval;                           // 0x06b460f4
  float chanceToDodge;                                    // 0x23ca0676
  uint metroidFlagsMetroid;                               // 0xfa51d735
  SLdrIngPossessionData ingPossessionData;                // 0xe61748ed
};

inline SLdrMetroidAlpha::SLdrMetroidAlpha()
: editorProperties()
, patterned()
, actorInformation()
, frozenVulnerability()
, energyDrainVulnerability()
, babyMetroidGrowthVulnerability()
, babyMetroidTransformationParticleEffect(kInvalidAssetId)
, ingPossessionData() {
  patterned.turnSpeed = 180.0f;
  patterned.detectionRange = 60.0f;
  patterned.maxAttackRange = 10.0f;
  patterned.averageAttackTime = 6.0f;
  patterned.attackTimeVariation = 5.0f;
  patterned.contactDamage.dI_Damage = 5.0f;
  patterned.contactDamage.dI_KnockBackPower = 3.0f;
  patterned.health.health = 1.0f;
  patterned.health.hI_KnockBackResistance = 2.0f;
  patterned.creatureSize = 1;
  unknown_0x72439b39 = 5.0f;
  unknown_0x3af75fcc = 40.0f;
  telegraphAttackTime = 1.0f;
  babyMetroidScale = 0.5f;
  unknown_0x03362858 = 10.0f;
  unknown_0x852d3bb0 = 10.0f;
  unknown_0x1c783744 = 0.5f;
  stage2GrowthScale = 1.75f;
  stage2GrowthEnergy = 50.0f;
  unknown_0x5f3f294c = 100.0f;
  dodgeCheckTimeInterval = 5.0f;
  chanceToDodge = 0.5f;
  metroidFlagsMetroid = 0x00000000u;
}

inline SLdrMetroidAlpha::~SLdrMetroidAlpha() {}

#endif
