// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRRELAY_HPP
#define _SLDRRELAY_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrRelay {
  SLdrRelay();
  ~SLdrRelay();

  SLdrEditorProperties editorProperties; // 0x255a4580
  bool oneShot;                          // 0xead7b7bb
};

inline SLdrRelay::SLdrRelay() : editorProperties() { oneShot = false; }

inline SLdrRelay::~SLdrRelay() {}

#endif
