// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSCRIPTLAYERCONTROLLER_HPP
#define _SLDRSCRIPTLAYERCONTROLLER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrMasterLayer {
  SLdrMasterLayer();
  ~SLdrMasterLayer();

  int areaID; // 0x00000000
  int layer; // 0x00000001
};

void LoadTypedefSLdrMasterLayer(SLdrMasterLayer& data, CInputStream& input);

struct SLdrScriptLayerController {
  SLdrScriptLayerController();
  ~SLdrScriptLayerController();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrMasterLayer masterLayer; // 0x8249f6c7
  bool isDynamic; // 0x12a7d8b2
};

void LoadTypedefSLdrScriptLayerController(SLdrScriptLayerController& data, CInputStream& input);

#endif
