// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRING_HPP
#define _SLDRING_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPlasmaBeamInfo.hpp"

struct SLdrIng {
  SLdrIng();
  ~SLdrIng();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  uint ingFlagsIng; // 0x092fbad0
  CAssetId facePlateModel; // 0xbdcce71b
  float hearingRadius; // 0xed69488f
  float ingSpotMaxSpeed; // 0x95b47cf9
  float ingSpotMaxWallSpeed; // 0x8d42a8d5
  float ingSpotBallPursuitSpeed; // 0x84586bfd
  float unknown_0x50398a06; // 0x50398a06
  float ingSpotTurnSpeed; // 0xeaa3c3f8
  CAssetId ingSpotBlobEffect; // 0xcc5a4918
  CAssetId ingSpotHitNormalDamage; // 0x8851dc01
  CAssetId ingSpotHitHeavyDamage; // 0x5d01100f
  CAssetId ingSpotDeath; // 0x9a56892e
  int sound_IngSpotIdle; // 0x4cab30a9
  int sound_IngSpotMove; // 0x8f83be73
  int sound_HitNormalDamage; // 0xb392943a
  int sound_HitHeavyDamage; // 0x24ecc1e9
  int sound_IngSpotDeath; // 0x4489935e
  CAssetId pART; // non-matching name, 0x3c2d681e
  CAssetId sRSC; // non-matching name, 0xd576f379
  CAssetId pART_0x3da219c7; // non-matching name, 0x3da219c7
  float unknown_0x23271976; // 0x23271976
  CAssetId pART_0x081e9e6c; // non-matching name, 0x081e9e6c
  float unknown_0xcb39eccb; // 0xcb39eccb
  float unknown_0x587ca175; // 0x587ca175
  float unknown_0x0bd7d5a9; // 0x0bd7d5a9
  int sound_SwarmMove; // 0xe8ea5bc8
  int sound_InsideHost; // 0x5650366a
  int sound_ExitHost; // 0xb09af706
  int sound_ExitHostSafeZone; // 0x0c13c5a8
  int sound; // non-matching name, 0x148b81e4
  float unknown_0x5d0d2c40; // 0x5d0d2c40
  float unknown_0xc620183a; // 0xc620183a
  float frustrationTime; // 0x7d19c3ca
  float tauntChance; // 0xa77f6212
  float aggressiveness; // 0x9579b1f2
  SLdrDamageInfo armSwipeDamage; // 0x915da374
  SLdrDamageInfo bodyProjectileContactDamage; // 0xab258f6b
  float unknown_0xa0d63374; // 0xa0d63374
  float bodyProjectileSuckTime; // 0xdfea60a2
  CAssetId bodyProjectileSplatEffect; // 0x601cc5b4
  float bodyProjectileSpeed; // 0xce980820
  float bodyProjectileDropTime; // 0xb752c177
  float bodyProjectileMinAttackDist; // 0xe6ddb662
  float bodyProjectileMaxAttackDist; // 0xb57bae86
  int sound_BodyProjectile; // 0x2025858b
  int sound_BodyProjectileSplatWall; // 0x19f8fee6
  float bodyProjectileOdds; // 0xdc741fbd
  float miniPortalMinAttackDist; // 0xfa6edeb5
  float miniPortalMaxAttackDist; // 0xa9c8c651
  CAssetId miniPortalEffect; // 0xa926f8a8
  int sound_MiniPortal; // 0x4051fd1a
  SLdrDamageInfo miniPortalProjectileDamage; // 0x424a6d37
  SLdrPlasmaBeamInfo miniPortalBeamInfo; // 0x9c170968
  float unknown_0x67f6c10e; // 0x67f6c10e
  SLdrDamageInfo exitGrappleDamage; // 0x11c36d8e
  float exitGrappleSpitForce; // 0xc2320b06
  int sound_Grapple; // 0x4832703b
  int sound_ExitGrapple; // 0x36b0e542
  float maxGrappleBallHoldTime; // 0x421651f6
  float grappleBallPursuitRange; // 0x560b4a95
  float postGrappleBallWaitTime; // 0x8bdcc614
  CColor lightColor; // 0xbd3efe7d
  float lightAttenuation; // 0xd24b888f
  SLdrDamageVulnerability ingSpotVulnerability; // 0x1b96ff8b
  SLdrDamageVulnerability grappleBallVulnerability; // 0x33737ea6
  SLdrDamageVulnerability triggerVulnerability; // 0x23399d21
};

inline SLdrIng::SLdrIng() : editorProperties(), patterned(), actorInformation(), facePlateModel(kInvalidAssetId), ingSpotBlobEffect(kInvalidAssetId), ingSpotHitNormalDamage(kInvalidAssetId), ingSpotHitHeavyDamage(kInvalidAssetId), ingSpotDeath(kInvalidAssetId), pART(kInvalidAssetId), sRSC(kInvalidAssetId), pART_0x3da219c7(kInvalidAssetId), pART_0x081e9e6c(kInvalidAssetId), armSwipeDamage(), bodyProjectileContactDamage(), bodyProjectileSplatEffect(kInvalidAssetId), miniPortalEffect(kInvalidAssetId), miniPortalProjectileDamage(), miniPortalBeamInfo(), exitGrappleDamage(), lightColor(CColor::Green()), ingSpotVulnerability(), grappleBallVulnerability(), triggerVulnerability() {
  patterned.turnSpeed = 360.0f;
  patterned.minAttackRange = 0.0f;
  patterned.health.health = 150.0f;
  patterned.health.hI_KnockBackResistance = 2.0f;
  patterned.creatureSize = 1;
  ingFlagsIng = 0x00000000u;
  hearingRadius = 50.0f;
  ingSpotMaxSpeed = 15.0f;
  ingSpotMaxWallSpeed = 7.0f;
  ingSpotBallPursuitSpeed = 25.0f;
  unknown_0x50398a06 = 25.0f;
  ingSpotTurnSpeed = 360.0f;
  sound_IngSpotIdle = 0;
  sound_IngSpotMove = 0;
  sound_HitNormalDamage = 0;
  sound_HitHeavyDamage = 0;
  sound_IngSpotDeath = 0;
  unknown_0x23271976 = 0.34999999f;
  unknown_0xcb39eccb = 15.0f;
  unknown_0x587ca175 = 1.5f;
  unknown_0x0bd7d5a9 = 1.5f;
  sound_SwarmMove = 0;
  sound_InsideHost = 0;
  sound_ExitHost = 0;
  sound_ExitHostSafeZone = 0;
  sound = 0;
  unknown_0x5d0d2c40 = 15.0f;
  unknown_0xc620183a = 1.5f;
  frustrationTime = 2.0f;
  tauntChance = 25.0f;
  aggressiveness = 10.0f;
  armSwipeDamage.unknown_0x119fbd31 = 11;
  armSwipeDamage.dI_Damage = 20.0f;
  armSwipeDamage.dI_KnockBackPower = 10.0f;
  bodyProjectileContactDamage.unknown_0x119fbd31 = 11;
  bodyProjectileContactDamage.dI_Damage = 20.0f;
  bodyProjectileContactDamage.dI_KnockBackPower = 5.0f;
  unknown_0xa0d63374 = 20.0f;
  bodyProjectileSuckTime = 5.0f;
  bodyProjectileSpeed = 25.0f;
  bodyProjectileDropTime = 2.0f;
  bodyProjectileMinAttackDist = 20.0f;
  bodyProjectileMaxAttackDist = 40.0f;
  sound_BodyProjectile = 0;
  sound_BodyProjectileSplatWall = 0;
  bodyProjectileOdds = 70.0f;
  miniPortalMinAttackDist = 40.0f;
  miniPortalMaxAttackDist = 100.0f;
  sound_MiniPortal = 0;
  miniPortalProjectileDamage.unknown_0x119fbd31 = 11;
  miniPortalProjectileDamage.dI_Damage = 20.0f;
  miniPortalProjectileDamage.dI_KnockBackPower = 10.0f;
  miniPortalBeamInfo.length = 500.0f;
  miniPortalBeamInfo.expansionSpeed = 4.0f;
  miniPortalBeamInfo.lifeTime = 1.0f;
  miniPortalBeamInfo.pulseSpeed = 20.0f;
  miniPortalBeamInfo.shutdownTime = 0.25f;
  miniPortalBeamInfo.pulseEffectScale = 2.0f;
  miniPortalBeamInfo.innerColor = CColor(0.49803901f, 0.49803901f, 0.49803901f, 0.49803901f);
  miniPortalBeamInfo.outerColor = CColor(0.60000002f, 0.60000002f, 0.0f, 0.49803901f);
  unknown_0x67f6c10e = 30.0f;
  exitGrappleDamage.unknown_0x119fbd31 = 11;
  exitGrappleDamage.dI_Damage = 10.0f;
  exitGrappleDamage.dI_KnockBackPower = 1.0f;
  exitGrappleSpitForce = 30.0f;
  sound_Grapple = 0;
  sound_ExitGrapple = 0;
  maxGrappleBallHoldTime = 10.0f;
  grappleBallPursuitRange = 20.0f;
  postGrappleBallWaitTime = 10.0f;
  lightColor = CColor(1.0f, 1.0f, 1.0f, 1.0f);
  lightAttenuation = 5.0f;
}

inline SLdrIng::~SLdrIng() {}

#endif
