// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCOMMANDOPIRATE_HPP
#define _SLDRCOMMANDOPIRATE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrIngPossessionData.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrUnknownStruct10 {
  SLdrUnknownStruct10();
  ~SLdrUnknownStruct10();

  float grenadeMinAttackInterval; // 0x74479b13
  float grenadePostAttackPause; // 0xb7994ea1
  float grenadeAttackChance; // 0x9a86ec4d
  float grenadeMinAttackDist; // 0x25f822c4
  float grenadeMaxAttackDist; // 0x765e3a20
  SLdrDamageInfo grenadeDamage; // 0x14d1a3a8
  CAssetId grenadeExplosion; // 0x1319e077
  CAssetId grenadeEffect; // 0xd207ff0f
  CAssetId grenadeTrail; // 0x2b31c882
  float grenadeMass; // 0x9a6bb47f
  float unknown_0xed086ce0; // 0xed086ce0
  float grenadeMinLaunchSpeed; // 0x00fc6646
  float grenadeMaxLaunchSpeed; // 0xa7c8e63f
  int unknown_0x454f16b1; // 0x454f16b1
  float eMPDuration; // 0x2d4706e8
  int sound_GrenadeBounce; // 0x258c3e1b
  int sound_GrenadeExplode; // 0xaf6aad88
};

void LoadTypedefSLdrUnknownStruct10(SLdrUnknownStruct10& data, CInputStream& input);

struct SLdrCommandoShield {
  SLdrCommandoShield();
  ~SLdrCommandoShield();

  SLdrDamageInfo shieldChargeDamage; // 0x4da4a894
  SLdrDamageVulnerability shieldVulnerability; // 0xd34f1323
  float shieldChargeMinAttackDist; // 0xc1d9dbc6
  float shieldChargeMaxAttackDist; // 0x927fc322
  float shieldChargeSpeed; // 0x717824b4
  CAssetId shieldExplodeEffect; // 0xa41f75ef
  int sound_ShieldExplode; // 0xe6e92e73
  float unknown_0x6cb0da5a; // 0x6cb0da5a
  float unknown_0xc3938663; // 0xc3938663
  float armShieldChance; // 0x865c109c
  float armShieldTime; // 0x8b48a2f8
  float armShieldTimeVariation; // 0xe1b0efa0
  CAssetId armShieldExplodeEffect; // 0x5ca206ca
  CAssetId shieldChargeEffect; // 0xebf69cf0
  CAssetId armShieldEffect; // 0x4aab4e04
  int sound_ShieldTurnOn; // 0xbf3c59b6
  int sound_ShieldTurnOff; // 0x78be3b8d
};

void LoadTypedefSLdrCommandoShield(SLdrCommandoShield& data, CInputStream& input);

struct SLdrCommandoPirate {
  SLdrCommandoPirate();
  ~SLdrCommandoPirate();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrIngPossessionData ingPossessionData; // 0xe61748ed
  int sound; // 0x7abed4ce
  float aggressiveness; // 0x9579b1f2
  float coverCheck; // 0xf89ab419
  float searchRadius; // 0xed9bf5a3
  float dodgeCheck; // 0xdc36e745
  int sound_Impact; // 0x1bb16ea5
  int sound_Hurled; // 0x3bb37a8f
  int sound_Death; // 0xe160b593
  int alwaysFF; // 0xfca76593
  int alwaysFF_0x467c3d94; // 0x467c3d94
  SLdrDamageInfo bladeDamage; // 0xa5912430
  CAssetId projectile; // 0xef485db9
  SLdrDamageInfo projectileDamage; // 0x553b1339
  int sound_Projectile; // 0xeac27605
  float hearingRadius; // 0xed69488f
  SLdrUnknownStruct10 unknown_0xfb435257; // 0xfb435257
  SLdrCommandoShield shieldInfo; // 0x388e16c9
  float intraBurstShotTime; // 0x71587b45
  float intraBurstShotVariation; // 0x7903312e
};

void LoadTypedefSLdrCommandoPirate(SLdrCommandoPirate& data, CInputStream& input);

#endif
