// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRINGPUDDLE_HPP
#define _SLDRINGPUDDLE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrHealthInfo.hpp"

struct SLdrIngPuddleData {
  SLdrIngPuddleData();
  ~SLdrIngPuddleData();

  CAssetId stateMachine;                 // 0x55744160
  SLdrHealthInfo health;                 // 0xcf90d15e
  float puddleSpeed;                     // 0xc6c16427
  CAssetId blobEffect;                   // 0x2367f689
  CAssetId puddleHitNormalDamage;        // 0xe8a6e174
  CAssetId puddleHitHeavyDamage;         // 0x1ab2b090
  CAssetId puddleDeath;                  // 0x1ccfa4ba
  int sound_IngSpotIdle;                 // 0x4cab30a9
  int sound_IngSpotMove;                 // 0x8f83be73
  int sound_HitNormalDamage;             // 0xb392943a
  int sound_HitHeavyDamage;              // 0x24ecc1e9
  int sound_IngSpotDeath;                // 0x4489935e
  SLdrDamageVulnerability vulnerability; // 0x7b71ae90
};

inline SLdrIngPuddleData::SLdrIngPuddleData()
: stateMachine(kInvalidAssetId)
, health()
, blobEffect(kInvalidAssetId)
, puddleHitNormalDamage(kInvalidAssetId)
, puddleHitHeavyDamage(kInvalidAssetId)
, puddleDeath(kInvalidAssetId)
, vulnerability() {
  health.hI_KnockBackResistance = 2.0f;
  puddleSpeed = 20.0f;
  sound_IngSpotIdle = 0;
  sound_IngSpotMove = 0;
  sound_HitNormalDamage = 0;
  sound_HitHeavyDamage = 0;
  sound_IngSpotDeath = 0;
}

inline SLdrIngPuddleData::~SLdrIngPuddleData() {}

inline void LoadTypedefIngPuddleData(SLdrIngPuddleData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x55744160: {
      sldrThis.stateMachine = CAssetId(input.ReadInt32());
      break;
    }
    case 0xcf90d15e: {
      LoadTypedefHealthInfo(sldrThis.health, input);
      break;
    }
    case 0xc6c16427: {
      sldrThis.puddleSpeed = input.ReadFloat();
      break;
    }
    case 0x2367f689: {
      sldrThis.blobEffect = CAssetId(input.ReadInt32());
      break;
    }
    case 0xe8a6e174: {
      sldrThis.puddleHitNormalDamage = CAssetId(input.ReadInt32());
      break;
    }
    case 0x1ab2b090: {
      sldrThis.puddleHitHeavyDamage = CAssetId(input.ReadInt32());
      break;
    }
    case 0x1ccfa4ba: {
      sldrThis.puddleDeath = CAssetId(input.ReadInt32());
      break;
    }
    case 0x4cab30a9: {
      sldrThis.sound_IngSpotIdle = input.ReadInt32();
      break;
    }
    case 0x8f83be73: {
      sldrThis.sound_IngSpotMove = input.ReadInt32();
      break;
    }
    case 0xb392943a: {
      sldrThis.sound_HitNormalDamage = input.ReadInt32();
      break;
    }
    case 0x24ecc1e9: {
      sldrThis.sound_HitHeavyDamage = input.ReadInt32();
      break;
    }
    case 0x4489935e: {
      sldrThis.sound_IngSpotDeath = input.ReadInt32();
      break;
    }
    case 0x7b71ae90: {
      LoadTypedefDamageVulnerability(sldrThis.vulnerability, input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrIngPuddle {
  SLdrIngPuddle();
  ~SLdrIngPuddle();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrActorParameters actorInformation;  // 0x7e397fed
  SLdrIngPuddleData ingPuddleProperties; // 0xd520975d
};

inline SLdrIngPuddle::SLdrIngPuddle()
: editorProperties(), actorInformation(), ingPuddleProperties() {}

inline SLdrIngPuddle::~SLdrIngPuddle() {}

#endif
