// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRFORGOTTENOBJECT_HPP
#define _SLDRFORGOTTENOBJECT_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrForgottenObject {
  SLdrForgottenObject();
  ~SLdrForgottenObject();

  SLdrEditorProperties editorProperties; // 0x255a4580
};

void LoadTypedefSLdrForgottenObject(SLdrForgottenObject& data, CInputStream& input);

#endif
