// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRGUIMENU_HPP
#define _SLDRGUIMENU_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrGuiWidgetProperties.hpp"

struct SLdrGuiMenu {
  SLdrGuiMenu();
  ~SLdrGuiMenu();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrGuiWidgetProperties widgetProperties; // 0x91cefa1e
  int controlDirection; // 0xa714d574
  bool wrapSelection; // 0x84f708c8
  int selectionChangedSound; // 0xbe50269e
};

void LoadTypedefSLdrGuiMenu(SLdrGuiMenu& data, CInputStream& input);

#endif
