// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSCANTREEINVENTORY_HPP
#define _SLDRSCANTREEINVENTORY_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrScannableParameters.hpp"
#include "rstl/string.hpp"

struct SLdrInventorySlot {
  SLdrInventorySlot();
  ~SLdrInventorySlot();

  int value;
};

void LoadTypedefSLdrInventorySlot(SLdrInventorySlot& data, CInputStream& input);

struct SLdrScanTreeInventory {
  SLdrScanTreeInventory();
  ~SLdrScanTreeInventory();

  SLdrEditorProperties editorProperties; // 0x255a4580
  CAssetId nodeName; // 0x46219bac
  rstl::string stringName; // 0x32698bd6
  SLdrInventorySlot unknown_0x3d326f90; // 0x3d326f90
  SLdrScannableParameters scannableInfo; // 0x2da1ec33
};

void LoadTypedefSLdrScanTreeInventory(SLdrScanTreeInventory& data, CInputStream& input);

#endif
