// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSPANKWEED_HPP
#define _SLDRSPANKWEED_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrSpankWeed {
  SLdrSpankWeed();
  ~SLdrSpankWeed();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  bool unknown_0x5cdc877d; // 0x5cdc877d
  float wakeUpRadius; // 0x835adca1
  float searchRadius; // 0xed9bf5a3
  float attackRadius; // 0x7c11b995
  float hurtSleepDelay; // 0x9b5a4744
};

inline SLdrSpankWeed::SLdrSpankWeed() : editorProperties(), patterned(), actorInformation() {
  patterned.contactDamage.dI_WeaponType = 9;
  patterned.contactDamage.dI_Damage = 20.0f;
  patterned.contactDamage.dI_KnockBackPower = 1.0f;
  patterned.damageWaitTime = 1.0f;
  patterned.health.health = 1000000.0f;
  patterned.health.hI_KnockBackResistance = 2.0f;
  unknown_0x5cdc877d = true;
  wakeUpRadius = 60.0f;
  searchRadius = 30.0f;
  attackRadius = 15.0f;
  hurtSleepDelay = 5.0f;
}

inline SLdrSpankWeed::~SLdrSpankWeed() {}

#endif
