// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSCRIPTLAYERCONTROLLER_HPP
#define _SLDRSCRIPTLAYERCONTROLLER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrMasterLayer {
  SLdrMasterLayer();
  ~SLdrMasterLayer();

  int areaID;
  int layer;
};

inline SLdrMasterLayer::SLdrMasterLayer() : areaID(-1) {}

inline SLdrMasterLayer::~SLdrMasterLayer() {}

void LoadTypedefMasterLayer(SLdrMasterLayer& sldrThis, CInputStream& input);

struct SLdrScriptLayerController {
  SLdrScriptLayerController();
  ~SLdrScriptLayerController();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrMasterLayer masterLayer;           // 0x8249f6c7
  bool isDynamic;                        // 0x12a7d8b2
};

inline SLdrScriptLayerController::SLdrScriptLayerController() : editorProperties(), masterLayer() {
  isDynamic = false;
}

inline SLdrScriptLayerController::~SLdrScriptLayerController() {}

#endif
