// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRGUISCREEN_HPP
#define _SLDRGUISCREEN_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrGuiScreen {
  SLdrGuiScreen();
  ~SLdrGuiScreen();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int whichScreen; // 0xd3b7e6d8
  CAssetId stringTable; // 0xfd95ed2a
};

void LoadTypedefSLdrGuiScreen(SLdrGuiScreen& data, CInputStream& input);

#endif
