// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRPARASITE_HPP
#define _SLDRPARASITE_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrParasite {
  SLdrParasite();
  ~SLdrParasite();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int flavor;                            // 0xbe73724a
  SLdrPatternedAITypedef patterned;      // 0xb3774750
  SLdrActorParameters actorInformation;  // 0x7e397fed
  float telegraphDistance;               // 0x8458b003
  float waypointApproachDistance;        // 0x733bd27c
  float wallTurnSpeed;                   // 0xac47c628
  float floorTurnSpeed;                  // 0x8e4f7b29
  float downTurnSpeed;                   // 0x3d3c1b76
  float stuckTime;                       // 0x0e7e3698
  float stickyReach;                     // 0xd5c25506
  float behaviorInfluenceRadius;         // 0x280361aa
  float separationDistance;              // 0x01559f27
  float separationPriority;              // 0xd293ebc4
  float alignmentPriority;               // 0x4841f1de
  float cohesionPriority;                // 0x61959f0d
  float pathFollowingPriority;           // 0xae11f975
  float forwardMovingPriority;           // 0x5e6a54b8
  float playerAvoidanceDistance;         // 0x956a1248
  float playerAvoidancePriority;         // 0x46ac66ab
  float parasiteVisibleDistance;         // 0x4eeec785
  bool initiallyPaused;                  // 0xc3cc437f
};

inline SLdrParasite::SLdrParasite() : editorProperties(), patterned(), actorInformation() {
  flavor = 0;
  patterned.mass = 25.0f;
  patterned.speed = 3.0f;
  patterned.turnSpeed = 720.0f;
  patterned.detectionRange = 5.0f;
  patterned.detectionHeightRange = 5.0f;
  patterned.detectionAngle = 90.0f;
  patterned.minAttackRange = 4.0f;
  patterned.maxAttackRange = 20.0f;
  patterned.contactDamage.dI_WeaponType = 9;
  patterned.contactDamage.dI_Damage = 10.0f;
  patterned.contactDamage.dI_KnockBackPower = 5.0f;
  patterned.damageWaitTime = 3.0f;
  patterned.collisionRadius = 0.2f;
  patterned.collisionHeight = 5.0f;
  patterned.unknown_0xe287d8dd = 0.0f;
  telegraphDistance = 10.0f;
  waypointApproachDistance = 2.5f;
  wallTurnSpeed = 360.0f;
  floorTurnSpeed = 180.0f;
  downTurnSpeed = 120.0f;
  stuckTime = 0.2f;
  stickyReach = 0.40000001f;
  behaviorInfluenceRadius = 6.0f;
  separationDistance = 2.5999999f;
  separationPriority = 1.0f;
  alignmentPriority = 0.80000001f;
  cohesionPriority = 0.69999999f;
  pathFollowingPriority = 0.89999998f;
  forwardMovingPriority = 0.2f;
  playerAvoidanceDistance = 1.3f;
  playerAvoidancePriority = 0.2f;
  parasiteVisibleDistance = 40.0f;
  initiallyPaused = false;
}

inline SLdrParasite::~SLdrParasite() {}

#endif
