// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRINGPUDDLE_HPP
#define _SLDRINGPUDDLE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrHealthInfo.hpp"

struct SLdrIngPuddleData {
  SLdrIngPuddleData();
  ~SLdrIngPuddleData();

  CAssetId stateMachine; // 0x55744160
  SLdrHealthInfo health; // 0xcf90d15e
  float puddleSpeed; // 0xc6c16427
  CAssetId blobEffect; // 0x2367f689
  CAssetId puddleHitNormalDamage; // 0xe8a6e174
  CAssetId puddleHitHeavyDamage; // 0x1ab2b090
  CAssetId puddleDeath; // 0x1ccfa4ba
  int sound_IngSpotIdle; // 0x4cab30a9
  int sound_IngSpotMove; // 0x8f83be73
  int sound_HitNormalDamage; // 0xb392943a
  int sound_HitHeavyDamage; // 0x24ecc1e9
  int sound_IngSpotDeath; // 0x4489935e
  SLdrDamageVulnerability vulnerability; // 0x7b71ae90
};

void LoadTypedefSLdrIngPuddleData(SLdrIngPuddleData& data, CInputStream& input);

struct SLdrIngPuddle {
  SLdrIngPuddle();
  ~SLdrIngPuddle();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrIngPuddleData ingPuddleProperties; // 0xd520975d
};

void LoadTypedefSLdrIngPuddle(SLdrIngPuddle& data, CInputStream& input);

#endif
