// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCOUNTER_HPP
#define _SLDRCOUNTER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrCounter {
  SLdrCounter();
  ~SLdrCounter();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int initial_Count; // 0xfd179a6f
  int max_Count; // 0x5b851589
  bool autoReset; // 0x7bef45ca
  bool wrap; // 0xf076cef5
};

void LoadTypedefSLdrCounter(SLdrCounter& data, CInputStream& input);

#endif
