// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRROOMACOUSTICS_HPP
#define _SLDRROOMACOUSTICS_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrRoomAcoustics {
  SLdrRoomAcoustics();
  ~SLdrRoomAcoustics();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int roomVolume; // 0xbd9ea266
  int priority; // 0x86cf23f4
  bool reverbHiEnabled; // 0xa00360cc
  bool unknown_0x3263c26e; // 0x3263c26e
  float reverbHiTime; // 0xc5868061
  float reverbHiPreDelay; // 0xc6f50032
  float reverbHiDamping; // 0xcba5555d
  float reverbHiColoration; // 0x7319cf50
  float reverbHiCrossTalk; // 0x3dc3f16f
  float reverbHiMix; // 0xd5518b6c
  bool chorusEnabled; // 0x26997ccb
  float chorusBaseDelay; // 0x121bdfad
  float chorusVariation; // 0xe8796bce
  float chorusPeriod; // 0x24bbd5e4
  bool reverbStdEnabled; // 0xff31631b
  bool unknown_0x4a5bbf90; // 0x4a5bbf90
  float reverbStdTime; // 0x9662498a
  float reverbStdPreDelay; // 0x91855d62
  float reverbStdDamping; // 0xd34d2029
  float reverbStdColoration; // 0xdc78e83d
  float reverbStdMix; // 0x820b509e
  bool delayEnabled; // 0xe9a36031
  int delay0; // 0x62c49457
  int delay1; // 0xda78f332
  int delay2; // 0xc8cd5cdc
  int delayFeedback0; // 0x7c14ff17
  int delayFeedback1; // 0xc4a89872
  int delayFeedback2; // 0xd61d379c
  int delayOutput0; // 0x9f75987f
  int delayOutput1; // 0x27c9ff1a
  int delayOutput2; // 0x357c50f4
  int delayLowPassFilter; // 0xcf45711c
  int delayHighPassFilter; // 0x626d1e9b
  bool flangerEnabled; // 0x7d8ee273
  float flangerDelay; // 0x83378e6a
  float flangerDelayPhase; // 0xf549d269
  float flangerDry; // 0x11fdae16
  float flangerFeedback; // 0xa3c439c1
  float flangerLFODepth; // 0x2dc70efe
  float flangerLFOFrequency; // 0xe2bd3706
  float flangerLFOWave; // 0x5e29cef8
  float flangerOut; // 0x35ae9f10
  bool bitcrusherEnabled; // 0x3e8d8694
  int unknown_0xf51a1d6a; // 0xf51a1d6a
  float bitcrusherGain; // 0xbb1a0f34
  int bitcrusherBitDepth; // 0xeb009039
  float bitcrusherSampleRateReduction; // 0x58096e0b
  bool phaserEnabled; // 0x3d8cad84
  float phaserFrequency; // 0x23c340f6
  float phaserFeedback; // 0x1e5a52b8
  float phaserInvert; // 0x1d69bec4
  float phaserMix; // 0x24538c4a
  float phaserSweep; // 0xd5388116
};

inline SLdrRoomAcoustics::SLdrRoomAcoustics() : editorProperties() {
  editorProperties.unknown_0x5d298a43 = 3;
  roomVolume = 117;
  priority = 1;
  reverbHiEnabled = false;
  unknown_0x3263c26e = false;
  reverbHiTime = 0.0f;
  reverbHiPreDelay = 0.0f;
  reverbHiDamping = 0.0f;
  reverbHiColoration = 0.0f;
  reverbHiCrossTalk = 0.0f;
  reverbHiMix = 0.0f;
  chorusEnabled = false;
  chorusBaseDelay = 0.0f;
  chorusVariation = 0.0f;
  chorusPeriod = 0.0f;
  reverbStdEnabled = false;
  unknown_0x4a5bbf90 = false;
  reverbStdTime = 0.0f;
  reverbStdPreDelay = 0.0f;
  reverbStdDamping = 0.0f;
  reverbStdColoration = 0.0f;
  reverbStdMix = 0.0f;
  delayEnabled = false;
  delay0 = 0;
  delay1 = 0;
  delay2 = 0;
  delayFeedback0 = 0;
  delayFeedback1 = 0;
  delayFeedback2 = 0;
  delayOutput0 = 0;
  delayOutput1 = 0;
  delayOutput2 = 0;
  delayLowPassFilter = 32000;
  delayHighPassFilter = 0;
  flangerEnabled = false;
  flangerDelay = 0.0f;
  flangerDelayPhase = 0.0f;
  flangerDry = 0.0f;
  flangerFeedback = 0.0f;
  flangerLFODepth = 0.0f;
  flangerLFOFrequency = 0.0f;
  flangerLFOWave = 0.0f;
  flangerOut = 0.0f;
  bitcrusherEnabled = false;
  unknown_0xf51a1d6a = 0;
  bitcrusherGain = 0.0f;
  bitcrusherBitDepth = 0;
  bitcrusherSampleRateReduction = 1.0f;
  phaserEnabled = false;
  phaserFrequency = 0.0f;
  phaserFeedback = 0.0f;
  phaserInvert = 0.0f;
  phaserMix = 0.0f;
  phaserSweep = 200.0f;
}

inline SLdrRoomAcoustics::~SLdrRoomAcoustics() {}

#endif
