// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRKROCUSS_HPP
#define _SLDRKROCUSS_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrKrocuss {
  SLdrKrocuss();
  ~SLdrKrocuss();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int flavor; // 0xbe73724a
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  float waypointApproachDistance; // 0x733bd27c
  float visibleDistance; // 0xa72530e8
  float wallTurnSpeed; // 0xac47c628
  float floorTurnSpeed; // 0x8e4f7b29
  float downTurnSpeed; // 0x3d3c1b76
  float stickyReach; // 0xd5c25506
  float projectileBoundsMultiplier; // 0x742eab20
  float collisionLookAhead; // 0x80a81909
  float animSpeedScalar; // 0x8590483b
  bool initiallyPaused; // 0xc3cc437f
  float timeShellClosed; // 0xf04cadca
  float timeToOpenShell; // 0x497d54e8
  float timeShellOpen; // 0x3371c963
  float timeToCloseShell; // 0x22d37771
  float unknown_0xbbebed9e; // 0xbbebed9e
  SLdrDamageVulnerability shellClosedVulnerability; // 0x6bd144c8
  CColor wingLightColor; // 0x4d20624b
  CAssetId dPSC; // 0xc3566114
  int shellOpenSound; // 0x6a11338f
  int shellCloseSound; // 0xf64ca627
  float maxAudibleDistance; // 0x214e48a0
};

void LoadTypedefSLdrKrocuss(SLdrKrocuss& data, CInputStream& input);

#endif
