// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTRIGGER_HPP
#define _SLDRTRIGGER_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrTriggerInfo.hpp"

struct SLdrTrigger {
  SLdrTrigger();
  ~SLdrTrigger();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrTriggerInfo trigger; // 0x77a27411
  bool deactivateOnEnter; // 0x8d33465f
  bool deactivateOnExit; // 0x1c453986
};

void LoadTypedefSLdrTrigger(SLdrTrigger& data, CInputStream& input);

#endif
