// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSPLITTERCOMMANDMODULE_HPP
#define _SLDRSPLITTERCOMMANDMODULE_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrIngPossessionData.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPlasmaBeamInfo.hpp"

struct SLdrUnknownStruct42 {
  SLdrUnknownStruct42();
  ~SLdrUnknownStruct42();

  float angle; // 0x382a1973
  CColor cloudColor1; // 0x4c41dcd4
  CColor cloudColor2; // 0xcad5ae7a
  CColor addColor1; // 0x1e52124e
  CColor addColor2; // 0x98c660e0
  float cloudScale; // 0x10c1ded2
  float fadeOffSize; // 0xae71a22a
  float openSpeed; // 0x4e29c85a
};

void LoadTypedefSLdrUnknownStruct42(SLdrUnknownStruct42& data, CInputStream& input);

struct SLdrSplitterCommandModuleData {
  SLdrSplitterCommandModuleData();
  ~SLdrSplitterCommandModuleData();

  int unknown_0xbd80fd94; // 0xbd80fd94
  float maxLinearVelocity; // 0x00d74fc3
  float maxTurnSpeed; // 0x0b5c3c1a
  float scanningTurnSpeed; // 0xa0b3e1be
  float minLaserPulseAttackTime; // 0xe32fcae9
  float minLaserPulseRange; // 0xc5e0b92c
  float maxLaserPulseRange; // 0xc17a8806
  int maxLaserPulseShots; // 0xe75bae9e
  CAssetId laserPulseProjectile; // 0x4d77b7aa
  SLdrDamageInfo laserPulseDamage; // 0xb763eb10
  int minDodges; // 0xeda45014
  int maxDodges; // 0x7dd740fe
  float dodgeChance; // 0x47be3298
  float resetShieldTime; // 0xd3dec6dc
  float shieldHP; // 0xecd9d92d
  float laserSweepTurnSpeed; // 0x5ff006d1
  SLdrDamageInfo laserSweepDamage; // 0x1bd017ce
  SLdrPlasmaBeamInfo laserSweepBeamInfo; // 0x4a37c437
  SLdrUnknownStruct42 unknown_0x9ec51fe4; // 0x9ec51fe4
  int sound_LaserSweep; // 0xea307548
  int sound_LaserChargeUp; // 0x3779bd93
  int sound_Docking; // 0xc90dbdb4
  int sound_Scanning; // 0xe7724802
  int sound_LightShield; // 0xd4a06273
  int sound_DarkShield; // 0xafc20631
  int sound_ShieldOn; // 0x2ff5a809
  SLdrIngPossessionData ingPossessionData; // 0xe61748ed
  SLdrDamageVulnerability lightShieldVulnerability; // 0x80a8ef3b
  SLdrDamageVulnerability darkShieldVulnerability; // 0xa21c90ea
};

void LoadTypedefSLdrSplitterCommandModuleData(SLdrSplitterCommandModuleData& data, CInputStream& input);

struct SLdrSplitterCommandModule {
  SLdrSplitterCommandModule();
  ~SLdrSplitterCommandModule();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrSplitterCommandModuleData commandModuleProperties; // 0x560cf813
};

void LoadTypedefSLdrSplitterCommandModule(SLdrSplitterCommandModule& data, CInputStream& input);

#endif
