// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRMEMORYRELAY_HPP
#define _SLDRMEMORYRELAY_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrMemoryRelay {
  SLdrMemoryRelay();
  ~SLdrMemoryRelay();

  SLdrEditorProperties editorProperties; // 0x255a4580
  bool oneShot; // 0xead7b7bb
  bool delayedAction; // 0xa905ccf0
};

void LoadTypedefSLdrMemoryRelay(SLdrMemoryRelay& data, CInputStream& input);

#endif
