// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRMETAREE_HPP
#define _SLDRMETAREE_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAudioPlaybackParms.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrMetaree {
  SLdrMetaree();
  ~SLdrMetaree();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrDamageInfo radiusDamage; // 0x086d58dd
  float dropHeight; // 0x38a5566f
  CVector3f collisionOffset0; // 0xa287077d
  float attackSpeed; // 0x6c0a2bc8
  float dropDelay; // 0x0097f282
  float haltDelay; // 0xe4e808c9
  float launchSpeed; // 0x31381a17
  SLdrAudioPlaybackParms turnSound; // 0xea11d1fa
};

void LoadTypedefSLdrMetaree(SLdrMetaree& data, CInputStream& input);

#endif
