// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRFOGVOLUME_HPP
#define _SLDRFOGVOLUME_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrFogVolume {
  SLdrFogVolume();
  ~SLdrFogVolume();

  SLdrEditorProperties editorProperties; // 0x255a4580
  float fogBobHeight; // 0xb90dff44
  float fogBobFreq; // 0xf608d35c
  CColor fogColor; // 0xe578c0dd
};

void LoadTypedefSLdrFogVolume(SLdrFogVolume& data, CInputStream& input);

#endif
