// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDREMPULSE_HPP
#define _SLDREMPULSE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrEMPulse {
  SLdrEMPulse();
  ~SLdrEMPulse();

  SLdrEditorProperties editorProperties; // 0x255a4580
  float initialSize;                     // 0x636df2db
  float finalSize;                       // 0x1e6686fe
  float duration;                        // 0x8b51e23f
  float minHudDisableTime;               // 0x96bd6426
  float maxHudDisableTime;               // 0xd7aa5ba0
  float minHudDisableAmount;             // 0x15ebb6e9
  float maxHudDisableAmount;             // 0xce54e50e
  CAssetId explosion;                    // 0xd8c6d15c
};

inline SLdrEMPulse::SLdrEMPulse() : editorProperties(), explosion(kInvalidAssetId) {
  editorProperties.active = false;
  initialSize = 0.1f;
  finalSize = 34.0f;
  duration = 1.3329999f;
  minHudDisableTime = 1.0f;
  maxHudDisableTime = 3.0f;
  minHudDisableAmount = 0.40000001f;
  maxHudDisableAmount = 0.80000001f;
}

inline SLdrEMPulse::~SLdrEMPulse() {}

#endif
