// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRRIPPLE_HPP
#define _SLDRRIPPLE_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrRipple {
  SLdrRipple();
  ~SLdrRipple();

  SLdrEditorProperties editorProperties; // 0x255a4580
  float energy;                          // 0x69731a91
};

inline SLdrRipple::SLdrRipple() : editorProperties() { energy = -0.1f; }

inline SLdrRipple::~SLdrRipple() {}

#endif
