// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRAREAATTRIBUTES_HPP
#define _SLDRAREAATTRIBUTES_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrAreaAttributes {
  SLdrAreaAttributes();
  ~SLdrAreaAttributes();

  SLdrEditorProperties editorProperties; // 0x255a4580
  bool needSky; // 0x95d4bee7
  bool darkWorld; // 0xb24fde1a
  int environmentEffects; // 0x9d0006ab
  int environmentGroupSound; // 0x56263e35
  float density; // 0x64e5fe9f
  float normalLighting; // 0xba5f801e
  CAssetId overrideSky; // 0xd208c9fa
  int phazonDamage; // 0xffeebc46
};

inline SLdrAreaAttributes::SLdrAreaAttributes() : editorProperties(), overrideSky(kInvalidAssetId) {
  needSky = false;
  darkWorld = false;
  environmentEffects = 0;
  environmentGroupSound = 0;
  density = 1.0f;
  normalLighting = 1.0f;
  phazonDamage = 0;
}

inline SLdrAreaAttributes::~SLdrAreaAttributes() {}

#endif
