// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRRUBIKSPUZZLE_HPP
#define _SLDRRUBIKSPUZZLE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrRubiksPuzzleData {
  SLdrRubiksPuzzleData();
  ~SLdrRubiksPuzzleData();

  float rotationSpeed; // 0x11cd076f
  CAssetId stateMachine; // 0x55744160
};

void LoadTypedefSLdrRubiksPuzzleData(SLdrRubiksPuzzleData& data, CInputStream& input);

struct SLdrRubiksPuzzle {
  SLdrRubiksPuzzle();
  ~SLdrRubiksPuzzle();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrRubiksPuzzleData rubiksPuzzleProperties; // 0x9fcd4e38
};

void LoadTypedefSLdrRubiksPuzzle(SLdrRubiksPuzzle& data, CInputStream& input);

#endif
