// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRPOINTOFINTEREST_HPP
#define _SLDRPOINTOFINTEREST_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrScannableParameters.hpp"

struct SLdrPointOfInterest {
  SLdrPointOfInterest();
  ~SLdrPointOfInterest();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrScannableParameters scanInfo; // 0xbdbec295
  float scanOffset; // 0x87271632
  bool lookAtPOI; // non-matching name, 0x01f9c5bb
};

inline SLdrPointOfInterest::SLdrPointOfInterest() : editorProperties(), scanInfo() {
  scanOffset = 1.5f;
  lookAtPOI = false;
}

inline SLdrPointOfInterest::~SLdrPointOfInterest() {}

#endif
