// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRPICKUPGENERATOR_HPP
#define _SLDRPICKUPGENERATOR_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrPickupGenerator {
  SLdrPickupGenerator();
  ~SLdrPickupGenerator();

  SLdrEditorProperties editorProperties; // 0x255a4580
  CVector3f offset; // 0x46477064
  bool offsetIsLocalSpace; // 0x72bbe7a6
  CAssetId rules; // 0x0c5143fe
};

void LoadTypedefSLdrPickupGenerator(SLdrPickupGenerator& data, CInputStream& input);

#endif
