// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCAMERAPITCH_HPP
#define _SLDRCAMERAPITCH_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrSplineType.hpp"

struct SLdrCameraPitch {
  SLdrCameraPitch();
  ~SLdrCameraPitch();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrSpline forwardsPitch; // 0x81d093b3
  SLdrSpline backwardsPitch; // 0xad9f8e3e
  SLdrSplineType playerSplineType; // 0x33e4685b
  bool playerSplineLoops; // 0x431769c6
};

void LoadTypedefSLdrCameraPitch(SLdrCameraPitch& data, CInputStream& input);

#endif
