// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRINGSPIDERBALLGUARDIAN_HPP
#define _SLDRINGSPIDERBALLGUARDIAN_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAudioPlaybackParms.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrIngSpiderballGuardianStruct {
  SLdrIngSpiderballGuardianStruct();
  ~SLdrIngSpiderballGuardianStruct();

  float minPatrolSpeed; // 0x17c5b61d
  float maxPatrolSpeed; // 0xb0f13664
  float linearAcceleration; // 0xaf9b05f4
  float angularSpeed; // 0xbcd7333f
  float stunnedHitPoints; // 0xd1d9d8bd
  float stunnedSpeed; // 0x8d5917d4
  float stunnedTime; // 0x8105ecfd
  float maxChargeTime; // 0xe5065ea8
};

inline SLdrIngSpiderballGuardianStruct::SLdrIngSpiderballGuardianStruct() {
  minPatrolSpeed = 5.0f;
  maxPatrolSpeed = 10.0f;
  linearAcceleration = 7.0f;
  angularSpeed = 720.0f;
  stunnedHitPoints = 40.0f;
  stunnedSpeed = 2.0f;
  stunnedTime = 25.0f;
  maxChargeTime = 15.0f;
}

inline SLdrIngSpiderballGuardianStruct::~SLdrIngSpiderballGuardianStruct() {}

inline void LoadTypedefIngSpiderballGuardianStruct(SLdrIngSpiderballGuardianStruct& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x17c5b61d: {
      sldrThis.minPatrolSpeed = input.ReadFloat();
      break;
    }
    case 0xb0f13664: {
      sldrThis.maxPatrolSpeed = input.ReadFloat();
      break;
    }
    case 0xaf9b05f4: {
      sldrThis.linearAcceleration = input.ReadFloat();
      break;
    }
    case 0xbcd7333f: {
      sldrThis.angularSpeed = input.ReadFloat();
      break;
    }
    case 0xd1d9d8bd: {
      sldrThis.stunnedHitPoints = input.ReadFloat();
      break;
    }
    case 0x8d5917d4: {
      sldrThis.stunnedSpeed = input.ReadFloat();
      break;
    }
    case 0x8105ecfd: {
      sldrThis.stunnedTime = input.ReadFloat();
      break;
    }
    case 0xe5065ea8: {
      sldrThis.maxChargeTime = input.ReadFloat();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrIngSpiderballGuardianData {
  SLdrIngSpiderballGuardianData();
  ~SLdrIngSpiderballGuardianData();

  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct; // non-matching name, 0x152db484
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0x2d163ff7; // non-matching name, 0x2d163ff7
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0x8c2fbb19; // non-matching name, 0x8c2fbb19
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0x5d612911; // non-matching name, 0x5d612911
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0xfc58adff; // non-matching name, 0xfc58adff
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0xc463268c; // non-matching name, 0xc463268c
  float damageRadius; // 0x0f598739
  SLdrDamageInfo proximityDamage; // 0xba78d281
  float unknown_0x32133b39; // 0x32133b39
  SLdrAudioPlaybackParms audioPlaybackParms; // non-matching name, 0xaed23abc
  SLdrAudioPlaybackParms sound_SpiderballRolling; // 0x3a5e2f52
  SLdrAudioPlaybackParms sound_SpiderballSlowRolling; // 0xcee38f10
  SLdrAudioPlaybackParms sound_SpiderballFastRolling; // 0x796fa303
  SLdrAudioPlaybackParms sound_EnterStunned; // 0xd5f3e9c4
  SLdrAudioPlaybackParms audioPlaybackParms_0x44c1f241; // non-matching name, 0x44c1f241
};

inline SLdrIngSpiderballGuardianData::SLdrIngSpiderballGuardianData() : ingSpiderballGuardianStruct(), ingSpiderballGuardianStruct_0x2d163ff7(), ingSpiderballGuardianStruct_0x8c2fbb19(), ingSpiderballGuardianStruct_0x5d612911(), ingSpiderballGuardianStruct_0xfc58adff(), ingSpiderballGuardianStruct_0xc463268c(), proximityDamage(), audioPlaybackParms(), sound_SpiderballRolling(), sound_SpiderballSlowRolling(), sound_SpiderballFastRolling(), sound_EnterStunned(), audioPlaybackParms_0x44c1f241() {
  damageRadius = 2.0f;
  proximityDamage.unknown_0x119fbd31 = 11;
  proximityDamage.dI_Damage = 40.0f;
  proximityDamage.dI_KnockBackPower = 10.0f;
  unknown_0x32133b39 = 20.0f;
}

inline SLdrIngSpiderballGuardianData::~SLdrIngSpiderballGuardianData() {}

inline void LoadTypedefIngSpiderballGuardianData(SLdrIngSpiderballGuardianData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x152db484: {
      LoadTypedefIngSpiderballGuardianStruct(sldrThis.ingSpiderballGuardianStruct, input);
      break;
    }
    case 0x2d163ff7: {
      LoadTypedefIngSpiderballGuardianStruct(sldrThis.ingSpiderballGuardianStruct_0x2d163ff7, input);
      break;
    }
    case 0x8c2fbb19: {
      LoadTypedefIngSpiderballGuardianStruct(sldrThis.ingSpiderballGuardianStruct_0x8c2fbb19, input);
      break;
    }
    case 0x5d612911: {
      LoadTypedefIngSpiderballGuardianStruct(sldrThis.ingSpiderballGuardianStruct_0x5d612911, input);
      break;
    }
    case 0xfc58adff: {
      LoadTypedefIngSpiderballGuardianStruct(sldrThis.ingSpiderballGuardianStruct_0xfc58adff, input);
      break;
    }
    case 0xc463268c: {
      LoadTypedefIngSpiderballGuardianStruct(sldrThis.ingSpiderballGuardianStruct_0xc463268c, input);
      break;
    }
    case 0x0f598739: {
      sldrThis.damageRadius = input.ReadFloat();
      break;
    }
    case 0xba78d281: {
      LoadTypedefDamageInfo(sldrThis.proximityDamage, input);
      break;
    }
    case 0x32133b39: {
      sldrThis.unknown_0x32133b39 = input.ReadFloat();
      break;
    }
    case 0xaed23abc: {
      LoadTypedefAudioPlaybackParms(sldrThis.audioPlaybackParms, input);
      break;
    }
    case 0x3a5e2f52: {
      LoadTypedefAudioPlaybackParms(sldrThis.sound_SpiderballRolling, input);
      break;
    }
    case 0xcee38f10: {
      LoadTypedefAudioPlaybackParms(sldrThis.sound_SpiderballSlowRolling, input);
      break;
    }
    case 0x796fa303: {
      LoadTypedefAudioPlaybackParms(sldrThis.sound_SpiderballFastRolling, input);
      break;
    }
    case 0xd5f3e9c4: {
      LoadTypedefAudioPlaybackParms(sldrThis.sound_EnterStunned, input);
      break;
    }
    case 0x44c1f241: {
      LoadTypedefAudioPlaybackParms(sldrThis.audioPlaybackParms_0x44c1f241, input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrIngSpiderballGuardian {
  SLdrIngSpiderballGuardian();
  ~SLdrIngSpiderballGuardian();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrIngSpiderballGuardianData ingSpiderballGuardianProperties; // 0xa1389799
};

inline SLdrIngSpiderballGuardian::SLdrIngSpiderballGuardian() : editorProperties(), patterned(), actorInformation(), ingSpiderballGuardianProperties() {
  patterned.turnSpeed = 360.0f;
  patterned.minAttackRange = 0.0f;
  patterned.health.health = 150.0f;
  patterned.health.hI_KnockBackResistance = 2.0f;
  patterned.creatureSize = 1;
}

inline SLdrIngSpiderballGuardian::~SLdrIngSpiderballGuardian() {}

#endif
