// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRWATER_HPP
#define _SLDRWATER_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrTriggerInfo.hpp"

struct SLdrLayerInfo {
  SLdrLayerInfo();
  ~SLdrLayerInfo();

  int motionType; // 0xe94f7e87
  float timeToCycleTex; // 0x3c5b0c98
  float rotation; // 0x912954e6
  float amplitude; // 0x89e3d294
  float textureScale; // 0x080c7499
};

inline SLdrLayerInfo::SLdrLayerInfo() {
  motionType = -2143184152;
  timeToCycleTex = 0.0f;
  rotation = 0.0f;
  amplitude = -0.0f;
  textureScale = 0.0f;
}

inline SLdrLayerInfo::~SLdrLayerInfo() {}

inline void LoadTypedefLayerInfo(SLdrLayerInfo& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0xe94f7e87: {
      sldrThis.motionType = input.ReadInt32();
      break;
    }
    case 0x3c5b0c98: {
      sldrThis.timeToCycleTex = input.ReadFloat();
      break;
    }
    case 0x912954e6: {
      sldrThis.rotation = input.ReadFloat();
      break;
    }
    case 0x89e3d294: {
      sldrThis.amplitude = input.ReadFloat();
      break;
    }
    case 0x080c7499: {
      sldrThis.textureScale = input.ReadFloat();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrWater {
  SLdrWater();
  ~SLdrWater();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrTriggerInfo trigger; // 0x77a27411
  float alphaFadeinTime; // 0xde5ea267
  float alphaFadeoutTime; // 0x22b69324
  float morphTimeTo; // 0x4c60077e
  float morphTimeRestore; // 0x8518047a
  int fluidType; // 0x7d606b78
  CAssetId lightMap; // 0x2421a2bf
  CAssetId colorMap; // 0x5e8b37dd
  CAssetId colorWarpMap; // 0x031d987e
  CAssetId glossMap; // 0x5aa79c9f
  CAssetId envMap; // 0x2f0645cf
  float envMapSize; // 0xde054447
  CAssetId refractWarpMap; // 0x7a4b4685
  CAssetId foamMap; // 0x5ba7702e
  CAssetId alphaMap; // 0x9a3463a7
  CColor baseColor; // 0x041398d5
  float alpha; // 0x0f7c6fc2
  float glossFlat; // 0x26382fcb
  float glossTopDown; // 0xc63a0616
  float refractWarpFlat; // 0xdb7a3a6b
  float refractWarpTopDown; // 0xb0259d23
  SLdrLayerInfo flowColor; // 0x244e9e6d
  SLdrLayerInfo flowColorWarp; // 0xe75248e4
  SLdrLayerInfo flowGloss1; // 0x385e0d43
  SLdrLayerInfo flowGloss2; // 0xd369b640
  SLdrLayerInfo flowRefractWarp; // 0x6ddea66d
  float flowSpeed; // 0xf14e3a14
  float flowOrientation; // 0x33eecdfd
  CColor underwaterFogColor; // 0x5a96218c
  CColor splashColor; // 0x13b56c22
  CAssetId splash_Small; // 0x3027043c
  CAssetId splash_Medium; // 0x41c12be2
  CAssetId splash_Big; // 0xd6e82200
  CAssetId visorRunoff; // 0x94a23bf9
  CAssetId visorRunoffBall; // 0x43a704fb
  int sound_SoundRunoff; // 0xba717f19
  int sound_SoundRunoffBall; // 0xae7c7efc
  int sound_Splash_Small; // 0xeef81e4c
  int sound_Splash_Medium; // 0x63c96763
  int sound_Splash_Big; // 0xd36209bc
  CColor fogColor; // 0xe578c0dd
  float fogHeight; // 0xb4b0fd8d
  float fogBobHeight; // 0xb90dff44
  float fogBobFreq; // 0xf608d35c
  float fogNoGravSuitDist; // 0xd8521c1c
  float fogNoGravSuitFactor; // 0x7dce5dc2
  float fogGravSuitDist; // 0x71819b3c
  float fogGravSuitFactor; // 0x9b96c630
  float viscosity; // 0xffe26f5c
  bool renderSurface; // 0xb5e9859f
  bool useDynamicLights; // 0x3ddca674
  float renderTileScaleX; // 0x0e791782
  float renderTileScaleY; // 0xc525c427
  float lightMapResolution; // 0x3425e83f
  float lightMapScaleX; // 0x2293fdb0
  float lightMapScaleY; // 0xe9cf2e15
  float lightMapOffsetX; // 0x268846d6
  float lightMapOffsetY; // 0xedd49573
  bool unknown_0xc71c0d63; // 0xc71c0d63
  bool filterSoundEffects; // 0x822118b4
  int unknown_0x414379ea; // 0x414379ea
};

inline SLdrWater::SLdrWater() : editorProperties(), trigger(), lightMap(kInvalidAssetId), colorMap(kInvalidAssetId), colorWarpMap(kInvalidAssetId), glossMap(kInvalidAssetId), envMap(kInvalidAssetId), refractWarpMap(kInvalidAssetId), foamMap(kInvalidAssetId), alphaMap(kInvalidAssetId), baseColor(CColor::Green()), flowColor(), flowColorWarp(), flowGloss1(), flowGloss2(), flowRefractWarp(), underwaterFogColor(CColor::Green()), splashColor(CColor::Green()), splash_Small(kInvalidAssetId), splash_Medium(kInvalidAssetId), splash_Big(kInvalidAssetId), visorRunoff(kInvalidAssetId), visorRunoffBall(kInvalidAssetId), fogColor(CColor::Green()) {
  alphaFadeinTime = 0.0f;
  alphaFadeoutTime = 0.0f;
  morphTimeTo = 5.0f;
  morphTimeRestore = 5.0f;
  fluidType = 0;
  envMapSize = 1.0f;
  baseColor = CColor(0.0f, 0.0f, 0.49803901f, 1.0f);
  alpha = 0.60000002f;
  glossFlat = 0.2f;
  glossTopDown = 1.0f;
  refractWarpFlat = 1.0f;
  refractWarpTopDown = 0.0f;
  flowColor.motionType = 0;
  flowColor.timeToCycleTex = 5.0f;
  flowColor.amplitude = 0.15000001f;
  flowColor.textureScale = 10.0f;
  flowColorWarp.motionType = 0;
  flowColorWarp.timeToCycleTex = 5.0f;
  flowColorWarp.amplitude = 0.15000001f;
  flowColorWarp.textureScale = 10.0f;
  flowGloss1.motionType = 0;
  flowGloss1.timeToCycleTex = 5.0f;
  flowGloss1.amplitude = 0.15000001f;
  flowGloss1.textureScale = 10.0f;
  flowGloss2.motionType = 0;
  flowGloss2.timeToCycleTex = 5.0f;
  flowGloss2.amplitude = 0.15000001f;
  flowGloss2.textureScale = 10.0f;
  flowRefractWarp.motionType = 0;
  flowRefractWarp.timeToCycleTex = 5.0f;
  flowRefractWarp.amplitude = 0.15000001f;
  flowRefractWarp.textureScale = 10.0f;
  flowSpeed = 10.0f;
  flowOrientation = 0.0f;
  underwaterFogColor = CColor(0.0f, 0.49803901f, 1.0f, 1.0f);
  splashColor = CColor(1.0f, 1.0f, 1.0f, 1.0f);
  sound_SoundRunoff = 0;
  sound_SoundRunoffBall = -1;
  sound_Splash_Small = 0;
  sound_Splash_Medium = 0;
  sound_Splash_Big = 0;
  fogColor = CColor(1.0f, 1.0f, 1.0f, 1.0f);
  fogHeight = 0.0f;
  fogBobHeight = 0.0f;
  fogBobFreq = 1.0f;
  fogNoGravSuitDist = 30.0f;
  fogNoGravSuitFactor = 125.0f;
  fogGravSuitDist = 150.0f;
  fogGravSuitFactor = 300.0f;
  viscosity = 0.5f;
  renderSurface = true;
  useDynamicLights = true;
  renderTileScaleX = 1.0f;
  renderTileScaleY = 1.0f;
  lightMapResolution = 0.30000001f;
  lightMapScaleX = 1.0f;
  lightMapScaleY = 1.0f;
  lightMapOffsetX = 0.0f;
  lightMapOffsetY = 0.0f;
  unknown_0xc71c0d63 = false;
  filterSoundEffects = true;
  unknown_0x414379ea = 300;
}

inline SLdrWater::~SLdrWater() {}

#endif
