// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRRUBIKSPUZZLE_HPP
#define _SLDRRUBIKSPUZZLE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrRubiksPuzzleData {
  SLdrRubiksPuzzleData();
  ~SLdrRubiksPuzzleData();

  float rotationSpeed;   // 0x11cd076f
  CAssetId stateMachine; // 0x55744160
};

inline SLdrRubiksPuzzleData::SLdrRubiksPuzzleData() : stateMachine(kInvalidAssetId) {
  rotationSpeed = 90.0f;
}

inline SLdrRubiksPuzzleData::~SLdrRubiksPuzzleData() {}

inline void LoadTypedefRubiksPuzzleData(SLdrRubiksPuzzleData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x11cd076f: {
      sldrThis.rotationSpeed = input.ReadFloat();
      break;
    }
    case 0x55744160: {
      sldrThis.stateMachine = CAssetId(input.ReadInt32());
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrRubiksPuzzle {
  SLdrRubiksPuzzle();
  ~SLdrRubiksPuzzle();

  SLdrEditorProperties editorProperties;       // 0x255a4580
  SLdrRubiksPuzzleData rubiksPuzzleProperties; // 0x9fcd4e38
};

inline SLdrRubiksPuzzle::SLdrRubiksPuzzle() : editorProperties(), rubiksPuzzleProperties() {}

inline SLdrRubiksPuzzle::~SLdrRubiksPuzzle() {}

#endif
