// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDROCTAPEDESEGMENT_HPP
#define _SLDROCTAPEDESEGMENT_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrOctapedeSegment {
  SLdrOctapedeSegment();
  ~SLdrOctapedeSegment();

  SLdrEditorProperties editorProperties; // 0x255a4580
  int flavor; // 0xbe73724a
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  float waypointApproachDistance; // 0x733bd27c
  float visibleDistance; // 0xa72530e8
  float wallTurnSpeed; // 0xac47c628
  float floorTurnSpeed; // 0x8e4f7b29
  float downTurnSpeed; // 0x3d3c1b76
  float stickyReach; // 0xd5c25506
  float projectileBoundsMultiplier; // 0x742eab20
  float collisionLookAhead; // 0x80a81909
  float animSpeedScalar; // 0x8590483b
  float maxAudibleDistance; // 0x214e48a0
  bool initiallyPaused; // 0xc3cc437f
  float unknown_0x4fb8747e; // 0x4fb8747e
  CAssetId betweenSegmentsEffect; // 0x1b58c5f1
  float minBreakApartSpeed; // 0x9b9c46fc
  float maxBreakApartSpeed; // 0x9f0677d6
  float minBreakApartAngle; // 0xc0241fc1
  float maxBreakApartAngle; // 0xc4be2eeb
  float minBreakApartSpinSpeed; // 0x99778599
  float maxBreakApartSpinSpeed; // 0xff92e3ed
  float minRunAroundTime; // 0xb8a1f0d5
  float maxRunAroundTime; // 0xabe4167e
  float unknown_0x2caddcbe; // 0x2caddcbe
  float unknown_0x4d320455; // 0x4d320455
  int minBounces; // 0xd6f71bb3
  int maxBounces; // 0x96b863c5
  float unknown_0x417f4a91; // 0x417f4a91
  SLdrDamageInfo explosionDamage; // 0xdeff74ea
  int walkSound; // 0xa24376ec
  int idleSound; // 0x40338715
  int seperateSound; // 0x527a643e
  int bounceSound; // 0x0bb3ccae
  int explodeSound; // 0xf3a4af05
  float unknown_0x0c4763d7; // 0x0c4763d7
};

inline SLdrOctapedeSegment::SLdrOctapedeSegment() : editorProperties(), patterned(), actorInformation(), betweenSegmentsEffect(kInvalidAssetId), explosionDamage() {
  flavor = 0;
  patterned.mass = 25.0f;
  patterned.speed = 3.0f;
  patterned.turnSpeed = 720.0f;
  patterned.detectionRange = 5.0f;
  patterned.detectionHeightRange = 5.0f;
  patterned.detectionAngle = 90.0f;
  patterned.minAttackRange = 4.0f;
  patterned.maxAttackRange = 20.0f;
  patterned.contactDamage.unknown_0x119fbd31 = 9;
  patterned.contactDamage.dI_Damage = 10.0f;
  patterned.contactDamage.dI_KnockBackPower = 5.0f;
  patterned.damageWaitTime = 3.0f;
  patterned.collisionRadius = 0.2f;
  patterned.collisionHeight = 5.0f;
  patterned.unknown_0xe287d8dd = 0.0f;
  waypointApproachDistance = 2.5f;
  visibleDistance = 2.5f;
  wallTurnSpeed = 360.0f;
  floorTurnSpeed = 180.0f;
  downTurnSpeed = 120.0f;
  stickyReach = 0.40000001f;
  projectileBoundsMultiplier = 1.0f;
  collisionLookAhead = 0.02f;
  animSpeedScalar = 1.0f;
  maxAudibleDistance = 50.0f;
  initiallyPaused = false;
  unknown_0x4fb8747e = 0.0f;
  minBreakApartSpeed = 0.0f;
  maxBreakApartSpeed = 0.0f;
  minBreakApartAngle = 0.0f;
  maxBreakApartAngle = 0.0f;
  minBreakApartSpinSpeed = 0.0f;
  maxBreakApartSpinSpeed = 0.0f;
  minRunAroundTime = 0.0f;
  maxRunAroundTime = 0.0f;
  unknown_0x2caddcbe = 1.0f;
  unknown_0x4d320455 = 2.0f;
  minBounces = 1;
  maxBounces = 1;
  unknown_0x417f4a91 = 0.75f;
  explosionDamage.unknown_0x119fbd31 = 9;
  explosionDamage.dI_Damage = 5.0f;
  explosionDamage.dI_KnockBackPower = 2.0f;
  walkSound = 0;
  idleSound = 0;
  seperateSound = 0;
  bounceSound = 0;
  explodeSound = 0;
  unknown_0x0c4763d7 = 0.0f;
}

inline SLdrOctapedeSegment::~SLdrOctapedeSegment() {}

#endif
