// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRRELAY_HPP
#define _SLDRRELAY_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrRelay {
  SLdrRelay();
  ~SLdrRelay();

  SLdrEditorProperties editorProperties; // 0x255a4580
  bool oneShot; // 0xead7b7bb
};

void LoadTypedefSLdrRelay(SLdrRelay& data, CInputStream& input);

#endif
