// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRINGSPIDERBALLGUARDIAN_HPP
#define _SLDRINGSPIDERBALLGUARDIAN_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAudioPlaybackParms.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrIngSpiderballGuardianStruct {
  SLdrIngSpiderballGuardianStruct();
  ~SLdrIngSpiderballGuardianStruct();

  float minPatrolSpeed; // 0x17c5b61d
  float maxPatrolSpeed; // 0xb0f13664
  float linearAcceleration; // 0xaf9b05f4
  float angularSpeed; // 0xbcd7333f
  float stunnedHitPoints; // 0xd1d9d8bd
  float stunnedSpeed; // 0x8d5917d4
  float stunnedTime; // 0x8105ecfd
  float maxChargeTime; // 0xe5065ea8
};

void LoadTypedefSLdrIngSpiderballGuardianStruct(SLdrIngSpiderballGuardianStruct& data, CInputStream& input);

struct SLdrIngSpiderballGuardianData {
  SLdrIngSpiderballGuardianData();
  ~SLdrIngSpiderballGuardianData();

  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct; // 0x152db484
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0x2d163ff7; // 0x2d163ff7
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0x8c2fbb19; // 0x8c2fbb19
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0x5d612911; // 0x5d612911
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0xfc58adff; // 0xfc58adff
  SLdrIngSpiderballGuardianStruct ingSpiderballGuardianStruct_0xc463268c; // 0xc463268c
  float damageRadius; // 0x0f598739
  SLdrDamageInfo proximityDamage; // 0xba78d281
  float unknown_0x32133b39; // 0x32133b39
  SLdrAudioPlaybackParms audioPlaybackParms; // 0xaed23abc
  SLdrAudioPlaybackParms sound_SpiderballRolling; // 0x3a5e2f52
  SLdrAudioPlaybackParms sound_SpiderballSlowRolling; // 0xcee38f10
  SLdrAudioPlaybackParms sound_SpiderballFastRolling; // 0x796fa303
  SLdrAudioPlaybackParms sound_EnterStunned; // 0xd5f3e9c4
  SLdrAudioPlaybackParms audioPlaybackParms_0x44c1f241; // 0x44c1f241
};

void LoadTypedefSLdrIngSpiderballGuardianData(SLdrIngSpiderballGuardianData& data, CInputStream& input);

struct SLdrIngSpiderballGuardian {
  SLdrIngSpiderballGuardian();
  ~SLdrIngSpiderballGuardian();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrIngSpiderballGuardianData ingSpiderballGuardianProperties; // 0xa1389799
};

void LoadTypedefSLdrIngSpiderballGuardian(SLdrIngSpiderballGuardian& data, CInputStream& input);

#endif
