// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRMYSTERYFLYER_HPP
#define _SLDRMYSTERYFLYER_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrMysteryFlyerData {
  SLdrMysteryFlyerData();
  ~SLdrMysteryFlyerData();

  CAssetId shotProjectile;   // 0x51253ba3
  SLdrDamageInfo shotDamage; // 0xcea30138
  float hoverSpeed;          // 0x845ef489
  float hoverHeight;         // 0xc75998aa
  float separationDistance;  // 0x01559f27
  bool needsToGenerate;      // 0x5f3fffd6
};

inline SLdrMysteryFlyerData::SLdrMysteryFlyerData()
: shotProjectile(kInvalidAssetId), shotDamage() {
  shotDamage.dI_WeaponType = 11;
  shotDamage.dI_Damage = 5.0f;
  hoverSpeed = 10.0f;
  hoverHeight = 2.0f;
  separationDistance = 5.0f;
  needsToGenerate = true;
}

inline SLdrMysteryFlyerData::~SLdrMysteryFlyerData() {}

inline void LoadTypedefMysteryFlyerData(SLdrMysteryFlyerData& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x51253ba3: {
      sldrThis.shotProjectile = CAssetId(input.ReadInt32());
      break;
    }
    case 0xcea30138: {
      LoadTypedefDamageInfo(sldrThis.shotDamage, input);
      break;
    }
    case 0x845ef489: {
      sldrThis.hoverSpeed = input.ReadFloat();
      break;
    }
    case 0xc75998aa: {
      sldrThis.hoverHeight = input.ReadFloat();
      break;
    }
    case 0x01559f27: {
      sldrThis.separationDistance = input.ReadFloat();
      break;
    }
    case 0x5f3fffd6: {
      sldrThis.needsToGenerate = input.ReadBool();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrMysteryFlyer {
  SLdrMysteryFlyer();
  ~SLdrMysteryFlyer();

  SLdrEditorProperties editorProperties;       // 0x255a4580
  SLdrPatternedAITypedef patterned;            // 0xb3774750
  SLdrActorParameters actorInformation;        // 0x7e397fed
  SLdrMysteryFlyerData mysteryFlyerProperties; // 0x44080565
};

inline SLdrMysteryFlyer::SLdrMysteryFlyer()
: editorProperties(), patterned(), actorInformation(), mysteryFlyerProperties() {}

inline SLdrMysteryFlyer::~SLdrMysteryFlyer() {}

#endif
