// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTWEAKGUICOLORS_HPP
#define _SLDRTWEAKGUICOLORS_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "rstl/string.hpp"

struct SLdrTweakGuiColors_HUDColorsTypedef {
  SLdrTweakGuiColors_HUDColorsTypedef();
  ~SLdrTweakGuiColors_HUDColorsTypedef();

  CColor hUDDecorativeColor; // 0xc8ddc662
  CColor threatGroupActiveColor; // 0x2f3cacaf
  CColor threatGroupInactiveColor; // 0x74e5ffa1
  CColor freeLookBarColor; // 0xa6609cc5
  CColor missileGroupActiveColor; // 0xcbb3fb76
  CColor missileGroupInactiveColor; // 0xd110a12f
  CColor unknown_0xdcaab836; // 0xdcaab836
  CColor energyBarFilledColor; // 0xacf62d93
  CColor energyBarShadowColor; // 0xb9a9fc6e
  CColor energyBarEmptyColor; // 0x37e381c2
  CColor energyTanksFilledColor; // 0x4377e677
  CColor energyTanksEmptyColor; // 0x63384f81
  CColor radarWidgetColor; // 0xa709db40
  CColor activeTextForegroundColor; // 0xaa4a5604
  CColor inactiveTextForegroundColor; // 0x6cccdf8f
  CColor textShadowOutlineColor; // 0x0daa7d80
};

void LoadTypedefSLdrTweakGuiColors_HUDColorsTypedef(SLdrTweakGuiColors_HUDColorsTypedef& data, CInputStream& input);

struct SLdrTweakGuiColors_Misc {
  SLdrTweakGuiColors_Misc();
  ~SLdrTweakGuiColors_Misc();

  CColor pauseScreenBGModulateColor; // 0x8ed04c36
  CColor unknown_0x166c22e0; // 0x166c22e0
  CColor unknown_0xcec78e81; // 0xcec78e81
  CColor unknown_0x91338f72; // 0x91338f72
  CColor unknown_0x0d24ae6b; // 0x0d24ae6b
  CColor unknown_0xddc561eb; // 0xddc561eb
  CColor unknown_0x9be28150; // 0x9be28150
  CColor hUDMemoTextForegroundColor; // 0x2df1eb03
  CColor hUDMemoTextOutlineColor; // 0xb5da30f4
  CColor hUDDecorativeColor; // 0xc8ddc662
  CColor hUDGlowColor; // 0x6991e2cd
  CColor hUDEnergyDecoColor; // 0x5c336f85
  CColor unknown_0xdefca700; // 0xdefca700
  CColor selectedVisorBeamColor; // 0xcb7ddaf4
  CColor unselectedVisorBeamColor; // 0xf17911aa
  CColor energyBarLowFilledColor; // 0xa14c8d20
  CColor energyBarLowShadowColor; // 0xb4135cdd
  CColor energyBarLowEmptyColor; // 0xe0290c48
  CColor hUDDamageModulateColor; // 0x1ec7f863
  CColor damageIndicatorColor; // 0xae1317d8
  CColor hudTitleForegroundColor; // 0x22b9b01e
  CColor hudTitleOutlineColor; // 0x70a2cd6e
  CColor visorMenuTitleForegroundColor; // 0xe7070332
  CColor visorMenuTitleOutlineColor; // 0x779c7b9c
  CColor beamMenuTitleForegroundColor; // 0x13bd3b64
  CColor beamMenuTitleOutlineColor; // 0x1531edd3
  CColor visorBeamMenuIconSelectedColor; // 0x27d0c234
  CColor visorBeamMenuIconUnselectedColor; // 0xbaa6d6a1
  CColor visorMenuIconColor0; // 0x59e416aa
  CColor visorMenuIconColor1; // 0x92b8c50f
  CColor visorMenuIconColor2; // 0x142cb7a1
  CColor visorMenuIconColor3; // 0xdf706404
  CColor beamMenuIconColor0; // 0x81269ee0
  CColor beamMenuIconColor1; // 0x4a7a4d45
  CColor beamMenuIconColor2; // 0xccee3feb
  CColor beamMenuIconColor3; // 0x07b2ec4e
  CColor energyWarningColor; // 0x6f6e9d6d
  CColor threatWarningColor; // 0xca68f68f
  CColor missileWarningColor; // 0x0c00a29f
  CColor missleDepletionColor; // 0x83040135
  CColor threatBarFilledColor; // 0x1adea12b
  CColor threatBarShadowColor; // 0x0f8170d6
  CColor threatBarEmptyColor; // 0x794204fd
  CColor missileBarFilledColor; // 0x3c1ae0ff
  CColor missileBarShadowColor; // 0x29453102
  CColor missileBarEmptyColor; // 0x64337ccd
  CColor threatGroupColor; // 0x4b86c539
  CColor freeLookBarColor; // 0xa6609cc5
  CColor hudBarDecoColor; // 0xbe3c29a1
  CColor unknown_0xf4379cf4; // 0xf4379cf4
  CColor threatGroupInactiveColor; // 0x74e5ffa1
  CColor missileGroupInactiveColor; // 0xd110a12f
  CColor missileGroupComboChargeColor; // 0xceb17cdf
  CColor missileGroupNonComboChargeColor; // 0x4c5aff4f
  CColor missileGroupComboActivatedColor; // 0x0b17b693
  CColor freeLookTickColor; // 0xfad063d5
  CColor freeLookDigitsForegroundColor; // 0x2eafedf7
  CColor freeLookDigitsOutlineColor; // 0x2a01734f
  CColor unknown_0x8b0a4c90; // 0x8b0a4c90
  CColor energyWarningOutlineColor; // 0xc4e17ca8
  CColor threatWarningOutlineColor; // 0xc7182898
  CColor missileWarningOutlineColor; // 0xcdbd73e1
  CColor helmetLightAmbientColor; // 0x78522461
  CColor flashPassColor; // 0x6a839a97
  CColor scanWindowFrameBaseColor; // 0x79ea6f12
  CColor scanWindowFrameActiveColor; // 0xdc901206
  CColor unknown_0xc54fa7bc; // 0xc54fa7bc
  CColor unknown_0x18717fa7; // 0x18717fa7
  CColor unknown_0x8b7d7378; // 0x8b7d7378
  CColor unknown_0x867b01a2; // 0x867b01a2
  CColor scanHudHierarchyFrameColor; // 0x08be8347
  CColor scanHudHierarchyInactiveFrameColor; // 0xe6ec3c8d
  CColor scanHudHierarchyTextFrameColor; // 0x591cd695
  CColor scanHudHierarchyFinalTextFrameColor; // 0x26e1eb8c
  CColor scanHudHierarchyFlashIconColor; // 0x63e9e374
  CColor scanHudHierarchyCompleteFlashIconColor; // 0x738d9c43
  CColor scanHudHierarchyFlashFlashIconColor; // 0xba6c75a2
  CColor scanHudHierarchyTextColor; // 0xc37d11b7
  CColor scanHudHierarchyFinalTextColor; // 0xef1ec40e
  CColor scanHudHierarchyPercentTextColor; // 0x0ca7beb2
  CColor scanHudHierarchyBarMeterColor; // 0x87d3ce8a
  CColor unknown_0xeb7eb756; // 0xeb7eb756
  CColor metroidSuckPulseColor; // 0xe4c1bbeb
  CColor unknown_0xce7c9d8d; // 0xce7c9d8d
  CColor energyBarDamageColor; // 0x13490420
  CColor xRayClampsColor; // 0xafe2d45d
  CColor xRayHoloGridColor; // 0x2af5aa06
  CColor xRaySeekerColor; // 0xd3cbe846
  CColor xRaySeekerTicksColor; // 0x507b51da
  CColor xRaySeekerTicksOuterColor; // 0xc61d97ef
  CColor xRayTopPuzzleColor; // 0xaf0001cf
  CColor xRayBottomPuzzleColor; // 0x150a9b17
  CColor xRayLeftPuzzleColor; // 0xd66d715f
  CColor xRayRightPuzzleColor; // 0xa8698fe8
  CColor xRayCornerColor; // 0x4cb38e71
  CColor xRayThreatDigitsForegroundColor; // 0x51c5aad9
  CColor xRayThreatDigitsOutlineColor; // 0x60e8322b
  CColor xRayMissileDigitsForegroundColor; // 0xa947a67c
  CColor xRayMissileDigitsOutlineColor; // 0x421bae2a
  CColor xRayThreatBarFilledColor; // 0xf0049167
  CColor xRayThreatBarEmptyColor; // 0x76357179
  CColor xRayMissileBarFilledColor; // 0x439a3774
  CColor xRayMissileBarEmptyColor; // 0x8ee94c81
  CColor scanDownloadSquareColor; // 0xbb0897ea
  CColor scanDotColor; // 0xc12cbab9
  CColor morphBallPowerBombDigitsForegroundColor; // 0x716e6398
  CColor morphBallPowerBombDigitsOutlineColor; // 0xdaca46d4
  CColor morphBallEnergyWordColor; // 0x0f37e756
  CColor morphBallBombCounterFilledColor; // 0xf7283644
  CColor morphBallBombCounterEmptyColor; // 0x37564b7d
  CColor morphBallPowerBombIconColor; // 0x66b7eda3
  CColor morphBallBombWordColor; // 0xf895098f
  CColor morphBallEnergyDecoColor; // 0x9b27be10
  CColor morphBallBombDecoColor; // 0x6c8550c9
  CColor unknown_0x5368a35f; // 0x5368a35f
  CColor morphBallEmptyPowerBombDigitsOutlineColor; // 0x5a807b81
  CColor morphBallEmptyPowerBombIconColor; // 0xeb63afed
  CColor scanPanelColor; // 0x92f59138
  CColor unknown_0x96f650c3; // 0x96f650c3
  CColor scanImagesColor; // 0xabdbfa5b
  CColor unknown_0xd3bafaf5; // 0xd3bafaf5
  CColor threatGroupDamageColor; // 0xf8b971fa
  CColor coundownForegroundColor; // 0x4f1d443e
  CColor coundownOutlineColor; // 0x0f6451da
  CColor unknown_0xc1ec3637; // 0xc1ec3637
  CColor unknown_0xb6a61e34; // 0xb6a61e34
  CColor unknown_0xfdcd9589; // 0xfdcd9589
  CColor unknown_0xb0253266; // 0xb0253266
  CColor scanSeekerColor; // 0x345e5b4e
  CColor thermalThreatDigitsOutlineColor; // 0xe8401c5a
  CColor thermalMissileDigitsOutlineColor; // 0x659147ae
  CColor combatMissileDigitsForegroundColor; // 0x43ed3310
  CColor combatMissileDigitsOutlineColor; // 0xa781ed1d
  CColor thermalDecoColor; // 0x35402188
  CColor thermalDecoOutlineColor; // 0x223058b5
  CColor unknown_0xe846d37f; // 0xe846d37f
  CColor thermalLockColor; // 0x8c9f2a1a
  CColor logBookColor; // 0x1b0f3a85
  CColor inventoryEquippedColor; // 0x149369fd
  CColor darkVisorDecoColor; // 0x02d5344f
  CColor lightAmmoTankFullSelectedColor; // 0xf37f8deb
  CColor lightAmmoTankFullUnselectedColor; // 0x5a6587df
  CColor lightAmmoTankEmptylSelectedColor; // 0xc18bdc67
  CColor lightAmmoTankEmptyUnselectedColor; // 0x4d916bb8
  CColor lightAmmoMeterSelectedFillColor; // 0x5ba76807
  CColor lightAmmoMeterSelectedShadowColor; // 0xa42f6495
  CColor lightAmmoMeterUnselectedFillColor; // 0x448156ae
  CColor lightAmmoMeterUnselectedShadowColor; // 0x1a8b61b8
  CColor lightAmmoIconSelectedColor; // 0xf36adacb
  CColor lightAmmoIconUnselectedColor; // 0x3aee673f
  CColor lightAmmoDigitsOutlineColor; // 0xf9c88b05
  CColor lightAmmoDigitsSelectedColor; // 0x3bffe826
  CColor lightAmmoDigitsUnselectedColor; // 0x19e9738b
  CColor lightAmmoChangeFlash; // 0x9329c6ff
  CColor lightAmmoTankWarningColor; // 0xf9e7e0df
  CColor lightAmmoMeterWarningColor; // 0x04e77411
  CColor lightAmmoDigitWarningColor; // 0x3c5d7111
  CColor lightAmmoDepletionColor; // 0x42e2dfc1
  CColor lightAmmoEmptyTankWarningColor; // 0xc758541f
  CColor darkAmmoTankFullSelectedColor; // 0xde649e48
  CColor darkAmmoTankFullUnselectedColor; // 0x5bf10430
  CColor darkAmmoTankEmptylSelectedColor; // 0xc01f5f88
  CColor darkAmmoTankEmptyUnselectedColor; // 0x7d2500d2
  CColor darkAmmoMeterSelectedFillColor; // 0x14558146
  CColor darkAmmoMeterSelectedShadowColor; // 0x949b0fff
  CColor darkAmmoMeterUnselectedFillColor; // 0x74353dc4
  CColor darkAmmoMeterUnselectedShadowColor; // 0x5ff96af1
  CColor darkAmmoIconSelectedColor; // 0x074bb42f
  CColor darkAmmoIconUnselectedColor; // 0xaaf6e9a9
  CColor darkAmmoDigitsOutlineColor; // 0x5e5b8c0a
  CColor darkAmmoDigitsSelectedColor; // 0xabe766b0
  CColor darkAmmoDigitsUnselectedColor; // 0x34f26028
  CColor darkAmmoChangeFlash; // 0xa59b3320
  int numHuds; // 0xbfffe95a
  CColor darkAmmoTankWarningColor; // 0x0c3c55c9
  CColor darkAmmoMeterWarningColor; // 0xf0c61af5
  CColor darkAmmoDigitWarningColor; // 0xc87c1ff5
  CColor darkAmmoDepletionColor; // 0x88936aa2
  CColor darkAmmoEmptyTankWarningColor; // 0xea4347bc
};

void LoadTypedefSLdrTweakGuiColors_Misc(SLdrTweakGuiColors_Misc& data, CInputStream& input);

struct SLdrTweakGuiColors_Multiplayer {
  SLdrTweakGuiColors_Multiplayer();
  ~SLdrTweakGuiColors_Multiplayer();

  CColor scoreTextColor; // 0x23cac744
  CColor winningScoreTextColor; // 0xa09caefe
  CColor timerTextColor; // 0x6bf04ff9
  CColor timerTextBlinkColor; // 0x4280d00a
  CColor scoreboardDecoColor; // 0xec4197e3
  CColor scoreboardBackgroundColor; // 0x823e2fb3
  CColor unknown_0x95cc4ed8; // 0x95cc4ed8
  CColor unknown_0xdb2ca6ff; // 0xdb2ca6ff
  CColor lockonIndicatorOnColor; // 0x03d27ffd
  CColor lockonIndicatorOffColor; // 0x4c215775
};

void LoadTypedefSLdrTweakGuiColors_Multiplayer(SLdrTweakGuiColors_Multiplayer& data, CInputStream& input);

struct SLdrTweakGui_VisorColorSchemeTypedef {
  SLdrTweakGui_VisorColorSchemeTypedef();
  ~SLdrTweakGui_VisorColorSchemeTypedef();

  CColor hUDHue; // 0x59148173
  CColor glassTint; // 0x9da5d1d7
};

void LoadTypedefSLdrTweakGui_VisorColorSchemeTypedef(SLdrTweakGui_VisorColorSchemeTypedef& data, CInputStream& input);

struct SLdrTweakGui_HudColorTypedef {
  SLdrTweakGui_HudColorTypedef();
  ~SLdrTweakGui_HudColorTypedef();

  CColor energyBarFilledColor; // 0xacf62d93
  CColor energyBarEmptyColor; // 0x37e381c2
  CColor energyBarShadowColor; // 0xb9a9fc6e
  CColor energyTanksFilledColor; // 0x4377e677
  CColor energyTanksEmptyColor; // 0x63384f81
  CColor energyDigitsForegroundColor; // 0x1fd3d43a
  CColor energyDigitsOutlineColor; // 0xe1ff2a4f
  CColor primaryEnergyBarFilledColor; // 0x9cfb8a36
  CColor primaryEnergyBarShadowColor; // 0x89a45bcb
  CColor primaryEnergyTankFilledColor; // 0xc2a8ccc6
};

void LoadTypedefSLdrTweakGui_HudColorTypedef(SLdrTweakGui_HudColorTypedef& data, CInputStream& input);

struct SLdrTweakGuiColors_TurretHudTypedef {
  SLdrTweakGuiColors_TurretHudTypedef();
  ~SLdrTweakGuiColors_TurretHudTypedef();

  CColor frameColor; // 0xa485372c
  CColor fontColor; // 0x1a96ec67
  CColor fontOutlineColor; // 0x844ab6b0
  CColor energyBarFillColor; // 0xbdb697a9
  CColor energyBarShadowColor; // 0xb9a9fc6e
  CColor energyBarEmptyColor; // 0x37e381c2
};

void LoadTypedefSLdrTweakGuiColors_TurretHudTypedef(SLdrTweakGuiColors_TurretHudTypedef& data, CInputStream& input);

struct SLdrTweakGuiColors {
  SLdrTweakGuiColors();
  ~SLdrTweakGuiColors();

  rstl::string instanceName; // 0x7fda1466
  SLdrTweakGuiColors_HUDColorsTypedef hUDColors; // 0xcb737724
  SLdrTweakGuiColors_Misc misc; // 0x6756d4de
  SLdrTweakGuiColors_Multiplayer multiplayer; // 0x697613e9
  SLdrTweakGui_VisorColorSchemeTypedef combatHudColorScheme; // 0x67c70055
  SLdrTweakGui_VisorColorSchemeTypedef echoHudColorScheme; // 0x62e0a08f
  SLdrTweakGui_VisorColorSchemeTypedef scanHudColorScheme; // 0x80becd6e
  SLdrTweakGui_VisorColorSchemeTypedef darkHudColorScheme; // 0x7de4b297
  SLdrTweakGui_VisorColorSchemeTypedef ballHudColorScheme; // 0xc0181762
  SLdrTweakGui_HudColorTypedef combatHud; // 0x45d7a40f
  SLdrTweakGui_HudColorTypedef scanHud; // 0x594b44cf
  SLdrTweakGui_HudColorTypedef xRayHud; // 0x8f5ebeb9
  SLdrTweakGui_HudColorTypedef thermalHud; // 0xf12b1e59
  SLdrTweakGui_HudColorTypedef ballHud; // 0x58cd6373
  SLdrTweakGuiColors_TurretHudTypedef turretHud; // 0xde139081
};

void LoadTypedefSLdrTweakGuiColors(SLdrTweakGuiColors& data, CInputStream& input);

#endif
