// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRRSFAUDIO_HPP
#define _SLDRRSFAUDIO_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "rstl/string.hpp"

struct SLdrRsfAudio {
  SLdrRsfAudio();
  ~SLdrRsfAudio();

  SLdrEditorProperties editorProperties; // 0x255a4580
  rstl::string unknown_0xfe97e5b3; // 0xfe97e5b3
  int loopStart; // 0x2e596612
  int loopEnd; // 0xd8496dea
  float fadeInTime; // 0x90aa341f
  float fadeOutTime; // 0x7c269ebc
  int volume; // 0x80c66c37
};

inline SLdrRsfAudio::SLdrRsfAudio() : editorProperties(), unknown_0xfe97e5b3() {
  loopStart = 0;
  loopEnd = 0;
  fadeInTime = 0.25f;
  fadeOutTime = 0.25f;
  volume = 127;
}

inline SLdrRsfAudio::~SLdrRsfAudio() {}

#endif
