// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTRYCLOPS_HPP
#define _SLDRTRYCLOPS_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrTryclops {
  SLdrTryclops();
  ~SLdrTryclops();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  float attractForce; // 0xb13fc578
  float attractAngle; // 0x868b85e4
  float attractDistance; // 0x47c6bb1d
  float shotForce; // 0x26087d23
};

void LoadTypedefSLdrTryclops(SLdrTryclops& data, CInputStream& input);

#endif
