// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRINGBLOBSWARM_HPP
#define _SLDRINGBLOBSWARM_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAnimationParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrBasicSwarmProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrIngBlobSwarm {
  SLdrIngBlobSwarm();
  ~SLdrIngBlobSwarm();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrActorParameters actorInformation; // 0x7e397fed
  SLdrAnimationParameters animationInformation; // 0xe25fb08c
  bool active; // 0xc6bb2f45
  SLdrBasicSwarmProperties basicSwarmProperties; // 0xe1ec7346
  int intoAttackAnimation; // 0x7399abbb
  int attackAnimation; // 0x734d923b
  float maxAttackAngle; // 0xf11f7384
  float intoAttackSpeed; // 0xca761dcd
  float attackSpeed; // 0x6c0a2bc8
  float mass; // 0x75dbb375
  float maxAttackHeight; // 0xe1ae51d8
  CVector3f attackAimOffset; // 0x540c1f87
};

void LoadTypedefSLdrIngBlobSwarm(SLdrIngBlobSwarm& data, CInputStream& input);

#endif
