// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSCANTREECATEGORY_HPP
#define _SLDRSCANTREECATEGORY_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "rstl/string.hpp"

struct SLdrScanTreeCategory {
  SLdrScanTreeCategory();
  ~SLdrScanTreeCategory();

  SLdrEditorProperties editorProperties; // 0x255a4580
  CAssetId nodeName; // 0x46219bac
  rstl::string stringName; // 0x32698bd6
};

void LoadTypedefSLdrScanTreeCategory(SLdrScanTreeCategory& data, CInputStream& input);

#endif
