// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCHOZOGHOST_HPP
#define _SLDRCHOZOGHOST_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrGhostBehave {
  SLdrGhostBehave();
  ~SLdrGhostBehave();

  float lurk;         // 0xd3a313a5
  float heckle;       // 0x3cfa69f1
  float attack;       // 0x1af89f4b
  float move;         // 0xe7e66f66
  float lurkTime;     // 0xb9d9c2d2
  float chargeAttack; // 0xcfabdd5f
  int numBolts;       // 0x5ab228b6
};

inline SLdrGhostBehave::SLdrGhostBehave() {
  lurk = -0.0f;
  heckle = 0.0f;
  attack = 0.0f;
  move = 0.0f;
  lurkTime = 0.0f;
  chargeAttack = 0.0f;
  numBolts = 0;
}

inline SLdrGhostBehave::~SLdrGhostBehave() {}

inline void LoadTypedefGhostBehave(SLdrGhostBehave& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.Get< uint >();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0xd3a313a5: {
      sldrThis.lurk = input.ReadFloat();
      break;
    }
    case 0x3cfa69f1: {
      sldrThis.heckle = input.ReadFloat();
      break;
    }
    case 0x1af89f4b: {
      sldrThis.attack = input.ReadFloat();
      break;
    }
    case 0xe7e66f66: {
      sldrThis.move = input.ReadFloat();
      break;
    }
    case 0xb9d9c2d2: {
      sldrThis.lurkTime = input.ReadFloat();
      break;
    }
    case 0xcfabdd5f: {
      sldrThis.chargeAttack = input.ReadFloat();
      break;
    }
    case 0x5ab228b6: {
      sldrThis.numBolts = input.ReadInt32();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}

struct SLdrChozoGhost {
  SLdrChozoGhost();
  ~SLdrChozoGhost();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned;      // 0xb3774750
  SLdrActorParameters actorInformation;  // 0x7e397fed
  float hearingRadius;                   // 0xed69488f
  float fadeOutDelay;                    // 0xfb12f672
  float attackDelay;                     // 0x1b67981a
  float freezeTime;                      // 0x1e8722c7
  CAssetId unknown_0x54151870;           // 0x54151870
  SLdrDamageInfo damageInfo;             // non-matching name, 0xffcda1f8
  CAssetId unknown_0x3a58089c;           // 0x3a58089c
  SLdrDamageInfo damageInfo_0x1ff047a9;  // non-matching name, 0x1ff047a9
  SLdrGhostBehave far;                   // 0xe832241f
  SLdrGhostBehave mid;                   // 0x1e2c8483
  SLdrGhostBehave near;                  // 0x78d76034
  int sound_Impact;                      // 0x1bb16ea5
  float disablePlayerGunTime;            // 0xc87d7ec7
  int sound_PhazeIn;                     // 0x2adcbb2e
  int sound_PhazeOut;                    // 0x58b8ec5d
  int unknown_0xec76940c;                // 0xec76940c
  float projectileStopHomingRange;       // 0x723542bb
  int unknown_0xfe9eac26;                // 0xfe9eac26
  float hurlRecoverTime;                 // 0x96feb75d
  CAssetId projectileVisorEffect;        // 0x8f8c64a0
  int sound_ProjectileVisor;             // 0xe15b4f4a
  float nearToMidDistance;               // 0x61e511b3
  float midToFarDistance;                // 0x2369607a
  int nearChance;                        // 0xa6a3879b
  int midChance;                         // 0x1b272781
};

inline SLdrChozoGhost::SLdrChozoGhost()
: editorProperties()
, patterned()
, actorInformation()
, unknown_0x54151870(kInvalidAssetId)
, damageInfo()
, unknown_0x3a58089c(kInvalidAssetId)
, damageInfo_0x1ff047a9()
, far()
, mid()
, near()
, projectileVisorEffect(kInvalidAssetId) {
  patterned.turnSpeed = 720.0f;
  patterned.detectionRange = 25.0f;
  patterned.minAttackRange = 8.0f;
  patterned.maxAttackRange = 70.0f;
  patterned.leashRadius = 70.0f;
  patterned.contactDamage.dI_WeaponType = 9;
  patterned.contactDamage.dI_Damage = 5.0f;
  patterned.contactDamage.dI_KnockBackPower = 1.0f;
  patterned.health.health = 300.0f;
  patterned.health.hI_KnockBackResistance = 10.0f;
  patterned.collisionHeight = 4.5f;
  patterned.creatureSize = 1;
  hearingRadius = 20.0f;
  fadeOutDelay = 2.5f;
  attackDelay = 1.0f;
  freezeTime = 2.0f;
  damageInfo.dI_Damage = 10.0f;
  damageInfo_0x1ff047a9.dI_Damage = 5.0f;
  far.lurk = 20.0f;
  far.attack = 60.0f;
  far.move = 20.0f;
  far.lurkTime = 2.0f;
  far.numBolts = 1;
  mid.lurk = 20.0f;
  mid.heckle = 10.0f;
  mid.attack = 60.0f;
  mid.move = 10.0f;
  mid.lurkTime = 2.0f;
  mid.chargeAttack = 20.0f;
  mid.numBolts = 3;
  near.attack = 100.0f;
  near.lurkTime = 2.0f;
  near.chargeAttack = 50.0f;
  near.numBolts = 2;
  sound_Impact = 0;
  disablePlayerGunTime = 1.5f;
  sound_PhazeIn = 0;
  sound_PhazeOut = 0;
  unknown_0xec76940c = 0;
  projectileStopHomingRange = 8.0f;
  unknown_0xfe9eac26 = 0;
  hurlRecoverTime = 1.5f;
  sound_ProjectileVisor = 0;
  nearToMidDistance = 20.0f;
  midToFarDistance = 45.0f;
  nearChance = 40;
  midChance = 40;
}

inline SLdrChozoGhost::~SLdrChozoGhost() {}

#endif
