// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRWAYPOINT_HPP
#define _SLDRWAYPOINT_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrWaypoint {
  SLdrWaypoint();
  ~SLdrWaypoint();

  SLdrEditorProperties editorProperties; // 0x255a4580
};

void LoadTypedefSLdrWaypoint(SLdrWaypoint& data, CInputStream& input);

#endif
