// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRBRIZGEE_HPP
#define _SLDRBRIZGEE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrBrizgee {
  SLdrBrizgee();
  ~SLdrBrizgee();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  float waypointApproachDistance; // 0x733bd27c
  float wallTurnSpeed; // 0xac47c628
  float floorTurnSpeed; // 0x8e4f7b29
  float downTurnSpeed; // 0x3d3c1b76
  float visibleDistance; // 0xa72530e8
  float forwardMovingPriority; // 0x5e6a54b8
  CAssetId noShellModel; // 0x07f947f4
  CAssetId noShellSkin; // 0x0b7325ea
  SLdrDamageVulnerability shellVulnerability; // 0xf573e11c
  float shellHealth; // 0xaa13253a
  SLdrDamageInfo shellContactDamage; // 0xb482e5dd
  float shellOffSpeedMultiplier; // 0x80da8053
  SLdrDamageInfo poisonDamage; // 0x143d18c6
  float poisonTime; // 0xf78947d4
  int shellBreakSound; // 0x6a942a60
  int poisonHitSound; // 0x808392ec
  int playerPoisonSound; // 0xdf2d8017
};

void LoadTypedefSLdrBrizgee(SLdrBrizgee& data, CInputStream& input);

#endif
