// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRGRAPPLEPOINT_HPP
#define _SLDRGRAPPLEPOINT_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrGrappleParameters.hpp"

struct SLdrGrapplePoint {
  SLdrGrapplePoint();
  ~SLdrGrapplePoint();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrGrappleParameters grappleInfo; // 0x6a2872d8
};

void LoadTypedefSLdrGrapplePoint(SLdrGrapplePoint& data, CInputStream& input);

#endif
