// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakTargeting.hpp"

SLdrTweakTargeting_Scan::SLdrTweakTargeting_Scan() : scanLockScale(), scanLockTransitionTime(), scanLockTranslation(), scanLockCrossHairColor(), scanLockLockedColor(), scanLockUnlockedColor() {
  scanLockScale = 1.0f;
  scanLockTransitionTime = 0.30000001f;
  scanLockTranslation = 1.0f;
  scanLockCrossHairColor = CColor(0.0f, 0.0f, 0.0f, 1.0f);
  scanLockLockedColor = CColor(0.0f, 0.0f, 0.0f, 1.0f);
  scanLockUnlockedColor = CColor(0.0f, 0.0f, 0.0f, 1.0f);
}

SLdrTweakTargeting_Scan::~SLdrTweakTargeting_Scan() {}

void LoadTypedefSLdrTweakTargeting_Scan(SLdrTweakTargeting_Scan& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.ReadInt32();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0xa0857b6e: {
      sldrThis.scanLockScale = input.ReadFloat();
      break;
    }
    case 0xa4cce30f: {
      sldrThis.scanLockTransitionTime = input.ReadFloat();
      break;
    }
    case 0x8e9bfea3: {
      sldrThis.scanLockTranslation = input.ReadFloat();
      break;
    }
    case 0x768110cd: {
      sldrThis.scanLockCrossHairColor = CColor(input);
      break;
    }
    case 0x319f966b: {
      sldrThis.scanLockLockedColor = CColor(input);
      break;
    }
    case 0xa81f378c: {
      sldrThis.scanLockUnlockedColor = CColor(input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}
