// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakPlayerGun.hpp"

SLdrTweakPlayerGun_Weapons::SLdrTweakPlayerGun_Weapons() : bomb(), unknown_0xe8907530(), bombDropDelayTime(), power_Bomb(), missile(), power_Beam(), dark_Beam(), dark_Beam_Blob(), light_Beam(), annihilator_Beam(), phazon_Beam() {
  bomb.weaponType = 4;
  bomb.radiusDamageAmount = 10.0f;
  bomb.damageRadius = 3.0f;
  unknown_0xe8907530 = 2.0f;
  bombDropDelayTime = 0.60000002f;
  power_Bomb.weaponType = 5;
  power_Bomb.damageAmount = 100.0f;
  power_Bomb.radiusDamageAmount = 50.0f;
  power_Bomb.damageRadius = 10.0f;
  missile.weaponType = 6;
  missile.damageAmount = 30.0f;
  missile.radiusDamageAmount = 15.0f;
  missile.damageRadius = 4.5f;
  missile.knockBackPower = 4.0f;
  power_Beam.delayBetweenShots = 0.111f;
  dark_Beam.delayBetweenShots = 0.30000001f;
  dark_Beam_Blob.weaponType = 1;
  dark_Beam_Blob.damageAmount = 1.0f;
  dark_Beam_Blob.radiusDamageAmount = 0.0f;
  dark_Beam_Blob.damageRadius = 0.0f;
  dark_Beam_Blob.knockBackPower = 0.0f;
  light_Beam.delayBetweenShots = 0.5f;
  annihilator_Beam.delayBetweenShots = 0.33000001f;
  phazon_Beam.delayBetweenShots = 0.1f;
}

SLdrTweakPlayerGun_Weapons::~SLdrTweakPlayerGun_Weapons() {}

void LoadTypedefSLdrTweakPlayerGun_Weapons(SLdrTweakPlayerGun_Weapons& sldrThis, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.ReadInt32();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x6173ad96: {
      LoadTypedefSLdrTDamageInfo(sldrThis.bomb, input);
      break;
    }
    case 0xe8907530: {
      sldrThis.unknown_0xe8907530 = input.ReadFloat();
      break;
    }
    case 0x0a9186cb: {
      sldrThis.bombDropDelayTime = input.ReadFloat();
      break;
    }
    case 0xdcc0c6fb: {
      LoadTypedefSLdrTDamageInfo(sldrThis.power_Bomb, input);
      break;
    }
    case 0x58f00b0a: {
      LoadTypedefSLdrTDamageInfo(sldrThis.missile, input);
      break;
    }
    case 0x1f6c1a6b: {
      LoadTypedefSLdrTBeamInfo(sldrThis.power_Beam, input);
      break;
    }
    case 0xc50f608b: {
      LoadTypedefSLdrTBeamInfo(sldrThis.dark_Beam, input);
      break;
    }
    case 0x059dce11: {
      LoadTypedefSLdrTDamageInfo(sldrThis.dark_Beam_Blob, input);
      break;
    }
    case 0xde7a8255: {
      LoadTypedefSLdrTBeamInfo(sldrThis.light_Beam, input);
      break;
    }
    case 0x74b9b983: {
      LoadTypedefSLdrTBeamInfo(sldrThis.annihilator_Beam, input);
      break;
    }
    case 0xdd5f2e3d: {
      LoadTypedefSLdrTBeamInfo(sldrThis.phazon_Beam, input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}
