// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRECHOPARAMETERS_HPP
#define _SLDRECHOPARAMETERS_HPP

#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrEchoParameters {
  SLdrEchoParameters();
  ~SLdrEchoParameters();

  bool isEchoEmitter; // 0x17addfc6
  bool onlyEmitDamage; // 0xf5df62ad
  int numSoundWaves; // 0xd0073a0c
  float spaceBetweenWaves; // 0xed6d6782
  float waveLineSize; // 0xdb190f68
  float forcedMinimumVis; // 0xf87a15e7
};

void LoadTypedefSLdrEchoParameters(SLdrEchoParameters& data, CInputStream& input);

#endif
