// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRVECTOR2F_HPP
#define _SLDRVECTOR2F_HPP

#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrVector2f {
  SLdrVector2f();
  ~SLdrVector2f();

  float x; // 0xa1677d4e
  float y; // 0x6a3baeeb
};

void LoadTypedefSLdrVector2f(SLdrVector2f& data, CInputStream& input);

#endif
