// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRPLAYERITEM_HPP
#define _SLDRPLAYERITEM_HPP

#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrPlayerItem {
  SLdrPlayerItem();
  ~SLdrPlayerItem();

  int value;
};

void LoadTypedefSLdrPlayerItem(SLdrPlayerItem& data, CInputStream& input);

#endif
