// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTRIGGERINFO_HPP
#define _SLDRTRIGGERINFO_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"

struct SLdrTriggerInfo {
  SLdrTriggerInfo();
  ~SLdrTriggerInfo();

  SLdrDamageInfo damage; // 0x337f9524
  CVector3f forceField; // 0x20927e9b
  uint flagsTrigger; // 0x82859f46
};

void LoadTypedefSLdrTriggerInfo(SLdrTriggerInfo& data, CInputStream& input);

#endif
