// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRPATTERNEDAITYPEDEF_HPP
#define _SLDRPATTERNEDAITYPEDEF_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrAnimationParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageInfo.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEchoParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrHealthInfo.hpp"

struct SLdrPatternedAITypedef {
  SLdrPatternedAITypedef();
  ~SLdrPatternedAITypedef();

  float mass; // 0x75dbb375
  float speed; // 0x6392404e
  float turnSpeed; // 0x020c78bb
  float detectionRange; // 0x8db77ee4
  float detectionHeightRange; // 0x513f04b8
  float detectionAngle; // 0x83dfc40f
  float minAttackRange; // 0x58434916
  float maxAttackRange; // 0xff77c96f
  float averageAttackTime; // 0xb0cfe015
  float attackTimeVariation; // 0xc80e329b
  float leashRadius; // 0x3fae47eb
  float playerLeashRadius; // 0x13f0b18f
  float playerLeashTime; // 0x7d5a0487
  SLdrDamageInfo contactDamage; // 0xd756416e
  float damageWaitTime; // 0xe0cdc7e3
  SLdrHealthInfo health; // 0xcf90d15e
  SLdrDamageVulnerability vulnerability; // 0x7b71ae90
  float collisionRadius; // 0x8a6ab139
  float collisionHeight; // 0x3011b5df
  CVector3f collisionOffset; // 0x2e686c2a
  float stepUpHeight; // 0xd9355674
  float unknown_0xe287d8dd; // 0xe287d8dd
  float unknown_0x66cdc6e8; // 0x66cdc6e8
  float xDamageDelay; // 0x061cbe62
  int sound_XDamage; // 0x19f84380
  SLdrAnimationParameters animationInformation; // 0xe25fb08c
  CAssetId stateMachine; // 0x55744160
  CAssetId stateMachine2; // 0xc1c7e255
  float unknown_0x87d22d43; // 0x87d22d43
  float unknown_0xf0790c1b; // 0xf0790c1b
  float freezeDuration; // 0xef3bd8cf
  int pathMeshIndex; // 0x98169634
  CVector3f gibParticlesOffset; // 0x487ef257
  CAssetId gibParticles; // 0x684f00c9
  CAssetId gibElectricParticles; // 0xf35f5164
  CVector3f iceGibParticlesOffset; // 0x130539a0
  CAssetId iceGibParticles; // 0xa8da9239
  int sound_IceXDamage; // 0x7344d6cd
  int sound_IceXDamageVocal; // 0x562cf323
  int sound_Frozen; // 0xcdd9f41c
  CAssetId knockbackRules; // 0x87011652
  int creatureSize; // 0x4bc4c4d9
  SLdrEchoParameters echoParameters; // 0x4476bed8
};

void LoadTypedefSLdrPatternedAITypedef(SLdrPatternedAITypedef& data, CInputStream& input);

#endif
