// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCOMMAND_HPP
#define _SLDRCOMMAND_HPP

#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrCommand {
  SLdrCommand();
  ~SLdrCommand();

  int command; // 0x94ba5737
};

void LoadTypedefCommand(SLdrCommand& data, CInputStream& input);

#endif
