// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRINGPOSSESSIONDATA_HPP
#define _SLDRINGPOSSESSIONDATA_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrDamageVulnerability.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrHealthInfo.hpp"

struct SLdrIngPossessionData {
  SLdrIngPossessionData();
  ~SLdrIngPossessionData();

  bool isAnEncounter; // 0x888fa435
  bool unknown_0xb68c0aa3; // 0xb68c0aa3
  CAssetId ingPossessedModel; // 0xad54da11
  CAssetId ingPossessedSkinRules; // 0xf5c66384
  CAssetId darkScanInfo; // 0x35a9792e
  SLdrHealthInfo ingPossessedHealth; // 0x1d852d4b
  float ingPossessedDamageMultiplier; // 0x487e4f9a
  int unknown_0x2befc1bf; // 0x2befc1bf
  SLdrDamageVulnerability ingVulnerability; // 0x4aeec093
};

void LoadTypedefSLdrIngPossessionData(SLdrIngPossessionData& data, CInputStream& input);

#endif
