// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef GENERATED_SLDRANIMATIONPARAMETERS_HPP
#define GENERATED_SLDRANIMATIONPARAMETERS_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrAnimationParameters {
  SLdrAnimationParameters() : ancs(kInvalidAssetId), character_index(0), initial_anim(0) {}
  CAssetId ancs;
  int character_index;
  int initial_anim;
};

void LoadTypedefSLdrAnimationParameters(SLdrAnimationParameters&, CInputStream&);

#endif
