// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSCANNABLEPARAMETERS_HPP
#define _SLDRSCANNABLEPARAMETERS_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrScannableParameters {
  SLdrScannableParameters();
  ~SLdrScannableParameters();

  CAssetId scannableInfo0; // 0xb94e9be7
};

void LoadTypedefSLdrScannableParameters(SLdrScannableParameters& data, CInputStream& input);

#endif
