// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRHEALTHINFO_HPP
#define _SLDRHEALTHINFO_HPP

#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrHealthInfo {
  SLdrHealthInfo();
  ~SLdrHealthInfo();

  float health; // 0xf0668919
  float hI_KnockBackResistance; // 0x3a2d17e4
};

void LoadTypedefSLdrHealthInfo(SLdrHealthInfo& data, CInputStream& input);

#endif
