// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRAUDIOPLAYBACKPARMS_HPP
#define _SLDRAUDIOPLAYBACKPARMS_HPP

#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrAudioPlaybackParms {
  SLdrAudioPlaybackParms();
  ~SLdrAudioPlaybackParms();

  float maximumDistance; // 0x0e449f72
  float fallOff; // 0x72531867
  int sound_Id; // 0xaf85a374
  int maxVolume; // 0xc712847c
  int minVolume; // 0x57619496
  bool useRoomAcoustics; // 0x85707354
};

void LoadTypedefSLdrAudioPlaybackParms(SLdrAudioPlaybackParms& data, CInputStream& input);

#endif
