// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCAMERASHAKERDATA_HPP
#define _SLDRCAMERASHAKERDATA_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrCameraShakerData {
  SLdrCameraShakerData();
  ~SLdrCameraShakerData();

  uint flagsCameraShaker; // 0xc3e75c5f
  float attenuationDistance; // 0x4d283ac5
  SLdrSpline horizontalMotion; // 0xf122cd97
  SLdrSpline verticalMotion; // 0x2927e544
  SLdrSpline forwardMotion; // 0x7cfa4678
  float duration; // 0x8b51e23f
  int audioEffect; // 0x388d2e46
};

void LoadTypedefSLdrCameraShakerData(SLdrCameraShakerData& data, CInputStream& input);

#endif
