// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDREDITORPROPERTIES_HPP
#define _SLDREDITORPROPERTIES_HPP

#include "Kyoto/Math/CVector3f.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "rstl/string.hpp"

struct SLdrTransform {
  SLdrTransform();
  ~SLdrTransform();

  CVector3f position; // 0x00000000
  CVector3f rotation; // 0x00000001
  CVector3f scale; // 0x00000002
};

void LoadTypedefSLdrTransform(SLdrTransform& data, CInputStream& input);

struct SLdrEditorProperties {
  SLdrEditorProperties();
  ~SLdrEditorProperties();

  rstl::string name; // 0x494e414d
  SLdrTransform transform; // 0x5846524d
  bool active; // 0x41435456
  uint unknown_0x5d298a43; // 0x5d298a43
};

void LoadTypedefSLdrEditorProperties(SLdrEditorProperties& data, CInputStream& input);

#endif
