// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRGUIWIDGETPROPERTIES_HPP
#define _SLDRGUIWIDGETPROPERTIES_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "rstl/string.hpp"

struct SLdrGuiWidgetProperties {
  SLdrGuiWidgetProperties();
  ~SLdrGuiWidgetProperties();

  rstl::string guiLabel; // 0x73939407
  int controllerNumber; // 0xdb7f4aa2
  bool isLocked; // 0xdee730f5
};

void LoadTypedefSLdrGuiWidgetProperties(SLdrGuiWidgetProperties& data, CInputStream& input);

#endif
