// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCOMMAND_HPP
#define _SLDRCOMMAND_HPP

#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrControllerActionCommand {
  SLdrControllerActionCommand();
  ~SLdrControllerActionCommand();

  int value;
};

void LoadTypedefSLdrControllerActionCommand(SLdrControllerActionCommand& data, CInputStream& input);

struct SLdrCommand {
  SLdrCommand();
  ~SLdrCommand();

  SLdrControllerActionCommand unknown_0x94ba5737; // 0x94ba5737
};

void LoadTypedefSLdrCommand(SLdrCommand& data, CInputStream& input);

#endif
