// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTEXTPROPERTIES_HPP
#define _SLDRTEXTPROPERTIES_HPP

#include "Kyoto/Graphics/CColor.hpp"
#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrTextProperties {
  SLdrTextProperties();
  ~SLdrTextProperties();

  int textBoundingWidth;  // 0xee521dc6
  int textBoundingHeight; // 0xf2d36abb
#if VERSION != VERSION_G2ME01
  float lineSpacing;       // 0x1a996292
  int lineExtraSpace;      // 0x05eff913
  int characterExtraSpace; // 0x45830901
#endif
  CColor foregroundColor;      // 0x3f39e635
  CColor outlineColor;         // 0x60d78569
  CColor geometryColor;        // 0x5908ef39
  CAssetId defaultFont;        // 0x0db9f8b6
  int horizontalJustification; // 0x18dd95cd
  int verticalJustification;   // 0x42091548
  bool wrapText;               // 0x330573e9
#if VERSION != VERSION_G2ME01
  bool drawShadow; // 0xd8a2eef0
#endif
};

void LoadTypedefTextProperties(SLdrTextProperties& data, CInputStream& input);

#endif
