// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakPlayerGun.hpp"

SLdrTweakPlayerGun::SLdrTweakPlayerGun() : instanceName(), misc(), holstering(), position(), arm_Position(), weapons(), beam_Combo(), beam_Misc(), ricochetDamage_Factor(), recoil(), comboRecoil(), projectileRecoil(), flameThrower(), waveBuster(), projectileImpact() {
  projectileImpact.flagsCameraShaker = 0x00000013u;
}

SLdrTweakPlayerGun::~SLdrTweakPlayerGun() {}

void LoadTypedefSLdrTweakPlayerGun(SLdrTweakPlayerGun& data, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.ReadInt32();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x7fda1466: {
      data.instanceName = rstl::string(input);
      break;
    }
    case 0xb82ed424: {
      LoadTypedefSLdrTweakPlayerGun_Misc(data.misc, input);
      break;
    }
    case 0x6b6bdc47: {
      LoadTypedefSLdrTweakPlayerGun_Holstering(data.holstering, input);
      break;
    }
    case 0x87882cb0: {
      LoadTypedefSLdrTweakPlayerGun_Position(data.position, input);
      break;
    }
    case 0x255007ad: {
      LoadTypedefSLdrTweakPlayerGun_Arm_Position(data.arm_Position, input);
      break;
    }
    case 0x83d758ab: {
      LoadTypedefSLdrTweakPlayerGun_Weapons(data.weapons, input);
      break;
    }
    case 0x888c8775: {
      LoadTypedefSLdrTweakPlayerGun_Beam_Combo(data.beam_Combo, input);
      break;
    }
    case 0xaaebb73e: {
      LoadTypedefSLdrTweakPlayerGun_Beam_Misc(data.beam_Misc, input);
      break;
    }
    case 0x8da058fe: {
      LoadTypedefSLdrTweakPlayerGun_RicochetDamage_Factor(data.ricochetDamage_Factor, input);
      break;
    }
    case 0xffdb4bb7: {
      LoadTypedefSLdrCameraShakerData(data.recoil, input);
      break;
    }
    case 0x937a35bd: {
      LoadTypedefSLdrCameraShakerData(data.comboRecoil, input);
      break;
    }
    case 0x26196738: {
      LoadTypedefSLdrCameraShakerData(data.projectileRecoil, input);
      break;
    }
    case 0xf40808c9: {
      LoadTypedefSLdrCameraShakerData(data.flameThrower, input);
      break;
    }
    case 0x9a6d7a31: {
      LoadTypedefSLdrCameraShakerData(data.waveBuster, input);
      break;
    }
    case 0x12f14c5a: {
      LoadTypedefSLdrCameraShakerData(data.projectileImpact, input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}
