// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakGuiColors.hpp"

SLdrTweakGuiColors::SLdrTweakGuiColors() : instanceName(), hUDColors(), misc(), multiplayer(), combatHudColorScheme(), echoHudColorScheme(), scanHudColorScheme(), darkHudColorScheme(), ballHudColorScheme(), combatHud(), scanHud(), xRayHud(), thermalHud(), ballHud(), turretHud() {
}

SLdrTweakGuiColors::~SLdrTweakGuiColors() {}

void LoadTypedefSLdrTweakGuiColors(SLdrTweakGuiColors& data, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.ReadInt32();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x7fda1466: {
      data.instanceName = rstl::string(input);
      break;
    }
    case 0xcb737724: {
      LoadTypedefSLdrTweakGuiColors_HUDColorsTypedef(data.hUDColors, input);
      break;
    }
    case 0x6756d4de: {
      LoadTypedefSLdrTweakGuiColors_Misc(data.misc, input);
      break;
    }
    case 0x697613e9: {
      LoadTypedefSLdrTweakGuiColors_Multiplayer(data.multiplayer, input);
      break;
    }
    case 0x67c70055: {
      LoadTypedefSLdrTweakGui_VisorColorSchemeTypedef(data.combatHudColorScheme, input);
      break;
    }
    case 0x62e0a08f: {
      LoadTypedefSLdrTweakGui_VisorColorSchemeTypedef(data.echoHudColorScheme, input);
      break;
    }
    case 0x80becd6e: {
      LoadTypedefSLdrTweakGui_VisorColorSchemeTypedef(data.scanHudColorScheme, input);
      break;
    }
    case 0x7de4b297: {
      LoadTypedefSLdrTweakGui_VisorColorSchemeTypedef(data.darkHudColorScheme, input);
      break;
    }
    case 0xc0181762: {
      LoadTypedefSLdrTweakGui_VisorColorSchemeTypedef(data.ballHudColorScheme, input);
      break;
    }
    case 0x45d7a40f: {
      LoadTypedefSLdrTweakGui_HudColorTypedef(data.combatHud, input);
      break;
    }
    case 0x594b44cf: {
      LoadTypedefSLdrTweakGui_HudColorTypedef(data.scanHud, input);
      break;
    }
    case 0x8f5ebeb9: {
      LoadTypedefSLdrTweakGui_HudColorTypedef(data.xRayHud, input);
      break;
    }
    case 0xf12b1e59: {
      LoadTypedefSLdrTweakGui_HudColorTypedef(data.thermalHud, input);
      break;
    }
    case 0x58cd6373: {
      LoadTypedefSLdrTweakGui_HudColorTypedef(data.ballHud, input);
      break;
    }
    case 0xde139081: {
      LoadTypedefSLdrTweakGuiColors_TurretHudTypedef(data.turretHud, input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}
