// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakGame.hpp"

SLdrTweakGame::SLdrTweakGame() : instanceName(), pakFile(), asset(), fieldofView(), fieldofView2Player(), disableDebugMenu(), musicOnByDefault(), developmentMode(), frontEndAudioVolume(), unknown_0xb35c72be(), unknown_0x4a02103c(), unknown_0xe1fca71b(), unknown_0xfbce966a(), unknown_0x09c6ca10(), hardModeDamageMultiplier(), hardModeWeaponMultiplier(), safeZoneActivationTime(), safeZoneDeactivationTime(), maxPercentageInventoryItems(), unknown_0x1d627808(), unknown_0xb2e8828d(), unknown_0x06af87bd(), unknown_0x1533ea4e(), unknown_0x40818220() {
  fieldofView = 55.0f;
  fieldofView2Player = 45.0f;
  disableDebugMenu = false;
  musicOnByDefault = true;
  developmentMode = true;
  frontEndAudioVolume = 25.0f;
  unknown_0xb35c72be = 1.0f;
  unknown_0x4a02103c = 30.0f;
  unknown_0xe1fca71b = 125.0f;
  unknown_0xfbce966a = 150.0f;
  unknown_0x09c6ca10 = 300.0f;
  hardModeDamageMultiplier = 1.53f;
  hardModeWeaponMultiplier = 0.5f;
  safeZoneActivationTime = 0.15000001f;
  safeZoneDeactivationTime = 0.15000001f;
  maxPercentageInventoryItems = 102;
}

SLdrTweakGame::~SLdrTweakGame() {}

void LoadTypedefSLdrTweakGame(SLdrTweakGame& data, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.ReadInt32();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x7fda1466: {
      data.instanceName = rstl::string(input);
      break;
    }
    case 0x2bd13ab3: {
      data.pakFile = rstl::string(input);
      break;
    }
    case 0xf8be005a: {
      data.asset = rstl::string(input);
      break;
    }
    case 0xfc93ceb8: {
      data.fieldofView = input.ReadFloat();
      break;
    }
    case 0x9fb2faa6: {
      data.fieldofView2Player = input.ReadFloat();
      break;
    }
    case 0xa9096914: {
      data.disableDebugMenu = input.ReadBool();
      break;
    }
    case 0x7262d27b: {
      data.musicOnByDefault = input.ReadBool();
      break;
    }
    case 0xe943ba12: {
      data.developmentMode = input.ReadBool();
      break;
    }
    case 0xa3dcf42a: {
      data.frontEndAudioVolume = input.ReadFloat();
      break;
    }
    case 0xb35c72be: {
      data.unknown_0xb35c72be = input.ReadFloat();
      break;
    }
    case 0x4a02103c: {
      data.unknown_0x4a02103c = input.ReadFloat();
      break;
    }
    case 0xe1fca71b: {
      data.unknown_0xe1fca71b = input.ReadFloat();
      break;
    }
    case 0xfbce966a: {
      data.unknown_0xfbce966a = input.ReadFloat();
      break;
    }
    case 0x09c6ca10: {
      data.unknown_0x09c6ca10 = input.ReadFloat();
      break;
    }
    case 0x4dfcd432: {
      data.hardModeDamageMultiplier = input.ReadFloat();
      break;
    }
    case 0xae1831d9: {
      data.hardModeWeaponMultiplier = input.ReadFloat();
      break;
    }
    case 0x5ab5812c: {
      data.safeZoneActivationTime = input.ReadFloat();
      break;
    }
    case 0x53401390: {
      data.safeZoneDeactivationTime = input.ReadFloat();
      break;
    }
    case 0xd09f373b: {
      data.maxPercentageInventoryItems = input.ReadInt32();
      break;
    }
    case 0x1d627808: {
      LoadTypedefSLdrTweakGame_FragLimitChoices(data.unknown_0x1d627808, input);
      break;
    }
    case 0xb2e8828d: {
      LoadTypedefSLdrTweakGame_TimeLimitChoices(data.unknown_0xb2e8828d, input);
      break;
    }
    case 0x06af87bd: {
      LoadTypedefSLdrTweakGame_CoinLimitChoices(data.unknown_0x06af87bd, input);
      break;
    }
    case 0x1533ea4e: {
      LoadTypedefSLdrTweakGame_TimeLimitChoices(data.unknown_0x1533ea4e, input);
      break;
    }
    case 0x40818220: {
      data.unknown_0x40818220 = SLdrSpline(input, propertySize);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}
