// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakPlayerRes.hpp"

SLdrTweakPlayerRes::SLdrTweakPlayerRes() : instanceName(), autoMapperIcons(), mapScreenIcons(), ballTransitionResources(), cinematicResources(), unknown_0x36ad9d19() {
  unknown_0x36ad9d19 = -0.0f;
}

SLdrTweakPlayerRes::~SLdrTweakPlayerRes() {}

void LoadTypedefSLdrTweakPlayerRes(SLdrTweakPlayerRes& data, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.ReadInt32();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x7fda1466: {
      data.instanceName = rstl::string(input);
      break;
    }
    case 0x357741e0: {
      LoadTypedefSLdrTweakPlayerRes_AutoMapperIcons(data.autoMapperIcons, input);
      break;
    }
    case 0x0d5e02a0: {
      LoadTypedefSLdrTweakPlayerRes_MapScreenIcons(data.mapScreenIcons, input);
      break;
    }
    case 0x279852ba: {
      LoadTypedefSLdrTBallTransitionResources(data.ballTransitionResources, input);
      break;
    }
    case 0x5e630608: {
      LoadTypedefSLdrTGunResources(data.cinematicResources, input);
      break;
    }
    case 0x36ad9d19: {
      data.unknown_0x36ad9d19 = input.ReadFloat();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}
