// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakCameraBob.hpp"

SLdrTweakCameraBob::SLdrTweakCameraBob() : instanceName(), cameraBobExtentX(), cameraBobExtentY(), cameraBobPeriod(), orbitBobScale(), maxOrbitBobScale(), slowSpeedPeriodScale(), targetMagnitudeTrackingRate(), landingBobSpringConstant(), viewWanderRadius(), viewWanderSpeedMin(), viewWanderSpeedMax(), viewWanderRollVariation(), gunBobMagnitude(), helmetBobMagnitude() {
  cameraBobExtentX = 0.07f;
  cameraBobExtentY = 0.14f;
  cameraBobPeriod = 0.38999999f;
  orbitBobScale = 0.76999998f;
  maxOrbitBobScale = 0.80000001f;
  slowSpeedPeriodScale = 0.30000001f;
  targetMagnitudeTrackingRate = 0.1f;
  landingBobSpringConstant = 150.0f;
  viewWanderRadius = 0.1f;
  viewWanderSpeedMin = 0.1f;
  viewWanderSpeedMax = 0.40000001f;
  viewWanderRollVariation = 0.30000001f;
  gunBobMagnitude = 0.22f;
  helmetBobMagnitude = 1.0f;
}

SLdrTweakCameraBob::~SLdrTweakCameraBob() {}

void LoadTypedefSLdrTweakCameraBob(SLdrTweakCameraBob& data, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.ReadInt32();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x7fda1466: {
      data.instanceName = rstl::string(input);
      break;
    }
    case 0xe2a0b6f1: {
      data.cameraBobExtentX = input.ReadFloat();
      break;
    }
    case 0x29fc6554: {
      data.cameraBobExtentY = input.ReadFloat();
      break;
    }
    case 0x149d7339: {
      data.cameraBobPeriod = input.ReadFloat();
      break;
    }
    case 0xa27bb5a7: {
      data.orbitBobScale = input.ReadFloat();
      break;
    }
    case 0xe3580b2b: {
      data.maxOrbitBobScale = input.ReadFloat();
      break;
    }
    case 0xb05dade7: {
      data.slowSpeedPeriodScale = input.ReadFloat();
      break;
    }
    case 0x6dc5d440: {
      data.targetMagnitudeTrackingRate = input.ReadFloat();
      break;
    }
    case 0xd16539a7: {
      data.landingBobSpringConstant = input.ReadFloat();
      break;
    }
    case 0xadbb0a42: {
      data.viewWanderRadius = input.ReadFloat();
      break;
    }
    case 0xe7f8f11b: {
      data.viewWanderSpeedMin = input.ReadFloat();
      break;
    }
    case 0x01985efa: {
      data.viewWanderSpeedMax = input.ReadFloat();
      break;
    }
    case 0xef19ba33: {
      data.viewWanderRollVariation = input.ReadFloat();
      break;
    }
    case 0x7f59be96: {
      data.gunBobMagnitude = input.ReadFloat();
      break;
    }
    case 0x38a82ac1: {
      data.helmetBobMagnitude = input.ReadFloat();
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}
