// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakSlideShow.hpp"

SLdrTweakSlideShow::SLdrTweakSlideShow() : instanceName(), pakFile(), font(), fontColor(), fontOutlineColor(), unknown_0xd398dac2(), unknown_0x03757d08(), translationMultiplier(), scaleMultiplier(), slideShowDelay(), helpFrameColor(), helpTransitionTime(), slideBlendTime(), slideNumberHideDelay(), slideNumberTransitionTime(), fadeInTime(), fadeOutTime(), stringResName() {
  fontColor = CColor(0.0f, 0.0f, 0.0f, 1.0f);
  fontOutlineColor = CColor(0.0f, 0.0f, 0.0f, 1.0f);
  unknown_0xd398dac2 = 50.0f;
  unknown_0x03757d08 = 50.0f;
  translationMultiplier = 10.0f;
  scaleMultiplier = 10.0f;
  slideShowDelay = 3.0f;
  helpFrameColor = CColor(0.0f, 0.0f, 0.0f, 1.0f);
  helpTransitionTime = 1.0f;
  slideBlendTime = 0.5f;
  slideNumberHideDelay = 3.0f;
  slideNumberTransitionTime = 0.5f;
  fadeInTime = 0.001f;
  fadeOutTime = 2.0f;
}

SLdrTweakSlideShow::~SLdrTweakSlideShow() {}

void LoadTypedefSLdrTweakSlideShow(SLdrTweakSlideShow& data, CInputStream& input) {
  const int propertyCount = input.ReadUint16();
  for (int i = 0; i < propertyCount; ++i) {
    const uint propertyId = input.ReadInt32();
    const u16 propertySize = input.ReadUint16();
    switch (propertyId) {
    case 0x7fda1466: {
      data.instanceName = rstl::string(input);
      break;
    }
    case 0x2bd13ab3: {
      data.pakFile = rstl::string(input);
      break;
    }
    case 0xfe31fba0: {
      data.font = rstl::string(input);
      break;
    }
    case 0x1a96ec67: {
      data.fontColor = CColor(input);
      break;
    }
    case 0x844ab6b0: {
      data.fontOutlineColor = CColor(input);
      break;
    }
    case 0xd398dac2: {
      data.unknown_0xd398dac2 = input.ReadFloat();
      break;
    }
    case 0x03757d08: {
      data.unknown_0x03757d08 = input.ReadFloat();
      break;
    }
    case 0x59276e14: {
      data.translationMultiplier = input.ReadFloat();
      break;
    }
    case 0x3ce7a013: {
      data.scaleMultiplier = input.ReadFloat();
      break;
    }
    case 0x278c0893: {
      data.slideShowDelay = input.ReadFloat();
      break;
    }
    case 0xd75d29f8: {
      data.helpFrameColor = CColor(input);
      break;
    }
    case 0x27515c7b: {
      data.helpTransitionTime = input.ReadFloat();
      break;
    }
    case 0xae47dc81: {
      data.slideBlendTime = input.ReadFloat();
      break;
    }
    case 0x029d2082: {
      data.slideNumberHideDelay = input.ReadFloat();
      break;
    }
    case 0xb187cd9b: {
      data.slideNumberTransitionTime = input.ReadFloat();
      break;
    }
    case 0x90aa341f: {
      data.fadeInTime = input.ReadFloat();
      break;
    }
    case 0x7c269ebc: {
      data.fadeOutTime = input.ReadFloat();
      break;
    }
    case 0xc0544bc1: {
      data.stringResName = rstl::string(input);
      break;
    }
    default:
      input.ReadBytes(nullptr, propertySize);
      break;
    }
  }
}
