#ifndef MUSYX_GROUP_CINELUMINOTHENCOUNTER3_H
#define MUSYX_GROUP_CINELUMINOTHENCOUNTER3_H

#define GRPCineLuminothEncounter3 0x01EB

#define SFXspt_b_voxidleholo_01_oneshot 0x02F4
#define SFXspt_b_voxidleholo_01_looped 0x02F6
#define SFXspt_b_voxidleholo_02_looped 0x02F7

#endif
