#ifndef MUSYX_GROUP_CINELUMINOTHENCOUNTER1_H
#define MUSYX_GROUP_CINELUMINOTHENCOUNTER1_H

#define GRPCineLuminothEncounter1 0x01ED

#define SFXlum_c_athrshift_00_oneshot 0x02E3
#define SFXlum_c_meteor_00_oneshot 0x02E4
#define SFXlum_c_athrsplit_00_oneshot 0x02E6

#endif
