#ifndef MUSYX_GROUP_CINEDARKCREATUREENCOUNTER2_H
#define MUSYX_GROUP_CINEDARKCREATUREENCOUNTER2_H

#define GRPCineDarkCreatureEncounter2 0x024A

#define SFXdce_c_samdraw_00_oneshot 0x032C
#define SFXdce_c_samturn_00_oneshot 0x032F
#define SFXlum_c_samdraw_00_oneshot 0x056F

#endif
