#ifndef MUSYX_GROUP_CINELUMINOTHENCOUNTER2_H
#define MUSYX_GROUP_CINELUMINOTHENCOUNTER2_H

#define GRPCineLuminothEncounter2 0x01EC

#define SFXlum_c_ingvoxidle_00_oneshot 0x02DC
#define SFXlum_c_ingvoxidle_01_oneshot 0x02DD
#define SFXlum_c_ingvoxidle_02_oneshot 0x02EB
#define SFXlum_c_generatorkey_lp_00_looped 0x02E5

#endif
