#ifndef MUSYX_GROUP_CLIFFSIDEELITELUMACTIVATE_H
#define MUSYX_GROUP_CLIFFSIDEELITELUMACTIVATE_H

#define GRPCliffsideEliteLumActivate 0x0165

#define SFXclf_x_elugas_00_oneshot 0x0481
#define SFXclf_x_eluhood_00_oneshot 0x0482
#define SFXclf_x_eluservo_lp_00_looped 0x0483

#endif
