#ifndef MUSYX_GROUP_CLIFFSIDEDARKVISORPLATFORM_H
#define MUSYX_GROUP_CLIFFSIDEDARKVISORPLATFORM_H

#define GRPCliffsideDarkVisorPlatform 0x016A

#define SFXclf_x_darkvisplat_lp_00_looped 0x057F

#endif
