#ifndef MUSYX_GROUP_COMMANDOPIRATEVOX_H
#define MUSYX_GROUP_COMMANDOPIRATEVOX_H

#define GRPCommandoPirateVox 0x00BE

#define SFXcpr_a_voxattack_00_oneshot 0x1E77
#define SFXcpr_b_voxalert_00_oneshot 0x1E78
#define SFXcpr_b_voxidle_00_oneshot 0x1E7B
#define SFXcpr_b_voxidle_01_oneshot 0x1E7C
#define SFXcpr_a_voxattack_01_oneshot 0x1ECA
#define SFXcpr_a_voxattack_02_oneshot 0x1EEE

#endif
