#ifndef MUSYX_GROUP_COMMANDOPIRATELIGHT4_H
#define MUSYX_GROUP_COMMANDOPIRATELIGHT4_H

#define GRPCommandoPirateLight4 0x0127

#define SFXcpr_b_flicker_00_oneshot 0x1EF8
#define SFXcpr_b_cloak_00_oneshot 0x1ECB
#define SFXcpr_b_decloak_00_oneshot 0x1ECC
#define SFXcpr_b_voxcloak_00_oneshot 0x1ECF
#define SFXcpr_b_voxdecloak_00_oneshot 0x1ED0

#endif
