#ifndef MUSYX_GROUP_DARKSAMUSCHANCEMEETING_H
#define MUSYX_GROUP_DARKSAMUSCHANCEMEETING_H

#define GRPDarkSamusChanceMeeting 0x006C

#define SFXdks_c_08suckin_00_oneshot 0x031A
#define SFXdks_c_bluedeth_lp_00_looped 0x04A8

#endif
