#ifndef MUSYX_GROUP_DIGITALGUARDIANDEATH_H
#define MUSYX_GROUP_DIGITALGUARDIANDEATH_H

#define GRPDigitalGuardianDeath 0x005F

#define SFXdgd_c_headbounce_00_oneshot 0x02AD
#define SFXdgd_c_samland_00_oneshot 0x0447
#define SFXdgd_c_samscrewout_00_oneshot 0x0448

#endif
