#ifndef MUSYX_GROUP_ELITELUMINOTHSHIELD_H
#define MUSYX_GROUP_ELITELUMINOTHSHIELD_H

#define GRPEliteLuminothShield 0x0075

#define SFXelu_b_litshield_lp_00_looped 0x0533
#define SFXrez_b_elulitshield_lp_00_looped 0x0516

#endif
