#ifndef MUSYX_GROUP_GFMETALSCRAPESMRATTLE_H
#define MUSYX_GROUP_GFMETALSCRAPESMRATTLE_H

#define GRPGFMetalScrapeSmRattle 0x014F

#define SFXgft_x_mtlscrapesmrattle_lp_00_looped 0x0370
#define SFXtem_x_02gondola_lp_00_looped 0x0127
#define SFXclf_x_0gspindoor_lp_00_looped 0x0443

#endif
