#ifndef MUSYX_GROUP_GFMETALSCRAPEMEDRATCHET_H
#define MUSYX_GROUP_GFMETALSCRAPEMEDRATCHET_H

#define GRPGFMetalScrapeMedRatchet 0x014E

#define SFXgft_x_mtlscrapemedratch_lp_00_looped 0x036F
#define SFXtem_x_gfelev_lp_looped 0x0115

#endif
