#ifndef MUSYX_GROUP_LUMINOTHMETALHITBIGDULL_H
#define MUSYX_GROUP_LUMINOTHMETALHITBIGDULL_H

#define GRPLuminothMetalHitBigDull 0x01C7

#define SFXlth_x_mtlhitbigdull_00_oneshot 0x0373
#define SFXsb1_c_mtlhitbigdull_00_oneshot 0x04FC

#endif
