#ifndef MUSYX_GROUP_LUMINOTHMETALHITSMALL_H
#define MUSYX_GROUP_LUMINOTHMETALHITSMALL_H

#define GRPLuminothMetalHitSmall 0x01CB

#define SFXlth_x_mtlhitsm_00_oneshot 0x0386
#define SFXsw2_x_10spinstop_00_oneshot 0x03FC
#define SFXclf_x_05spinstop_00_oneshot 0x045B

#endif
