#ifndef MUSYX_GROUP_LUMINOTHMETALSCRAPEBIGRATCHET_H
#define MUSYX_GROUP_LUMINOTHMETALSCRAPEBIGRATCHET_H

#define GRPLuminothMetalScrapeBigRatchet 0x01CD

#define SFXlth_x_mtlscrapebigratch_lp_00_looped 0x0379
#define SFXlth_x_translower_lp_00_looped 0x02D0
#define SFXlth_x_metalblk_lp_00_looped 0x0219
#define SFXswp_x_03bridge_lp_00_looped 0x02D1
#define SFXsn2_x_0opuzzle_lp_00_looped 0x0158

#endif
