#ifndef MUSYX_GROUP_LUMINOTHMETALHITMEDRATCHET_H
#define MUSYX_GROUP_LUMINOTHMETALHITMEDRATCHET_H

#define GRPLuminothMetalHitMedRatchet 0x01CA

#define SFXlth_x_mtlhitmedratch_00_oneshot 0x0385

#endif
