#ifndef MUSYX_GROUP_LUMINOTHMETALSCRAPEMED_H
#define MUSYX_GROUP_LUMINOTHMETALSCRAPEMED_H

#define GRPLuminothMetalScrapeMed 0x01CF

#define SFXlth_x_mtlscrapemed_lp_00_looped 0x037B
#define SFXtem_x_floormove_lp_00_looped 0x005F
#define SFXclf_x_05spin_lp_00_looped 0x045A

#endif
