#ifndef MUSYX_GROUP_LUMINOTHMETALSCRAPEBIGRATCHET2_H
#define MUSYX_GROUP_LUMINOTHMETALSCRAPEBIGRATCHET2_H

#define GRPLuminothMetalScrapeBigRatchet2 0x01CE

#define SFXlth_x_mtlscrapebigratch_lp_01_looped 0x037A
#define SFXlth_x_skrdoor_lp_00_looped 0x0064

#endif
