#ifndef MUSYX_GROUP_LUMINOTHMETALSERVOMED_H
#define MUSYX_GROUP_LUMINOTHMETALSERVOMED_H

#define GRPLuminothMetalServoMed 0x01D0

#define SFXlth_x_mtlservomed_lp_00_looped 0x0388
#define SFXsw2_x_10spinner_lp_00_looped 0x03FF
#define SFXcnt_b_floormove_lp_00_looped 0x05BF

#endif
