#ifndef MUSYX_GROUP_LUMINOTHMETALHITBIGRATTLE_H
#define MUSYX_GROUP_LUMINOTHMETALHITBIGRATTLE_H

#define GRPLuminothMetalHitBigRattle 0x01C8

#define SFXlth_x_mtlhitbigrattle_00_oneshot 0x0374
#define SFXlth_x_transstop_00_oneshot 0x00FB
#define SFXsn2_x_0opuzzlestop_00_oneshot 0x015A
#define SFXswp_x_0opistonstop_00_oneshot 0x0480
#define SFXsb1_c_mtlhitbigrattle_00_oneshot 0x04FD

#endif
