#ifndef MUSYX_GROUP_ONEMINUTEMUSIC_MP_H
#define MUSYX_GROUP_ONEMINUTEMUSIC_MP_H

#define GRPOneMinuteMusic_MP 0x0278

#define SFXmulti_defbgm_speed_doon32L_oneshot 0x050D
#define SFXmulti_defbgm_speed_doon32R_oneshot 0x050E

#endif
