#ifndef MUSYX_GROUP_SPACEPIRATEVOX_H
#define MUSYX_GROUP_SPACEPIRATEVOX_H

#define GRPSpacePirateVox 0x00D6

#define SFXspr_b_voxaffirm_00_oneshot 0x1DCC
#define SFXspr_b_voxangry_01_oneshot 0x1DD3
#define SFXspr_b_voxidle_00_oneshot 0x1DCE
#define SFXspr_b_voxidle_01_oneshot 0x1DCF
#define SFXspr_b_voxidle_02_oneshot 0x1DD0
#define SFXspr_b_voxangry_00_oneshot 0x022D
#define SFXspr_b_voxidle_03_oneshot 0x1DD1
#define SFXspr_b_voxalert_00_oneshot 0x026C
#define SFXspr_b_voxattack_00_oneshot 0x1DD4
#define SFXspr_b_voxidle_04_oneshot 0x1DD5

#endif
