object: orig/G2MJ01/sys/main.dol
splits: config/G2MJ01/splits.txt
symbols: config/G2MJ01/symbols.txt
auto_force_files: false
modules:
  - object: orig/G2MJ01/files/RelProd/AIMannedTurret.rel
  - object: orig/G2MJ01/files/RelProd/AtomicAlpha.rel
  - object: orig/G2MJ01/files/RelProd/AtomicBeta.rel
  - object: orig/G2MJ01/files/RelProd/BacteriaSwarm.rel
  - object: orig/G2MJ01/files/RelProd/Blogg.rel
  - object: orig/G2MJ01/files/RelProd/ChozoGhost.rel
  - object: orig/G2MJ01/files/RelProd/CommandoPirate.rel
  - object: orig/G2MJ01/files/RelProd/DarkCommando.rel
  - object: orig/G2MJ01/files/RelProd/DarkSamus.rel
  - object: orig/G2MJ01/files/RelProd/DarkSamusBattleStage.rel
  - object: orig/G2MJ01/files/RelProd/DarkTrooper.rel
  - object: orig/G2MJ01/files/RelProd/DestructibleBarrier.rel
  - object: orig/G2MJ01/files/RelProd/DigitalGuardian.rel
  - object: orig/G2MJ01/files/RelProd/ElitePirate.rel
  - object: orig/G2MJ01/files/RelProd/EmperorIngStage1.rel
  - object: orig/G2MJ01/files/RelProd/EmperorIngStage2Tentacle.rel
  - object: orig/G2MJ01/files/RelProd/EmperorIngStage3.rel
  - object: orig/G2MJ01/files/RelProd/EyeBall.rel
  - object: orig/G2MJ01/files/RelProd/FishCloud.rel
  - object: orig/G2MJ01/files/RelProd/FlyerSwarm.rel
  - object: orig/G2MJ01/files/RelProd/FlyingPirate.rel
  - object: orig/G2MJ01/files/RelProd/FogOverlay.rel
  - object: orig/G2MJ01/files/RelProd/ForgottenObject.rel
  - object: orig/G2MJ01/files/RelProd/GeomBlobV2.rel
  - object: orig/G2MJ01/files/RelProd/Glowbug.rel
  - object: orig/G2MJ01/files/RelProd/Grenchler.rel
  - object: orig/G2MJ01/files/RelProd/GunTurret.rel
  - object: orig/G2MJ01/files/RelProd/Ing.rel
  - object: orig/G2MJ01/files/RelProd/IngBlobSwarm.rel
  - object: orig/G2MJ01/files/RelProd/IngBoostBallGuardian.rel
  - object: orig/G2MJ01/files/RelProd/IngPuddle.rel
  - object: orig/G2MJ01/files/RelProd/IngSnatchingSwarm.rel
  - object: orig/G2MJ01/files/RelProd/IngSpaceJumpGuardian.rel
  - object: orig/G2MJ01/files/RelProd/IngSpiderballGuardian.rel
  - object: orig/G2MJ01/files/RelProd/IngSwarm.rel
  - object: orig/G2MJ01/files/RelProd/Kralee.rel
  - object: orig/G2MJ01/files/RelProd/Krocuss.rel
  - object: orig/G2MJ01/files/RelProd/Lumite.rel
  - object: orig/G2MJ01/files/RelProd/MediumIng.rel
  - object: orig/G2MJ01/files/RelProd/Metaree.rel
  - object: orig/G2MJ01/files/RelProd/MetareeSwarm.rel
  - object: orig/G2MJ01/files/RelProd/Metroid.rel
  - object: orig/G2MJ01/files/RelProd/MinorIng.rel
  - object: orig/G2MJ01/files/RelProd/MysteryFlyer.rel
  - object: orig/G2MJ01/files/RelProd/OctapedeSegment.rel
  - object: orig/G2MJ01/files/RelProd/Parasite.rel
  - object: orig/G2MJ01/files/RelProd/PillBug.rel
  - object: orig/G2MJ01/files/RelProd/PirateRagDoll.rel
  - object: orig/G2MJ01/files/RelProd/PlantScarabSwarm.rel
  - object: orig/G2MJ01/files/RelProd/PuddleSpore.rel
  - object: orig/G2MJ01/files/RelProd/Puffer.rel
  - object: orig/G2MJ01/files/RelProd/Rezbit.rel
  - object: orig/G2MJ01/files/RelProd/Ripper.rel
  - object: orig/G2MJ01/files/RelProd/RubiksPuzzle.rel
  - object: orig/G2MJ01/files/RelProd/SandBoss.rel
  - object: orig/G2MJ01/files/RelProd/Sandworm.rel
  - object: orig/G2MJ01/files/RelProd/ScriptCannonBall.rel
  - object: orig/G2MJ01/files/RelProd/ScriptCoin.rel
  - object: orig/G2MJ01/files/RelProd/ScriptFrontEndDataNetwork.rel
  - object: orig/G2MJ01/files/RelProd/ScriptGui.rel
  - object: orig/G2MJ01/files/RelProd/ScriptPlayerActor.rel
  - object: orig/G2MJ01/files/RelProd/ScriptPlayerProxy.rel
  - object: orig/G2MJ01/files/RelProd/ScriptPlayerTurret.rel
  - object: orig/G2MJ01/files/RelProd/ScriptRiftPortal.rel
  - object: orig/G2MJ01/files/RelProd/ScriptRsfAudio.rel
  - object: orig/G2MJ01/files/RelProd/ScriptSafeZone.rel
  - object: orig/G2MJ01/files/RelProd/ScriptStreamedMovie.rel
  - object: orig/G2MJ01/files/RelProd/Shredder.rel
  - object: orig/G2MJ01/files/RelProd/Shrieker.rel
  - object: orig/G2MJ01/files/RelProd/SkyRipple.rel
  - object: orig/G2MJ01/files/RelProd/SnakeWeedSwarm.rel
  - object: orig/G2MJ01/files/RelProd/SpacePirate.rel
  - object: orig/G2MJ01/files/RelProd/SpankWeed.rel
  - object: orig/G2MJ01/files/RelProd/Splinter.rel
  - object: orig/G2MJ01/files/RelProd/Splitter.rel
  - object: orig/G2MJ01/files/RelProd/Sporb.rel
  - object: orig/G2MJ01/files/RelProd/StoneToad.rel
  - object: orig/G2MJ01/files/RelProd/SwampBossStage1.rel
  - object: orig/G2MJ01/files/RelProd/SwampBossStage2.rel
  - object: orig/G2MJ01/files/RelProd/SwarmBasics.rel
  - object: orig/G2MJ01/files/RelProd/Tryclops.rel
  - object: orig/G2MJ01/files/RelProd/Tweaks.rel
  - object: orig/G2MJ01/files/RelProd/WallCrawler.rel
  - object: orig/G2MJ01/files/RelProd/WallCrawlerSwarm.rel
  - object: orig/G2MJ01/files/RelProd/WallWalker.rel
  - object: orig/G2MJ01/files/RelProd/WispTentacle.rel
