#ifndef _SCRIPTLOADER
#define _SCRIPTLOADER

#include "Kyoto/Graphics/CGraphics.hpp"

class CEntity;
class CInputStream;
class CStateManager;
class CEntityInfo;
class CActorParameters;
class CDamageInfo;
class CTransform4f;
class CScannableParameters;
class CVector2f;
class CVector3f;
class CAABox;
class TAreaId;
class CModelData;
class CHealthInfo;
class CDamageVulnerability;
namespace rstl {
template < class T >
class optional_object;
}
struct SLdrHealthInfo;
struct SLdrDamageVulnerability;
struct SLdrAnimationSet;
struct SEchoParameters;
struct SLdrActorParameters;
struct SLdrDamageInfo;
struct SLdrEchoParameters;
struct SLdrScannableParameters;
struct SLdrEditorProperties;
struct SLdrVector2f;

// Names from the Echoes Wii SEL exports.
CDamageInfo LdrToDamageInfo(const SLdrDamageInfo& data);
CHealthInfo LdrToHealthInfo(const SLdrHealthInfo& data);
CDamageVulnerability LdrToDamageVulnerability(const SLdrDamageVulnerability& data);
rstl::optional_object< CModelData > LdrToModelData(const CVector3f& scale, CAssetId model,
                                               const SLdrAnimationSet& animation,
                                               bool useAnimation);
// Reconstructed name, correlated with Prime and verified Echoes loader callers.
CAABox LoadCAABox(CStateManager& mgr, const TAreaId& areaId, const CVector3f& collisionSize,
                 const CVector3f& collisionOffset);
// Names from the Echoes Wii SEL exports.
CTransform4f LdrToTransform4f(const SLdrEditorProperties& data);
CVector2f LdrToVector2f(const SLdrVector2f& data);
ERglFogMode FogSelectionToFogMode(int selection);
// Guessed name, following the neighbouring SEL-derived conversions.
CScannableParameters LdrToScannableParameters(const SLdrScannableParameters& data);
CActorParameters LdrToActorParameters(const SLdrActorParameters& data);
SEchoParameters LdrToEchoParameters(const SLdrEchoParameters& data);

typedef CEntity* (*FScriptLoader)(CStateManager& mgr, CInputStream& input, CEntityInfo& info);

CEntity* LoadActor(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadActorKeyframe(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadActorRotate(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAdvancedCounter(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAreaDamage(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAIHint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAIJumpPoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAIKeyframe(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAIMannedTurret(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAIWaypoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAmbientAI(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAreaAttributes(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAtomicAlpha(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadAtomicBeta(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadBacteriaSwarm(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadBallTrigger(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadBlogg(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadBrizgee(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCamera(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCameraBlurKeyframe(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCameraFilterKeyframe(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCameraHint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCameraPitch(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCameraShaker(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCameraWaypoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCannonBall(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadChozoGhost(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCoin(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadColorModulate(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCommandPirate(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadConditionalRelay(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadControlHint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadControllerAction(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCounter(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCoverPoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadCrystallite(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDamageableTrigger(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDamageableTriggerOriented(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDamageActor(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDarkCommando(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDarkSamus(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDarkSamusBattleStage(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDarkTrooper(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDebris(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDebrisExtended(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDestructableBarrier(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDigitalGuardian(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDigitalGuardianHead(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDistanceFog(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDock(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDoor(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadEffect(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadElitePirate(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadEmperorIngStage1(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadEmperorIngStage2Tentacle(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadEmperorIngStage3(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadEMPulse(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadEnvFxDensityController(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadEyeBall(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadFishCloud(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadFishCloudModifier(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadFlyerSwarm(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadFlyingPirate(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadFogOverlay(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadFogVolume(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadForgottenObject(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadFrontEndDataNetwork(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGenerator(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGlowBug(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGrapplePoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGrenchler(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGuiMenu(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGuiPlayerJoinManager(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGuiScreen(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGuiSlider(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGuiWidget(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGunTurretBase(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadGunTurretTop(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadHUDHint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadHUDMemo(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadIngs(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadIngBlobSwarm(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadIngBoostBallGuardian(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadIngPuddle(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadIngSnatchingSwarm(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadIngSpaceJumpGuardian(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadIngSpiderBallGuardian(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadKralee(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadKrocus(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadDynamicLight(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadLumite(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadMediumIng(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadMemoryRelay(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadMetaree(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadMetareeSwarm(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadMetroidAlpha(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadMidi(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadMinorIng(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadMysteryFlyer(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadOctopedeSegment(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadParasite(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPathCamera(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPathMeshCtrl(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPickup(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPickupGenerator(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPillBug(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPlatform(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPlantScarabSwarm(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPlayerActor(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPlayerController(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPlayerHint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPlayerStateChange(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPlayerTurret(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPointOfInterest(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPortalTransition(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPuddleSpore(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadPuffer(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRadialDamage(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRandomRelay(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRepulsor(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRezbit(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRiftPortal(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRipper(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRipple(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRoomAcoustics(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRsfAudio(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRubiksPuzzle(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRumbleEffect(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSafeZone(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSafeZoneCrystal(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSandBoss(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSandworm(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadScriptLayerController(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadRelay(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSequenceTimer(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadShadowProjector(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadShredder(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadShrieker(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSilhouette(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSkyRipple(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSnakeWeedSwarm(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSound(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSoundModifier(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSpacePirate(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSpankWeed(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSpawnPoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSpecialFunction(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSpiderBallAttractionSurface(CStateManager& mgr, CInputStream& input,
                                         CEntityInfo& info);
CEntity* LoadSpiderBallWaypoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSpindleCamera(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSpinner(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSplinter(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSplitterCommandModule(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSplitterMainChassis(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSporbBase(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSporbNeedle(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSporbTop(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSporbProjectile(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSteam(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadStoneToad(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadStreamedAudio(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadStreamedMovie(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSubtitle(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSurfaceCamera(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSwitch(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSwampBossStage1(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadSwampBossStage2(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTargetingPoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTeamAI(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTextPane(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTimeKeyframe(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTimer(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTrigger(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTriggerEllipsoid(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTriggerOrientated(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadTryclops(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadVisorFlare(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadVisorGoo(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadWater(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadWallWalker(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadWaypoint(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadWispTentacle(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadWorldLightFader(CStateManager& mgr, CInputStream& input, CEntityInfo& info);
CEntity* LoadWorldTeleporter(CStateManager& mgr, CInputStream& input, CEntityInfo& info);

#endif // _SCRIPTLOADER
